// libs/sveltekit/src/components/SkeletonScrollButton/SkeletonScrollButton.svelte
<script lang="ts">
  export type LoadingState = 'loading' | 'hidden';
  export let state: LoadingState = 'loading';
</script>

<div 
  class="skeleton-scroll-button" 
  aria-hidden={state === 'hidden'} 
  role="status" 
  aria-label="Loading scroll button"
>
  {#if state === 'loading'}
    <div class="skeleton-circle" aria-label="Skeleton button"></div>
  {/if}
</div>

<style lang="css">
  @import './SkeletonScrollButton.css';
</style>

// libs/react/src/components/SkeletonScrollButton/SkeletonScrollButton.tsx
import React from 'react';

interface SkeletonScrollButtonProps {
  state: 'loading' | 'hidden';
}

const SkeletonScrollButton: React.FC<SkeletonScrollButtonProps> = ({ state }) => {
  return (
    <div
      className={`skeleton-scroll-button ${state}`}
      aria-hidden={state === 'hidden'}
      role="status"
      aria-live={state === 'loading' ? 'polite' : 'off'}
    >
      <div className="skeleton-circle"></div>
    </div>
  );
};

export default SkeletonScrollButton;
