// libs/react/src/components/ThreadMessageBubble/ThreadMessageBubble.tsx
import React from 'react';

interface ThreadMessageBubbleProps {
  state: 'sent' | 'received' | 'read' | 'unread';
  message: string;
  timestamp: string;
  isSender: boolean;
}

const ThreadMessageBubble: React.FC<ThreadMessageBubbleProps> = ({ state, message, timestamp, isSender }) => {
  return (
    <div
      className={`message-bubble ${state} ${isSender ? 'sender' : 'receiver'}`}
      role="alert"
      aria-live="polite"
    >
      <p>{message}</p>
      <span className="timestamp">{timestamp}</span>
    </div>
  );
};

export default ThreadMessageBubble;

// libs/sveltekit/src/components/ThreadMessageBubble/ThreadMessageBubble.svelte
<script lang="ts">
  export let message: string = 'This is a message.';
  export let isSent: boolean = true;
  export let isRead: boolean = false;

  function getStatus() {
    return isRead ? 'Read' : 'Unread';
  }
</script>

<div class={`message-bubble ${isSent ? 'sent' : 'received'}`}>
  <p>{message}</p>
  <span class="status">{getStatus()}</span>
</div>

<style lang="css">
  @import './ThreadMessageBubble.css';
</style>
