// libs/vue/src/components/PinnedList/PinnedList.vue
<template>
  <ul class="pinned-list">
    <li
      v-for="item in items"
      :key="item.id"
      :class="[
        'pinned-list-item',
        { pinned: item.pinned, selected: item.id === selectedItem, hover: item.id === hoveredItem }
      ]"
      @click="selectItem(item.id)"
      @mouseover="hoveredItem = item.id"
      @mouseleave="hoveredItem = null"
      :aria-selected="item.id === selectedItem ? 'true' : 'false'"
    >
      {{ item.label }}
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

interface ListItem {
  id: number;
  label: string;
  pinned: boolean;
}

export default defineComponent({
  name: 'PinnedList',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
    selectedItem: {
      type: Number,
      required: true,
    },
  },
  setup(props, { emit }) {
    const hoveredItem = ref<number | null>(null);

    const selectItem = (id: number) => {
      emit('update:selectedItem', id);
    };

    return { hoveredItem, selectItem };
  },
});
</script>

<style scoped lang="css">
.pinned-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.pinned-list-item {
  padding: var(--list-item-padding, 10px 15px);
  margin: 4px 0;
  cursor: pointer;
  transition: background-color 0.2s;
  border-radius: var(--list-border-radius, 4px);
}

.pinned-list-item.pinned {
  background-color: var(--pinned-bg, #ffc107);
}

.pinned-list-item.selected {
  background-color: var(--selected-bg, #007bff);
  color: var(--selected-color, #fff);
}

.pinned-list-item.hover:not(.selected) {
  background-color: var(--hover-bg, #e9ecef);
}
</style>

// libs/react-deprecated/src/components/PinnedList/PinnedList.jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const ListContainer = styled.ul`
  list-style-type: none;
  padding: 0;
  margin: 0;
`;

const ListItem = styled.li`
  padding: 10px;
  margin: 5px 0;
  background-color: ${({ pinned }) => (pinned ? '#f0f8ff' : 'white')};
  border-left: ${({ selected }) => (selected ? '5px solid #007bff' : '5px solid transparent')};
  cursor: pointer;
  transition: background-color 0.3s ease;

  &:hover {
    background-color: #f0f0f0;
  }
`;

const PinnedList = ({ items, pinnedItems, selectedItem, onSelect }) => {
  return (
    <ListContainer>
      {items.map((item, index) => (
        <ListItem
          key={index}
          pinned={pinnedItems.includes(item)}
          selected={selectedItem === item}
          onClick={() => onSelect(item)}
        >
          {item}
        </ListItem>
      ))}
    </ListContainer>
  );
};

PinnedList.propTypes = {
  items: PropTypes.arrayOf(PropTypes.string).isRequired,
  pinnedItems: PropTypes.arrayOf(PropTypes.string),
  selectedItem: PropTypes.string,
  onSelect: PropTypes.func.isRequired,
};

PinnedList.defaultProps = {
  pinnedItems: [],
  selectedItem: '',
};

export default PinnedList;
