// libs/sveltekit/src/components/ScrollableHorizontalNavigation/ScrollableHorizontalNavigation.svelte
<script lang="ts">
  export let items: { label: string; action: () => void }[] = [];
  export let activeIndex: number | null = null;

  const activateItem = (index: number) => {
    activeIndex = index;
    items[index].action();
  };
</script>

<div class="scrollable-horizontal-navigation" role="navigation">
  <div class="nav-container">
    <ul class="nav-items" role="menubar">
      {#each items as item, index}
        <li class={`nav-item ${activeIndex === index ? 'active' : ''}`} role="menuitem">
          <button class="item-link" on:click={() => activateItem(index)}>{item.label}</button>
        </li>
      {/each}
    </ul>
  </div>
</div>

<style lang="css">
  @import './ScrollableHorizontalNavigation.css';
</style>

// libs/vue/src/components/ScrollableHorizontalNavigation/ScrollableHorizontalNavigation.vue
<template>
  <nav role="navigation" aria-label="Horizontal Navigation" class="scrollable-nav">
    <ul class="nav-list" role="menubar">
      <li v-for="(item, index) in navItems" :key="item.label" role="none">
        <a href="#" 
           :class="{ active: activeIndex === index }" 
           @click="setActive(index)" 
           role="menuitem" 
           :aria-current="isActive(index)">
          {{ item.label }}
        </a>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

interface NavItem {
  label: string;
}

export default defineComponent({
  name: 'ScrollableHorizontalNavigation',
  data() {
    return {
      activeIndex: -1,
    };
  },
  props: {
    navItems: {
      type: Array as () => NavItem[],
      required: true,
    },
  },
  methods: {
    setActive(index: number) {
      this.activeIndex = index;
    },
    isActive(index: number) {
      return this.activeIndex === index;
    },
  },
});
</script>

<style lang="css">
@import './ScrollableHorizontalNavigation.css';
</style>
