// app/src/components/UserAvatar/UserAvatar.jsx
// UserAvatar.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './UserAvatar.css';

const UserAvatar = ({ status, imageUrl, onClick }) => {
  return (
    <div className={`user-avatar ${status}`} onClick={onClick}>
      <img src={imageUrl} alt="User Avatar" />
    </div>
  );
};

UserAvatar.propTypes = {
  status: PropTypes.oneOf(['online', 'offline', 'active', 'away', 'busy']).isRequired,
  imageUrl: PropTypes.string.isRequired,
  onClick: PropTypes.func,
};

export default UserAvatar;

// libs/sveltekit/src/components/UserAvatar/UserAvatar.svelte
<script lang="ts">
  export let status: 'online' | 'offline' | 'active' | 'away' | 'busy' = 'offline';

  function getStatusClass() {
    return `status-${status}`;
  }
</script>

<div class="user-avatar {getStatusClass()}" aria-label="{status}">
  <img src="/path/to/avatar.png" alt="User Avatar" />
</div>

<style lang="css">
  @import './UserAvatar.css';
</style>
