// libs/vue/src/components/MultipleChoicePoll/MultipleChoicePoll.vue


<template>
  <div role="group" aria-labelledby="poll-question" class="poll">
    <p id="poll-question">{{ question }}</p>
    <div v-for="option in options" :key="option" class="option">
      <input
        type="checkbox"
        :id="option"
        :value="option"
        v-model="selectedOptions"
        :disabled="isDisabled"
        @change="handleChange"
        :aria-checked="selectedOptions.includes(option)"
      />
      <label :for="option">{{ option }}</label>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'MultipleChoicePoll',
  props: {
    question: {
      type: String,
      required: true,
    },
    options: {
      type: Array as () => string[],
      required: true,
    },
    isDisabled: {
      type: Boolean,
      default: false,
    },
    showResults: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['update:selectedOptions'],
  setup(_, { emit }) {
    const selectedOptions = ref<string[]>([]);
    
    const handleChange = () => {
      emit('update:selectedOptions', selectedOptions.value);
    };

    return {
      selectedOptions,
      handleChange,
    };
  },
});
</script>




<style scoped lang="css">
@import './MultipleChoicePoll.css';
</style>

// libs/react/src/components/MultipleChoicePoll/MultipleChoicePoll.tsx
import React, { useState } from 'react';
import './MultipleChoicePoll.css';

interface OptionProps {
  id: number;
  text: string;
}

interface MultipleChoicePollProps {
  question: string;
  options: OptionProps[];
  disabled: boolean;
  showResults: boolean;
  onVote: (selectedOptions: number[]) => void;
}

const MultipleChoicePoll: React.FC<MultipleChoicePollProps> = ({ question, options, disabled, showResults, onVote }) => {
  const [selectedOptions, setSelectedOptions] = useState<number[]>([]);

  const handleOptionChange = (optionId: number) => {
    if (!disabled) {
      const newSelectedOptions = selectedOptions.includes(optionId)
        ? selectedOptions.filter((id) => id !== optionId)
        : [...selectedOptions, optionId];
      setSelectedOptions(newSelectedOptions);
      onVote(newSelectedOptions);
    }
  };

  return (
    <div className="multiple-choice-poll">
      <h2 className="poll-question">{question}</h2>
      <ul className="poll-options">
        {options.map((option) => (
          <li key={option.id} className={`poll-option ${disabled ? 'disabled' : ''}`}>
            <label>
              <input
                type="checkbox"
                name="poll"
                value={option.id}
                checked={selectedOptions.includes(option.id)}
                onChange={() => handleOptionChange(option.id)}
                disabled={disabled}
                aria-disabled={disabled}
              />
              {option.text}
            </label>
            {showResults && <span className="results-bar" style={{ width: `${Math.random() * 100}%` }} />}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default MultipleChoicePoll;
