// libs/vue/src/components/AudioWaveformDisplay/AudioWaveformDisplay.vue
<template>
  <div class="audio-waveform-display" role="region" aria-label="Audio waveform display">
    <canvas ref="waveformCanvas" aria-label="Waveform visualization"></canvas>
    <div v-if="isLoading" class="loading" aria-live="polite">Loading...</div>
    <button @click="togglePlay" class="control-button" aria-label="Play/Pause">
      {{ isPlaying ? 'Pause' : 'Play' }}
    </button>
    <input
      type="range"
      class="scrub-bar"
      :max="duration"
      v-model="currentTime"
      @input="scrubAudio"
      aria-label="Scrubbing control"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from 'vue';

export default defineComponent({
  name: 'AudioWaveformDisplay',
  props: {
    src: {
      type: String,
      required: true,
    },
  },
  setup() {
    const audioElement = ref<HTMLAudioElement | null>(null);
    const waveformCanvas = ref<HTMLCanvasElement | null>(null);
    const isPlaying = ref(false);
    const isLoading = ref(true);
    const currentTime = ref(0);
    const duration = ref(0);

    const togglePlay = () => {
      if (audioElement.value) {
        if (isPlaying.value) {
          audioElement.value.pause();
        } else {
          audioElement.value.play();
        }
        isPlaying.value = !isPlaying.value;
      }
    };

    const scrubAudio = () => {
      if (audioElement.value) {
        audioElement.value.currentTime = currentTime.value;
      }
    };

    const onLoadedData = () => {
      if (audioElement.value) {
        duration.value = audioElement.value.duration;
        isLoading.value = false;
      }
    };

    onMounted(() => {
      const audio = audioElement.value;
      if (audio) {
        audio.addEventListener('loadeddata', onLoadedData);
        audio.addEventListener('timeupdate', () => {
          currentTime.value = audio.currentTime;
        });
      }

      const canvas = waveformCanvas.value;
      if (canvas) {
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.fillStyle = 'var(--waveform-color)';
          ctx.fillRect(0, 0, canvas.width, canvas.height);
        }
      }
    });

    return {
      isPlaying,
      isLoading,
      currentTime,
      duration,
      togglePlay,
      scrubAudio,
    };
  },
});
</script>

<style scoped lang="css">
.audio-waveform-display {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  padding: 10px;
  background-color: var(--waveform-bg-color);
  border-radius: 5px;
}

.control-button {
  background-color: var(--button-bg-color);
  color: var(--button-text-color);
  border: none;
  padding: 5px 10px;
  cursor: pointer;
  border-radius: 3px;
}

.scrub-bar {
  width: 100%;
}

.loading {
  color: var(--loading-text-color);
}
</style>

// libs/sveltekit/src/components/AudioWaveformDisplay/AudioWaveformDisplay.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let src: string = '';
  export let isPlaying: boolean = false;
  export let isLoading: boolean = false;
  export let currentTime: number = 0;
  export let duration: number = 0;

  let canvasElement: HTMLCanvasElement;
  let audioElement: HTMLAudioElement;
  let audioContext: AudioContext;
  let analyser: AnalyserNode;
  let dataArray: Uint8Array;
  let animationFrameId: number;

  const drawWaveform = () => {
    if (!analyser || !canvasElement) return;

    const canvasCtx = canvasElement.getContext('2d');
    if (!canvasCtx) return;

    const bufferLength = analyser.frequencyBinCount;
    dataArray = new Uint8Array(bufferLength);
    analyser.getByteTimeDomainData(dataArray);

    canvasCtx.fillStyle = 'rgba(255, 255, 255, 1)';
    canvasCtx.fillRect(0, 0, canvasElement.width, canvasElement.height);

    canvasCtx.lineWidth = 2;
    canvasCtx.strokeStyle = 'rgba(0, 0, 0, 1)';
    canvasCtx.beginPath();

    const sliceWidth = canvasElement.width / bufferLength;
    let x = 0;

    for (let i = 0; i < bufferLength; i++) {
      const v = dataArray[i] / 128.0;
      const y = (v * canvasElement.height) / 2;

      if (i === 0) {
        canvasCtx.moveTo(x, y);
      } else {
        canvasCtx.lineTo(x, y);
      }

      x += sliceWidth;
    }

    canvasCtx.lineTo(canvasElement.width, canvasElement.height / 2);
    canvasCtx.stroke();

    animationFrameId = requestAnimationFrame(drawWaveform);
  };

  const initializeAudio = () => {
    audioContext = new AudioContext();
    analyser = audioContext.createAnalyser();
    const source = audioContext.createMediaElementSource(audioElement);
    source.connect(analyser);
    analyser.connect(audioContext.destination);

    analyser.fftSize = 2048;
    drawWaveform();
  };

  const togglePlay = () => {
    if (isPlaying) {
      audioElement.pause();
    } else {
      audioElement.play();
    }
    isPlaying = !isPlaying;
  };

  onMount(() => {
    initializeAudio();
    return () => cancelAnimationFrame(animationFrameId);
  });
</script>

<div class="audio-waveform-display" role="region" aria-label="Audio Waveform Display">
  <audio bind:this={audioElement} src={src} on:loadedmetadata={() => duration = audioElement.duration} on:timeupdate={() => currentTime = audioElement.currentTime}></audio>
  <canvas bind:this={canvasElement} width="600" height="100" aria-label="Waveform"></canvas>
  <button on:click={togglePlay} on:keydown={(e) => e.key === 'Enter' && togglePlay()} aria-label={isPlaying ? 'Pause' : 'Play'}>
    {#if isPlaying}Pause{:else}Play{/if}
  </button>
</div>

<style lang="css">
  @import './AudioWaveformDisplay.css';
</style>
