// libs/react/src/components/Accordion/Accordion.tsx
import React, { useState } from 'react';

export interface AccordionProps {
  title: string;
  content: string;
  isOpen?: boolean;
}

const Accordion: React.FC<AccordionProps> = ({ title, content, isOpen = false }) => {
  const [open, setOpen] = useState(isOpen);

  const toggleAccordion = () => {
    setOpen(!open);
  };

  return (
    <div className="accordion">
      <button
        className="accordion-title"
        onClick={toggleAccordion}
        aria-expanded={open}
        aria-controls="accordion-content"
      >
        {title}
      </button>
      {open && (
        <div id="accordion-content" className="accordion-content">
          {content}
        </div>
      )}
    </div>
  );
};

export default Accordion;

// libs/sveltekit/src/components/Accordion/Accordion.svelte
<script lang="ts">
  export let isOpen: boolean = false;
  export let title: string = 'Accordion Title';
  export let content: string = 'Accordion content goes here.';

  const toggle = () => {
    isOpen = !isOpen;
  };
</script>

<div class="accordion">
  <button 
    class="accordion-header" 
    on:click={toggle} 
    aria-expanded={isOpen} 
    aria-controls="accordion-content"
  >
    {title}
  </button>
  {#if isOpen}
    <div id="accordion-content" class="accordion-content" tabindex="0">
      {content}
    </div>
  {/if}
</div>

<style lang="css">
  @import './Accordion.css';
</style>
