// libs/sveltekit/src/components/ChatList/ChatList.svelte
<script lang="ts">
  export type Chat = { id: number; name: string; lastMessage: string; isSelected: boolean };
  export let chats: Chat[] = [];
  export let onSelect: (id: number) => void = () => {};
  
  const handleKeyPress = (event: KeyboardEvent, id: number) => {
    if (event.key === 'Enter' || event.key === ' ') {
      onSelect(id);
    }
  };
</script>

<div class="chat-list" role="list">
  {#if chats.length > 0}
    {#each chats as { id, name, lastMessage, isSelected }}
      <div 
        class="chat-item {isSelected ? 'selected' : ''}" 
        role="listitem" 
        tabindex="0"
        aria-selected={isSelected}
        on:click={() => onSelect(id)}
        on:keydown={(event) => handleKeyPress(event, id)}
      >
        <div class="chat-name">{name}</div>
        <div class="chat-message">{lastMessage}</div>
      </div>
    {/each}
  {:else}
    <div class="empty-message" role="listitem">No chats available</div>
  {/if}
</div>

<style lang="css">
  @import './ChatList.css';
</style>

// libs/vue/src/components/ChatList/ChatList.vue
<template>
  <div class="chat-list" role="list">
    <div
      v-if="chats.length === 0"
      class="chat-list-empty"
      aria-label="No chats available"
    >
      No chats available
    </div>
    <div
      v-else
      v-for="(chat, index) in chats"
      :key="chat.id"
      :class="['chat-item', { selected: selectedChatId === chat.id }]"
      role="listitem"
      tabindex="0"
      @click="$emit('select', chat.id)"
    >
      {{ chat.name }}
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

interface Chat {
  id: string;
  name: string;
}

export default defineComponent({
  name: 'ChatList',
  props: {
    chats: {
      type: Array as PropType<Chat[]>,
      required: true,
    },
    selectedChatId: {
      type: String as PropType<string | null>,
      default: null,
    },
  },
});
</script>

<style lang="css">
@import './ChatList.css';
</style>
