// libs/react/src/components/ThreadReadReceipt/ThreadReadReceipt.tsx
import React from 'react';

interface ThreadReadReceiptProps {
  status: 'seen' | 'unseen' | 'delivered' | 'failed';
}

const ThreadReadReceipt: React.FC<ThreadReadReceiptProps> = ({ status }) => {
  const getStatusIcon = () => {
    switch (status) {
      case 'seen':
        return '👁️';
      case 'unseen':
        return '📬';
      case 'delivered':
        return '✅';
      case 'failed':
        return '❌';
      default:
        return '📬';
    }
  };

  return (
    <div
      className={`thread-read-receipt ${status}`}
      role="img"
      aria-label={`Read Receipt ${status}`}
    >
      <span>{getStatusIcon()}</span>
    </div>
  );
};

export default ThreadReadReceipt;

// libs/sveltekit/src/components/ThreadReadReceipt/ThreadReadReceipt.svelte
<script lang="ts">
  export type ReceiptState = 'seen' | 'unseen' | 'delivered' | 'failed';
  export let state: ReceiptState = 'unseen';

  function getIcon() {
    switch (state) {
      case 'seen':
        return '👁️';
      case 'delivered':
        return '✅';
      case 'failed':
        return '❌';
      default:
        return '📩';
    }
  }
</script>

<div class="read-receipt" aria-label={`Message ${state}`}>
  {getIcon()}
</div>

<style lang="css">
  @import './ThreadReadReceipt.css';
</style>
