// libs/react-dprecated/src/components/MemberMention/MemberMention.jsx
// MemberMention.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './MemberMention.css';

const MemberMention = ({ isVisible, isClicked, memberName }) => {
  let statusClass = 'hidden';
  if (isVisible) {
    statusClass = isClicked ? 'clicked' : 'visible';
  }

  return (
    <span className={`member-mention ${statusClass}`}>
      @{memberName}
    </span>
  );
};

MemberMention.propTypes = {
  isVisible: PropTypes.bool.isRequired,
  isClicked: PropTypes.bool.isRequired,
  memberName: PropTypes.string.isRequired,
};

export default MemberMention;

// libs/sveltekit/src/components/MemberMention/MemberMention.svelte
<script lang="ts">
  export let visible: boolean = true;
  export let clicked: boolean = false;
  export let memberName: string = 'Member';

  function handleClick() {
    clicked = true;
  }
</script>

{#if visible}
  <div 
    class="member-mention" 
    role="button" 
    aria-pressed={clicked}
    tabindex="0"
    on:click={handleClick} 
    on:keydown={(e) => e.key === 'Enter' ? handleClick() : null}
  >
    @{memberName}
  </div>
{/if}

<style lang="css">
  @import './MemberMention.css';
</style>
