// libs/svelte/src/components/FileUpload/FileUpload.svelte
<script lang="ts">
  export let multiple: boolean = false;
  export let uploadProgress: number = 0;
  export let isDragAndDrop: boolean = true;

  let files: File[] = [];

  function handleFileChange(event: Event) {
    const inputFiles = Array.from((event.target as HTMLInputElement).files || []);
    files = inputFiles;
  }

  function handleDragOver(event: DragEvent) {
    event.preventDefault();
  }

  function handleDrop(event: DragEvent) {
    event.preventDefault();
    const droppedFiles = Array.from(event.dataTransfer?.files || []);
    files = droppedFiles;
  }
</script>

<div
  class="file-upload"
  on:dragover={handleDragOver}
  on:drop={handleDrop}
  aria-label="File Upload"
>
  {#if isDragAndDrop}
    <div class="drop-area" tabindex="0">
      Drag and drop files here or click to browse
    </div>
  {/if}
  <input
    type="file"
    class="file-input"
    multiple={multiple}
    on:change={handleFileChange}
    aria-hidden="true"
  />
  {#if uploadProgress > 0}
    <div class="progress-bar" role="progressbar" aria-valuenow={uploadProgress} aria-valuemin="0" aria-valuemax="100">
      <div class="progress" style="width: {uploadProgress}%"></div>
    </div>
  {/if}
</div>

<style lang="css">
  @import './FileUpload.css';
</style>

// libs/vue/src/components/FileUpload/FileUpload.vue

<template>
  <div 
    class="file-upload-container" 
    :class="{ 'drag-over': isDragOver }" 
    @dragover.prevent="handleDragOver" 
    @dragleave.prevent="handleDragLeave" 
    @drop.prevent="handleDrop"
  >
    <input 
      type="file" 
      :multiple="multiple" 
      @change="handleFileSelect" 
      aria-label="Upload File(s)"
    />
    <div v-if="progress" class="progress-bar" role="progressbar" :aria-valuenow="progress" aria-valuemin="0" aria-valuemax="100">
      <div class="progress" :style="{ width: progress + '%' }"></div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'FileUpload',
  props: {
    multiple: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    const isDragOver = ref(false);
    const progress = ref<number | null>(null);

    const handleFileSelect = (event: Event) => {
      const input = event.target as HTMLInputElement;
      const files = input.files;
      if (files) {
        // Process files
      }
    };

    const handleDragOver = () => {
      isDragOver.value = true;
    };

    const handleDragLeave = () => {
      isDragOver.value = false;
    };

    const handleDrop = (event: DragEvent) => {
      isDragOver.value = false;
      const files = event.dataTransfer?.files;
      if (files) {
        // Process files
      }
    };

    return { isDragOver, progress, handleFileSelect, handleDragOver, handleDragLeave, handleDrop };
  },
});
</script>




<style scoped lang="css">
@import './FileUpload.css';
</style>
