// app/src/32342/Selectablelistwithitemdetails/Selectablelistwithitemdetails.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const ListContainer = styled.div`
  border: 1px solid #ccc;
  border-radius: 5px;
`;

const ListItem = styled.div`
  padding: 10px 15px;
  margin: 5px 0;
  border-bottom: 1px solid #eee;
  background-color: ${props => (props.selected ? '#d3f4ff' : '#fff')};
  cursor: pointer;
  &:hover {
    background-color: #f1f1f1;
  }
  &:last-child {
    border-bottom: none;
  }
`;

const ItemDetails = styled.div`
  padding: 10px;
  background-color: #f9f9f9;
  display: ${props => (props.open ? 'block' : 'none')};
`;

const Selectablelistwithitemdetails = ({ items }) => {
  const [selectedItem, setSelectedItem] = useState(null);
  const [detailsOpen, setDetailsOpen] = useState(false);

  const handleItemClick = (id) => {
    setSelectedItem(selectedItem === id ? null : id);
    setDetailsOpen(selectedItem !== id);
  };

  return (
    <ListContainer>
      {items.map(item => (
        <div key={item.id}>
          <ListItem
            selected={selectedItem === item.id}
            onClick={() => handleItemClick(item.id)}
          >
            {item.name}
          </ListItem>
          <ItemDetails open={selectedItem === item.id && detailsOpen}>
            {item.details}
          </ItemDetails>
        </div>
      ))}
    </ListContainer>
  );
};

Selectablelistwithitemdetails.propTypes = {
  items: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.number.isRequired,
      name: PropTypes.string.isRequired,
      details: PropTypes.string,
    })
  ).isRequired,
};

export default Selectablelistwithitemdetails;

// libs/vue/src/components/SelectableListWithItemDetails/SelectableListWithItemDetails.vue
<template>
  <div class="selectable-list">
    <ul class="selectable-list-items">
      <li
        v-for="item in items"
        :key="item.id"
        :class="['selectable-list-item', { selected: item.id === selectedItem, disabled: disabled }]"
        @click="toggleSelection(item.id)"
      >
        <div class="item-content">
          {{ item.label }}
          <button @click.stop="toggleDetails(item.id)" class="details-button" :aria-expanded="item.id === openDetails ? 'true' : 'false'">
            {{ item.id === openDetails ? 'Hide Details' : 'Show Details' }}
          </button>
        </div>
        <div v-if="item.id === openDetails" class="item-details">
          {{ item.details }}
        </div>
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

interface ListItem {
  id: number;
  label: string;
  details: string;
}

export default defineComponent({
  name: 'SelectableListWithItemDetails',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    const selectedItem = ref<number | null>(null);
    const openDetails = ref<number | null>(null);

    const toggleSelection = (id: number) => {
      if (!disabled) {
        selectedItem.value = selectedItem.value === id ? null : id;
      }
    };

    const toggleDetails = (id: number) => {
      openDetails.value = openDetails.value === id ? null : id;
    };

    return { selectedItem, openDetails, toggleSelection, toggleDetails };
  },
});
</script>

<style scoped lang="css">
.selectable-list {
  border: var(--list-border, 1px solid #ddd);
  border-radius: var(--list-border-radius, 4px);
}

.selectable-list-items {
  list-style: none;
  padding: 0;
  margin: 0;
}

.selectable-list-item {
  padding: var(--list-item-padding, 10px 15px);
  margin: 4px 0;
  cursor: pointer;
  transition: background-color 0.2s;
}

.selectable-list-item.selected {
  background-color: var(--selected-bg, #d0eaff);
}

.selectable-list-item.disabled {
  color: var(--disabled-color, #ccc);
  cursor: not-allowed;
}

.item-details {
  padding: var(--details-padding, 8px 12px);
  background-color: var(--details-bg, #f8f9fa);
}

.details-button {
  background: none;
  border: none;
  color: var(--button-color, #007bff);
  cursor: pointer;
  padding: 0;
}
</style>
