// libs/react-deprecated/src/components/LoadingBarsWithSteps/LoadingBarsWithSteps.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './LoadingBarsWithSteps.css';

const LoadingBarsWithSteps = ({ steps, currentStep }) => {
  return (
    <div className="loading-steps">
      {steps.map((step, index) => {
        const stepStatus = index < currentStep ? 'completed' : index === currentStep ? 'active' : 'inactive';
        return (
          <div key={index} className={`step ${stepStatus}`}>
            <div className="step-label">{step.label}</div>
            <div className="step-bar" />
          </div>
        );
      })}
    </div>
  );
};

LoadingBarsWithSteps.propTypes = {
  steps: PropTypes.arrayOf(
    PropTypes.shape({
      label: PropTypes.string.isRequired,
    })
  ).isRequired,
  currentStep: PropTypes.number.isRequired,
};

export default LoadingBarsWithSteps;

// svelte/components/LoadingBarsWithSteps/LoadingBarsWithSteps.svelte
<script lang="ts">
  export type Step = {
    label: string;
    status: 'active' | 'completed' | 'inactive';
  };

  export let steps: Step[] = [];
  export let ariaLabel: string = 'Loading Bars with Steps';
</script>

<div class="loading-bars-with-steps" role="progressbar" aria-label={ariaLabel}>
  {#each steps as { label, status }}
    <div class={`step ${status}`}>
      <div class="step-label">{label}</div>
      <div class="loading-bar"></div>
    </div>
  {/each}
</div>

<style lang="css">
  @import './LoadingBarsWithSteps.css';
</style>
