// libs/vue/src/components/TextTool/TextTool.vue


<template>
  <div class="text-tool">
    <button @click="toggleActive" :class="{ active: isActive }" aria-label="Text Tool">Text Tool</button>
    <div v-if="isActive" class="text-options">
      <label for="font-style">Font Style:</label>
      <select id="font-style" v-model="fontStyle">
        <option v-for="style in fontStyles" :key="style" :value="style">{{ style }}</option>
      </select>
      
      <label for="font-size">Font Size:</label>
      <input id="font-size" type="number" v-model="fontSize" />

      <label for="font-color">Color:</label>
      <input id="font-color" type="color" v-model="fontColor" />

      <label for="alignment">Alignment:</label>
      <select id="alignment" v-model="alignment">
        <option v-for="align in alignments" :key="align" :value="align">{{ align }}</option>
      </select>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'TextTool',
  setup() {
    const isActive = ref(false);
    const fontStyle = ref('Arial');
    const fontSize = ref(16);
    const fontColor = ref('#000000');
    const alignment = ref('left');
    
    const fontStyles = ['Arial', 'Verdana', 'Times New Roman'];
    const alignments = ['left', 'center', 'right'];

    const toggleActive = () => {
      isActive.value = !isActive.value;
    };

    return {
      isActive,
      fontStyle,
      fontSize,
      fontColor,
      alignment,
      fontStyles,
      alignments,
      toggleActive,
    };
  },
});
</script>




<style scoped lang="css">
@import './TextTool.css';
</style>

// libs/react/src/components/TextTool/TextTool.tsx
import React, { useState } from 'react';
import './TextTool.css';

interface TextToolProps {
  active: boolean;
  onAddText: (text: string, options: TextOptions) => void;
}

interface TextOptions {
  fontStyle: string;
  fontSize: number;
  color: string;
  alignment: 'left' | 'center' | 'right';
}

const TextTool: React.FC<TextToolProps> = ({ active, onAddText }) => {
  const [text, setText] = useState<string>('');
  const [fontStyle, setFontStyle] = useState<string>('Arial');
  const [fontSize, setFontSize] = useState<number>(16);
  const [color, setColor] = useState<string>('#000000');
  const [alignment, setAlignment] = useState<'left' | 'center' | 'right'>('left');

  const handleAddText = () => {
    if (active && text) {
      onAddText(text, { fontStyle, fontSize, color, alignment });
    }
  };

  return (
    <div className={`text-tool ${active ? 'active' : ''}`}>
      <textarea 
        value={text} 
        onChange={(e) => setText(e.target.value)} 
        placeholder="Enter text here" 
        aria-label="Text input"
      />
      <select 
        value={fontStyle} 
        onChange={(e) => setFontStyle(e.target.value)} 
        aria-label="Font style"
      >
        <option value="Arial">Arial</option>
        <option value="Times New Roman">Times New Roman</option>
        <option value="Courier New">Courier New</option>
      </select>
      <input 
        type="number" 
        value={fontSize} 
        onChange={(e) => setFontSize(Number(e.target.value))} 
        min="10" 
        max="100" 
        aria-label="Font size"
      />
      <input 
        type="color" 
        value={color} 
        onChange={(e) => setColor(e.target.value)} 
        aria-label="Font color"
      />
      <select 
        value={alignment} 
        onChange={(e) => setAlignment(e.target.value as 'left' | 'center' | 'right')} 
        aria-label="Text alignment"
      >
        <option value="left">Left</option>
        <option value="center">Center</option>
        <option value="right">Right</option>
      </select>
      <button onClick={handleAddText} disabled={!active || !text} aria-label="Add text to canvas">
        Add Text
      </button>
    </div>
  );
};

export default TextTool;
