// libs/react/src/components/Pagination/Pagination.tsx
import React from 'react';

interface PaginationProps {
  totalPages: number;
  currentPage: number;
  onPageChange: (page: number) => void;
}

const Pagination: React.FC<PaginationProps> = ({ totalPages, currentPage, onPageChange }) => {
  const handlePageClick = (page: number) => {
    if (page !== currentPage) {
      onPageChange(page);
    }
  };

  return (
    <nav aria-label="Pagination">
      <ul className="pagination">
        {[...Array(totalPages)].map((_, index) => (
          <li
            key={index}
            className={`page-item ${currentPage === index + 1 ? 'active' : ''}`}
            onClick={() => handlePageClick(index + 1)}
            aria-current={currentPage === index + 1 ? 'page' : undefined}
          >
            {index + 1}
          </li>
        ))}
      </ul>
    </nav>
  );
};

export default Pagination;

// libs/sveltekit/src/components/Pagination/Pagination.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let totalPages: number = 1;
  export let currentPage: number = 1;

  const dispatch = createEventDispatcher();

  function selectPage(page: number) {
    if (page < 1 || page > totalPages) return;
    dispatch('change', { page });
  }

  function handleKeydown(event: KeyboardEvent, page: number) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      selectPage(page);
    }
  }
</script>

<nav aria-label="Pagination Navigation">
  <ul class="pagination">
    {#each Array(totalPages) as _, index}
      <li
        class="pagination-item"
        class:active={currentPage === index + 1}
        role="button"
        aria-current={currentPage === index + 1 ? 'page' : undefined}
        aria-label={`Page ${index + 1}`}
        tabindex="0"
        on:click={() => selectPage(index + 1)}
        on:keydown={(event) => handleKeydown(event, index + 1)}
      >
        {index + 1}
      </li>
    {/each}
  </ul>
</nav>

<style lang="css">
  @import './Pagination.css';
</style>
