// libs/vue/src/components/CommandPalette/CommandPalette.vue
<template>
  <div class="command-palette" :class="{ open: isOpen }" role="dialog" aria-modal="true" v-if="isOpen">
    <input
      type="text"
      class="command-input"
      v-model="query"
      @input="filterCommands"
      @keydown.down="navigate('down')"
      @keydown.up="navigate('up')"
      @keydown.enter="selectCommand"
      placeholder="Type a command..."
      aria-label="Command input"
    />
    <ul class="command-list" role="listbox">
      <li
        v-for="(command, index) in filteredCommands"
        :key="command.id"
        :class="{ 'active': activeIndex === index }"
        role="option"
        :aria-selected="activeIndex === index"
        @click="selectCommand(index)"
        @mouseenter="setActiveIndex(index)"
        tabindex="-1"
      >
        {{ command.name }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

export default defineComponent({
  name: 'CommandPalette',
  props: {
    commands: {
      type: Array as () => Array<{ id: number, name: string }>,
      required: true,
    },
    isOpen: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const query = ref('');
    const activeIndex = ref(-1);

    const filteredCommands = computed(() =>
      props.commands.filter(command =>
        command.name.toLowerCase().includes(query.value.toLowerCase())
      )
    );

    const filterCommands = () => {
      activeIndex.value = -1;
    };

    const navigate = (direction: 'up' | 'down') => {
      if (direction === 'down') {
        activeIndex.value = (activeIndex.value + 1) % filteredCommands.value.length;
      } else if (direction === 'up') {
        activeIndex.value = (activeIndex.value - 1 + filteredCommands.value.length) % filteredCommands.value.length;
      }
    };

    const selectCommand = (index = activeIndex.value) => {
      if (index >= 0 && index < filteredCommands.value.length) {
        alert(`Command Selected: ${filteredCommands.value[index].name}`);
        query.value = '';
      }
    };

    const setActiveIndex = (index: number) => {
      activeIndex.value = index;
    };

    return { query, filteredCommands, activeIndex, filterCommands, navigate, selectCommand, setActiveIndex };
  },
});
</script>

<style lang="css">
@import './CommandPalette.css';
</style>

// libs/sveltekit/src/components/CommandPalette/CommandPalette.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  export let isOpen: boolean = false;
  export let commands: string[] = [];
  export let activeIndex: number = -1;

  let inputElement: HTMLInputElement;

  function togglePalette() {
    isOpen = !isOpen;
  }

  function handleKeyDown(event: KeyboardEvent) {
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      activeIndex = (activeIndex + 1) % commands.length;
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      activeIndex = (activeIndex - 1 + commands.length) % commands.length;
    } else if (event.key === 'Enter' && activeIndex >= 0) {
      selectCommand(commands[activeIndex]);
    }
  }

  function selectCommand(command: string) {
    const event = new CustomEvent('select', {
      detail: { command }
    });
    dispatchEvent(event);
  }

  onMount(() => {
    if (isOpen) {
      inputElement.focus();
    }
  });
</script>

<div class="command-palette" class:open={isOpen}>
  {#if isOpen}
    <input
      bind:this={inputElement}
      type="text"
      placeholder="Type a command..."
      on:keydown={handleKeyDown}
      aria-label="Command palette input"
    />
    <ul>
      {#each commands as command, index}
        <li
          class:active={index === activeIndex}
          on:click={() => selectCommand(command)}
          role="option"
          tabindex="0"
          on:keypress={(e) => e.key === 'Enter' && selectCommand(command)}
        >
          {command}
        </li>
      {/each}
    </ul>
  {/if}
</div>

<style lang="css">
  @import './CommandPalette.css';
</style>
