// app/src/components/SearchBox/SearchBox.jsx
// SearchBox.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './SearchBox.css';

const SearchBox = ({ placeholder, value, onChange }) => {
  const [isFocused, setIsFocused] = useState(false);

  return (
    <input
      type="text"
      className={`search-box ${isFocused ? 'focused' : 'unfocused'}`}
      placeholder={placeholder}
      value={value}
      onChange={onChange}
      onFocus={() => setIsFocused(true)}
      onBlur={() => setIsFocused(false)}
    />
  );
};

SearchBox.propTypes = {
  placeholder: PropTypes.string,
  value: PropTypes.string.isRequired,
  onChange: PropTypes.func.isRequired,
};

export default SearchBox;

// libs/vue/src/components/SearchBox/SearchBox.vue
<template>
  <div class="search-box">
    <input
      type="text"
      :value="value"
      @input="$emit('update:value', $event.target.value)"
      @focus="isFocused = true"
      @blur="isFocused = false"
      class="search-input"
      :placeholder="placeholder"
      aria-label="Search"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'SearchBox',
  props: {
    value: {
      type: String,
      required: false,
      default: '',
    },
    placeholder: {
      type: String,
      required: false,
      default: 'Search...',
    },
  },
  setup() {
    const isFocused = ref(false);
    return { isFocused };
  },
});
</script>

<style lang="css">
@import './SearchBox.css';
</style>
