// libs/react/src/components/GroupMemberAvatar/GroupMemberAvatar.tsx
import React from 'react';

interface GroupMemberAvatarProps {
  imageUrl: string;
  status: 'online' | 'offline' | 'active' | 'away' | 'busy';
  altText: string;
}

const GroupMemberAvatar: React.FC<GroupMemberAvatarProps> = ({ imageUrl, status, altText }) => {
  return (
    <div className={`group-member-avatar ${status}`} aria-label={`${altText} is ${status}`}>
      <img src={imageUrl} alt={altText} className="avatar-image" />
      <span className={`status-indicator ${status}`} />
    </div>
  );
};

export default GroupMemberAvatar;

// libs/sveltekit/src/components/GroupMemberAvatar/GroupMemberAvatar.svelte
<script lang="ts">
  export let imageUrl: string = '';
  export let status: 'online' | 'offline' | 'active' | 'away' | 'busy' = 'offline';
</script>

<div class="group-member-avatar" role="img" aria-label="Group member avatar">
  <img src={imageUrl} alt="Group member" class="avatar-image" />
  <span class="status-indicator {status}" aria-label={status}></span>
</div>

<style lang="css">
  @import './GroupMemberAvatar.css';
</style>
