// libs/sveltekit/src/components/VideoPlayerAdvanced/VideoPlayerAdvanced.svelte
<script lang="ts">
  export let isPlaying: boolean = false;
  export let isPaused: boolean = true;
  export let isBuffering: boolean = false;
  export let isFullscreen: boolean = false;
  export let areSubtitlesOn: boolean = false;
  export let isPiPMode: boolean = false;

  function togglePlayPause() {
    isPlaying = !isPlaying;
    isPaused = !isPaused;
  }

  function toggleFullscreen() {
    isFullscreen = !isFullscreen;
  }

  function toggleSubtitles() {
    areSubtitlesOn = !areSubtitlesOn;
  }

  function togglePiPMode() {
    isPiPMode = !isPiPMode;
  }
</script>

<div class="video-player-advanced" role="region" aria-label="Advanced Video Player">
  <video controls bind:currentTime bind:paused={isPaused}>
    <source src="video.mp4" type="video/mp4" />
    {#if areSubtitlesOn}
      <track kind="subtitles" src="subtitles.vtt" srclang="en" label="English" default />
    {/if}
    Your browser does not support the video tag.
  </video>
  <div class="player-controls">
    <button on:click={togglePlayPause} aria-pressed={isPlaying}>
      {isPlaying ? 'Pause' : 'Play'}
    </button>
    <button on:click={toggleFullscreen} aria-pressed={isFullscreen}>
      {isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
    </button>
    <button on:click={toggleSubtitles} aria-pressed={areSubtitlesOn}>
      {areSubtitlesOn ? 'Subtitles Off' : 'Subtitles On'}
    </button>
    <button on:click={togglePiPMode} aria-pressed={isPiPMode}>
      {isPiPMode ? 'Exit PiP' : 'PiP Mode'}
    </button>
  </div>
</div>

<style lang="css">
  @import './VideoPlayerAdvanced.css';
</style>

// libs/react/src/components/VideoPlayerAdvanced/VideoPlayerAdvanced.tsx
import React, { useState } from 'react';

interface VideoPlayerAdvancedProps {
  videoUrl: string;
  title: string;
  subtitlesUrl?: string;
}

const VideoPlayerAdvanced: React.FC<VideoPlayerAdvancedProps> = ({ videoUrl, title, subtitlesUrl }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isBuffering, setIsBuffering] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [areSubtitlesVisible, setAreSubtitlesVisible] = useState(false);
  const [isPiPMode, setIsPiPMode] = useState(false);

  const togglePlayPause = () => {
    setIsPlaying(!isPlaying);
  };

  const toggleFullscreen = () => {
    setIsFullscreen(!isFullscreen);
  };

  const toggleSubtitles = () => {
    setAreSubtitlesVisible(!areSubtitlesVisible);
  };

  const togglePiPMode = () => {
    setIsPiPMode(!isPiPMode);
  };

  return (
    <div className={`video-player-advanced ${isFullscreen ? 'fullscreen' : ''}`}>
      <h2>{title}</h2>
      <video src={videoUrl} controls autoPlay={isPlaying} onPlay={() => setIsBuffering(false)} onWaiting={() => setIsBuffering(true)}>
        {subtitlesUrl && <track kind="subtitles" src={subtitlesUrl} srcLang="en" label="English" default={areSubtitlesVisible} />}
      </video>
      <div className="controls">
        <button onClick={togglePlayPause} aria-label={isPlaying ? 'Pause' : 'Play'}>
          {isPlaying ? 'Pause' : 'Play'}
        </button>
        <button onClick={toggleFullscreen} aria-label={isFullscreen ? 'Exit Fullscreen' : 'Enter Fullscreen'}>
          {isFullscreen ? 'Exit Fullscreen' : 'Enter Fullscreen'}
        </button>
        <button onClick={toggleSubtitles} aria-label={areSubtitlesVisible ? 'Hide Subtitles' : 'Show Subtitles'}>
          {areSubtitlesVisible ? 'Subtitles Off' : 'Subtitles On'}
        </button>
        <button onClick={togglePiPMode} aria-label={isPiPMode ? 'Exit PiP Mode' : 'Enter PiP Mode'}>
          {isPiPMode ? 'Exit PiP' : 'Enter PiP'}
        </button>
      </div>
      {isBuffering && <div className="buffering">Buffering...</div>}
    </div>
  );
};

export default VideoPlayerAdvanced;
