// libs/sveltekit/src/components/VideoPlayerAdvanced/VideoPlayerAdvanced.svelte
<script lang="ts">
  export let isPlaying: boolean = false;
  export let isPaused: boolean = true;
  export let isBuffering: boolean = false;
  export let isFullscreen: boolean = false;
  export let areSubtitlesOn: boolean = false;
  export let isPiPMode: boolean = false;

  function togglePlayPause() {
    isPlaying = !isPlaying;
    isPaused = !isPaused;
  }

  function toggleFullscreen() {
    isFullscreen = !isFullscreen;
  }

  function toggleSubtitles() {
    areSubtitlesOn = !areSubtitlesOn;
  }

  function togglePiPMode() {
    isPiPMode = !isPiPMode;
  }
</script>

<div class="video-player-advanced" role="region" aria-label="Advanced Video Player">
  <video controls bind:currentTime bind:paused={isPaused}>
    <source src="video.mp4" type="video/mp4" />
    {#if areSubtitlesOn}
      <track kind="subtitles" src="subtitles.vtt" srclang="en" label="English" default />
    {/if}
    Your browser does not support the video tag.
  </video>
  <div class="player-controls">
    <button on:click={togglePlayPause} aria-pressed={isPlaying}>
      {isPlaying ? 'Pause' : 'Play'}
    </button>
    <button on:click={toggleFullscreen} aria-pressed={isFullscreen}>
      {isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
    </button>
    <button on:click={toggleSubtitles} aria-pressed={areSubtitlesOn}>
      {areSubtitlesOn ? 'Subtitles Off' : 'Subtitles On'}
    </button>
    <button on:click={togglePiPMode} aria-pressed={isPiPMode}>
      {isPiPMode ? 'Exit PiP' : 'PiP Mode'}
    </button>
  </div>
</div>

<style lang="css">
  @import './VideoPlayerAdvanced.css';
</style>

// libs/react/src/components/VideoPlayerAdvanced/VideoPlayerAdvanced.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './VideoPlayerAdvanced.css';

const VideoPlayerAdvanced = ({ videoSrc, subtitlesSrc }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isSubtitlesOn, setIsSubtitlesOn] = useState(false);
  const [isPiPMode, setIsPiPMode] = useState(false);
  const [isBuffering, setIsBuffering] = useState(false);

  const handlePlayPause = () => {
    setIsPlaying(!isPlaying);
  };

  const handleFullscreenToggle = () => {
    setIsFullscreen(!isFullscreen);
  };

  const handleSubtitlesToggle = () => {
    setIsSubtitlesOn(!isSubtitlesOn);
  };

  const handlePiPToggle = () => {
    setIsPiPMode(!isPiPMode);
  };

  return (
    <div className={`video-player-advanced ${isFullscreen ? 'fullscreen' : ''}`}>
      <video
        src={videoSrc}
        controls
        onPlay={() => setIsBuffering(false)}
        onPause={() => setIsPlaying(false)}
        className={isBuffering ? 'buffering' : ''}
      >
        {isSubtitlesOn && <track default kind="subtitles" src={subtitlesSrc} />}
      </video>
      <div className="video-controls">
        <button onClick={handlePlayPause}>
          {isPlaying ? 'Pause' : 'Play'}
        </button>
        <button onClick={handleFullscreenToggle}>
          {isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
        </button>
        <button onClick={handleSubtitlesToggle}>
          {isSubtitlesOn ? 'Subtitles Off' : 'Subtitles On'}
        </button>
        <button onClick={handlePiPToggle}>
          {isPiPMode ? 'Exit PiP' : 'PiP Mode'}
        </button>
      </div>
    </div>
  );
};

VideoPlayerAdvanced.propTypes = {
  videoSrc: PropTypes.string.isRequired,
  subtitlesSrc: PropTypes.string,
};

export default VideoPlayerAdvanced;
