// app/src/components/SendButton/SendButton.jsx
// SendButton.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './SendButton.css';

const SendButton = ({ state, onClick }) => {
  return (
    <button
      className={`send-button ${state}`}
      onClick={onClick}
      disabled={state === 'disabled'}
    >
      Send
    </button>
  );
};

SendButton.propTypes = {
  state: PropTypes.oneOf(['enabled', 'disabled', 'hovered', 'clicked']).isRequired,
  onClick: PropTypes.func.isRequired,
};

export default SendButton;

// libs/vue/src/components/SendButton/SendButton.vue
<template>
  <button
    :class="state"
    :disabled="state === 'disabled'"
    @mouseover="handleMouseOver"
    @mouseleave="handleMouseLeave"
    @click="handleClick"
    aria-label="Send message"
  >
    Send
  </button>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'SendButton',
  props: {
    state: {
      type: String,
      default: 'enabled',
      validator: (value: string) => ['enabled', 'disabled', 'hovered', 'clicked'].includes(value),
    },
  },
  emits: ['update:state'],
  setup(props, { emit }) {
    const handleMouseOver = () => {
      if (props.state !== 'disabled') {
        emit('update:state', 'hovered');
      }
    };

    const handleMouseLeave = () => {
      if (props.state !== 'disabled') {
        emit('update:state', 'enabled');
      }
    };

    const handleClick = () => {
      if (props.state !== 'disabled') {
        emit('update:state', 'clicked');
        setTimeout(() => emit('update:state', 'enabled'), 200);
      }
    };

    return {
      handleMouseOver,
      handleMouseLeave,
      handleClick,
    };
  },
});
</script>

<style lang="css">
@import './SendButton.css';
</style>
