// libs/react/src/components/SkeletonTypingIndicator/SkeletonTypingIndicator.tsx
import React from 'react';

interface SkeletonTypingIndicatorProps {
  state: 'loading' | 'hidden';
}

const SkeletonTypingIndicator: React.FC<SkeletonTypingIndicatorProps> = ({ state }) => {
  return (
    <div
      className={`skeleton-typing-indicator ${state}`}
      aria-hidden={state === 'hidden'}
      role="status"
      aria-live={state === 'loading' ? 'polite' : 'off'}
    >
      <div className="skeleton-dot"></div>
      <div className="skeleton-dot"></div>
      <div className="skeleton-dot"></div>
    </div>
  );
};

export default SkeletonTypingIndicator;

// libs/sveltekit/src/components/SkeletonTypingIndicator/SkeletonTypingIndicator.svelte
<script lang="ts">
  export type LoadingState = 'loading' | 'hidden';
  export let state: LoadingState = 'loading';
</script>

<div 
  class="skeleton-typing-indicator" 
  aria-hidden={state === 'hidden'} 
  role="status" 
  aria-label="Loading typing indicator"
>
  {#if state === 'loading'}
    <div class="dot"></div>
    <div class="dot"></div>
    <div class="dot"></div>
  {/if}
</div>

<style lang="css">
  @import './SkeletonTypingIndicator.css';
</style>
