// libs/vue/src/components/Textarea/Textarea.vue


<template>
  <div class="textarea-container">
    <textarea 
      :placeholder="placeholder" 
      :disabled="disabled"
      aria-label="Textarea input"
      v-model="text"
      @input="onInput"
    ></textarea>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'Textarea',
  props: {
    placeholder: {
      type: String,
      default: 'Enter text...',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['input'],
  setup(_, { emit }) {
    const text = ref('');

    const onInput = () => {
      emit('input', text.value);
    };

    return {
      text,
      onInput,
    };
  },
});
</script>




<style scoped lang="css">
@import './Textarea.css';
</style>

// libs/sveltekit/src/components/Textarea/Textarea.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  export let value: string = '';
  export let placeholder: string = 'Enter text...';
  export let disabled: boolean = false;

  const dispatch = createEventDispatcher();

  function handleInput(event: Event) {
    const target = event.target as HTMLTextAreaElement;
    value = target.value;
    dispatch('input', { value });
  }
</script>

<div class="textarea-container" aria-disabled={disabled}>
  <textarea
    bind:value={value}
    placeholder={placeholder}
    on:input={handleInput}
    disabled={disabled}
    aria-label="Text input"
  ></textarea>
</div>

<style lang="css">
  @import './Textarea.css';
</style>
