// libs/react-dprecated/src/components/VisualCueForAccessibilityFocusIndicator/VisualCueForAccessibilityFocusIndicator.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './VisualCueForAccessibilityFocusIndicator.css';

const VisualCueForAccessibilityFocusIndicator = ({ isFocused, label }) => {
  return (
    <div className={`visual-cue ${isFocused ? 'focused' : 'unfocused'}`}>
      {label}
    </div>
  );
};

VisualCueForAccessibilityFocusIndicator.propTypes = {
  isFocused: PropTypes.bool.isRequired,
  label: PropTypes.string.isRequired,
};

VisualCueForAccessibilityFocusIndicator.defaultProps = {
  isFocused: false,
  label: 'Focus indicator',
};

export default VisualCueForAccessibilityFocusIndicator;

// libs/vue/src/components/VisualCueForAccessibilityFocusIndicator/VisualCueForAccessibilityFocusIndicator.vue
<template>
  <div class="focus-indicator" :class="{ focused: isFocused }" tabindex="0" @focus="handleFocus" @blur="handleBlur">
    <p>{{ isFocused ? 'Focused' : 'Unfocused' }}</p>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'VisualCueForAccessibilityFocusIndicator',
  setup() {
    const isFocused = ref(false);

    const handleFocus = () => {
      isFocused.value = true;
    };

    const handleBlur = () => {
      isFocused.value = false;
    };

    return { isFocused, handleFocus, handleBlur };
  },
});
</script>

<style lang="css">
@import './VisualCueForAccessibilityFocusIndicator.css';
</style>
