// libs/react/src/components/SendButton/SendButton.tsx
import React from 'react';

interface SendButtonProps {
  disabled?: boolean;
  onClick?: () => void;
}

const SendButton: React.FC<SendButtonProps> = ({ disabled = false, onClick }) => {
  return (
    <button
      className={`send-button ${disabled ? 'disabled' : 'enabled'}`}
      onClick={onClick}
      disabled={disabled}
      aria-label="Send message"
    >
      Send
    </button>
  );
};

export default SendButton;

// libs/sveltekit/src/components/SendButton/SendButton.svelte
<script lang="ts">
  export let disabled: boolean = false;
  export let label: string = 'Send';

  function handleClick() {
    if (!disabled) {
      // Handle send action
    }
  }
</script>

<button
  class="send-button"
  on:click={handleClick}
  disabled={disabled}
  aria-disabled={disabled}
>
  {label}
</button>

<style lang="css">
  @import './SendButton.css';
</style>
