// libs/sveltekit/src/components/SearchInputWithFilterOptions/SearchInputWithFilterOptions.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let searchTerm: string = '';
  export let filters: string[] = [];
  export let disabled: boolean = false;

  const dispatch = createEventDispatcher();

  function handleSearchInput(event: Event) {
    if (!disabled) {
      searchTerm = (event.target as HTMLInputElement).value;
      dispatch('search', searchTerm);
    }
  }

  function handleFilterClick(filter: string) {
    if (!disabled) {
      dispatch('filter', filter);
    }
  }

  function handleKeyDown(event: KeyboardEvent, filter: string) {
    if (!disabled && event.key === 'Enter') {
      handleFilterClick(filter);
    }
  }
</script>

<div class="search-input-with-filters">
  <input
    type="text"
    bind:value={searchTerm}
    on:input={handleSearchInput}
    placeholder="Search..."
    disabled={disabled}
    aria-disabled={disabled}
  />

  <div class="filters" role="list">
    {#each filters as filter}
      <div
        class="filter"
        role="listitem"
        tabIndex={disabled ? -1 : 0}
        on:click={() => handleFilterClick(filter)}
        on:keydown={(event) => handleKeyDown(event, filter)}
        aria-disabled={disabled}
      >
        {filter}
      </div>
    {/each}
  </div>
</div>

<style lang="css">
  @import './SearchInputWithFilterOptions.css';
</style>

// libs/react-deprecated/src/components/SearchInputWithFilterOptions/SearchInputWithFilterOptions.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './SearchInputWithFilterOptions.css';

const SearchInputWithFilterOptions = ({ filters, onSearch, disabled }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [activeFilters, setActiveFilters] = useState([]);

  const handleSearchChange = (e) => {
    setSearchTerm(e.target.value);
    onSearch(e.target.value, activeFilters);
  };

  const toggleFilter = (filter) => {
    const newFilters = activeFilters.includes(filter)
      ? activeFilters.filter((f) => f !== filter)
      : [...activeFilters, filter];
    setActiveFilters(newFilters);
    onSearch(searchTerm, newFilters);
  };

  return (
    <div className={`search-input-with-filters ${disabled ? 'disabled' : ''}`}>
      <input
        type="text"
        value={searchTerm}
        onChange={handleSearchChange}
        placeholder="Search..."
        disabled={disabled}
      />
      <div className="filter-options">
        {filters.map((filter) => (
          <button
            key={filter}
            onClick={() => toggleFilter(filter)}
            className={activeFilters.includes(filter) ? 'active' : ''}
            disabled={disabled}
          >
            {filter}
          </button>
        ))}
      </div>
    </div>
  );
};

SearchInputWithFilterOptions.propTypes = {
  filters: PropTypes.arrayOf(PropTypes.string),
  onSearch: PropTypes.func,
  disabled: PropTypes.bool,
};

SearchInputWithFilterOptions.defaultProps = {
  filters: [],
  onSearch: () => {},
  disabled: false,
};

export default SearchInputWithFilterOptions;
