// svelte/components/LoadingBarsWithSteps/LoadingBarsWithSteps.svelte
<script lang="ts">
  export type Step = {
    label: string;
    status: 'active' | 'completed' | 'inactive';
  };

  export let steps: Step[] = [];
  export let ariaLabel: string = 'Loading Bars with Steps';
</script>

<div class="loading-bars-with-steps" role="progressbar" aria-label={ariaLabel}>
  {#each steps as { label, status }}
    <div class={`step ${status}`}>
      <div class="step-label">{label}</div>
      <div class="loading-bar"></div>
    </div>
  {/each}
</div>

<style lang="css">
  @import './LoadingBarsWithSteps.css';
</style>

// libs/react/src/components/LoadingBarsWithSteps/LoadingBarsWithSteps.tsx
import React from 'react';

interface Step {
  id: number;
  label: string;
  status: 'Active' | 'Completed' | 'Inactive';
}

interface LoadingBarsWithStepsProps {
  steps: Step[];
}

const LoadingBarsWithSteps: React.FC<LoadingBarsWithStepsProps> = ({ steps }) => {
  return (
    <div className="loading-bars" aria-label="Loading steps">
      {steps.map((step) => (
        <div key={step.id} className={`loading-step ${step.status.toLowerCase()}`}>
          <span className="step-label">{step.label}</span>
          <div className="step-bar">
            <div className={`bar-fill ${step.status.toLowerCase()}`} />
          </div>
        </div>
      ))}
    </div>
  );
};

export default LoadingBarsWithSteps;
