// libs/react-deprecated/src/components/FileInputWithPreview/FileInputWithPreview.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './FileInputWithPreview.css';

const FileInputWithPreview = ({ onFileChange, disabled, error }) => {
  const [filePreview, setFilePreview] = useState(null);

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file && !disabled) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setFilePreview(reader.result);
        onFileChange(file);
      };
      reader.readAsDataURL(file);
    }
  };

  return (
    <div className={`file-input-with-preview ${disabled ? 'disabled' : ''}`}>
      <input
        type="file"
        onChange={handleFileChange}
        disabled={disabled}
      />
      {filePreview && <img src={filePreview} alt="Preview" className="preview" />}
      {error && <div className="error">{error}</div>}
    </div>
  );
};

FileInputWithPreview.propTypes = {
  onFileChange: PropTypes.func,
  disabled: PropTypes.bool,
  error: PropTypes.string,
};

FileInputWithPreview.defaultProps = {
  onFileChange: () => {},
  disabled: false,
  error: '',
};

export default FileInputWithPreview;

// libs/vue/src/components/FileInputWithPreview/FileInputWithPreview.vue
<template>
  <div class="file-input-container">
    <input
      type="file"
      :disabled="disabled"
      @change="handleFileChange"
      :aria-disabled="disabled"
    />
    <div v-if="error" class="error-message">{{ error }}</div>
    <div v-if="previewUrl" class="preview">
      <img :src="previewUrl" alt="File preview" />
    </div>
  </div>
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue';

export default defineComponent({
  name: 'FileInputWithPreview',
  props: {
    disabled: {
      type: Boolean,
      default: false,
    },
    error: {
      type: String,
      default: '',
    },
  },
  emits: ['fileUploaded'],
  setup(_, { emit }) {
    const previewUrl = ref<string | null>(null);

    const handleFileChange = (event: Event) => {
      const target = event.target as HTMLInputElement;
      const file = target.files ? target.files[0] : null;
      if (file && !_.disabled) {
        const reader = new FileReader();
        reader.onload = (e) => {
          previewUrl.value = e.target?.result as string;
          emit('fileUploaded', file);
        };
        reader.readAsDataURL(file);
      }
    };

    return {
      previewUrl,
      handleFileChange,
    };
  },
});
</script>

<style lang="css">
@import './FileInputWithPreview.css';
</style>
