// app/src/components/InteractiveMediaMap/InteractiveMediaMap.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './InteractiveMediaMap.css';

const InteractiveMediaMap = ({ markers }) => {
  const [zoomedIn, setZoomedIn] = useState(false);
  const [selectedMarker, setSelectedMarker] = useState(null);
  const [loading, setLoading] = useState(true);

  const handleZoomToggle = () => {
    setZoomedIn(!zoomedIn);
  };

  const handleMarkerSelect = (marker) => {
    setSelectedMarker(marker);
  };

  const handleMapLoad = () => {
    setLoading(false);
  };

  return (
    <div className={`interactive-map ${zoomedIn ? 'zoomed-in' : ''}`}>
      {loading && <div className="loading-spinner">Loading...</div>}
      {!loading && (
        <div className="map-container" onLoad={handleMapLoad}>
          {markers.map((marker, index) => (
            <div
              key={index}
              className={`map-marker ${selectedMarker === marker ? 'selected' : ''}`}
              onClick={() => handleMarkerSelect(marker)}
            >
              {marker.name}
            </div>
          ))}
        </div>
      )}
      <button className="zoom-button" onClick={handleZoomToggle}>
        {zoomedIn ? 'Zoom Out' : 'Zoom In'}
      </button>
    </div>
  );
};

InteractiveMediaMap.propTypes = {
  markers: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string.isRequired,
      position: PropTypes.object.isRequired,
    })
  ).isRequired,
};

export default InteractiveMediaMap;

// libs/vue/src/components/InteractiveMediaMap/InteractiveMediaMap.vue
<template>
  <div class="interactive-media-map" :class="stateClass" role="region" aria-label="Interactive Media Map">
    <div v-if="state === 'Loading'" class="loading">Loading...</div>
    <div v-else class="map-container">
      <div class="map" @click="handleMapClick">
        <div
          v-for="(marker, index) in markers"
          :key="index"
          class="marker"
          :style="{ left: marker.x + '%', top: marker.y + '%' }"
          @click.stop="selectMarker(index)"
          :aria-label="`Marker ${index + 1}`"
        ></div>
      </div>
      <div v-if="selectedMarker !== null" class="marker-info">
        Marker {{ selectedMarker + 1 }} Selected
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

export default defineComponent({
  name: 'InteractiveMediaMap',
  props: {
    state: {
      type: String,
      default: 'Default',
    },
    markers: {
      type: Array as () => Array<{ x: number; y: number }>,
      default: () => [],
    },
  },
  setup(props) {
    const selectedMarker = ref<number | null>(null);

    const stateClass = computed(() => {
      switch (props.state) {
        case 'Zoomed In':
          return 'zoomed-in';
        case 'Marker Selected':
          return 'marker-selected';
        case 'Loading':
          return 'loading';
        default:
          return 'default';
      }
    });

    const handleMapClick = () => {
      selectedMarker.value = null;
    };

    const selectMarker = (index: number) => {
      selectedMarker.value = index;
    };

    return { selectedMarker, stateClass, handleMapClick, selectMarker };
  },
});
</script>

<style lang="css">
@import './InteractiveMediaMap.css';
</style>
