// libs/sveltekit/src/components/GroupChatName/GroupChatName.svelte
<script lang="ts">
  export let name: string = '';
  export let state: 'displayed' | 'hidden' | 'edited' = 'displayed';
</script>

<div class="group-chat-name {state}" role="heading" aria-label="Group chat name">
  {#if state !== 'hidden'}
    <span>{name}</span>
  {/if}
</div>

<style lang="css">
  @import './GroupChatName.css';
</style>

// app/src/components/GroupChatName/GroupChatName.jsx
// GroupChatName.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './GroupChatName.css';

const GroupChatName = ({ name, isVisible, isEdited }) => {
  return (
    <div className={`group-chat-name ${isVisible ? 'displayed' : 'hidden'} ${isEdited ? 'edited' : ''}`}>
      {isVisible && <span>{name}</span>}
    </div>
  );
};

GroupChatName.propTypes = {
  name: PropTypes.string.isRequired,
  isVisible: PropTypes.bool.isRequired,
  isEdited: PropTypes.bool,
};

GroupChatName.defaultProps = {
  isEdited: false,
};

export default GroupChatName;
