// libs/sveltekit/src/components/Accordion/Accordion.svelte
<script lang="ts">
  export let isOpen: boolean = false;
  export let title: string = 'Accordion Title';
  export let content: string = 'Accordion content goes here.';

  const toggle = () => {
    isOpen = !isOpen;
  };
</script>

<div class="accordion">
  <button 
    class="accordion-header" 
    on:click={toggle} 
    aria-expanded={isOpen} 
    aria-controls="accordion-content"
  >
    {title}
  </button>
  {#if isOpen}
    <div id="accordion-content" class="accordion-content" tabindex="0">
      {content}
    </div>
  {/if}
</div>

<style lang="css">
  @import './Accordion.css';
</style>

// libs/vue/src/components/Accordion/Accordion.vue
<template>
  <div class="accordion">
    <button
      class="accordion-header"
      @click="toggle"
      @mouseenter="hover = true"
      @mouseleave="hover = false"
      :aria-expanded="isOpen"
    >
      <span>{{ title }}</span>
      <span v-if="hover" aria-hidden="true">&#9660;</span>
      <span v-else aria-hidden="true">{{ isOpen ? '▲' : '▼' }}</span>
    </button>
    <div v-if="isOpen" class="accordion-content" role="region">
      <slot />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'Accordion',
  props: {
    title: {
      type: String,
      required: true,
    },
    open: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const isOpen = ref(props.open);
    const hover = ref(false);

    const toggle = () => {
      isOpen.value = !isOpen.value;
    };

    return { isOpen, toggle, hover };
  },
});
</script>

<style lang="css">
@import './Accordion.css';
</style>
