// libs/sveltekit/src/components/ThreadReplyIndicator/ThreadReplyIndicator.svelte
<script lang="ts">
  export let isVisible: boolean = true;
  export let isClicked: boolean = false;

  function handleClick() {
    isClicked = !isClicked;
  }

  function handleKeyDown(event: KeyboardEvent) {
    if (event.key === 'Enter' || event.key === ' ') {
      handleClick();
    }
  }
</script>

<div
  class="reply-indicator"
  role="button"
  tabindex="0"
  aria-pressed={isClicked}
  aria-hidden={!isVisible}
  on:click={handleClick}
  on:keydown={handleKeyDown}
>
  ↩ Reply
</div>

<style lang="css">
  @import './ThreadReplyIndicator.css';
</style>

// libs/react/src/components/ThreadReplyIndicator/ThreadReplyIndicator.tsx
import React, { useState } from 'react';

interface ThreadReplyIndicatorProps {
  visible: boolean;
}

const ThreadReplyIndicator: React.FC<ThreadReplyIndicatorProps> = ({ visible }) => {
  const [isClicked, setIsClicked] = useState(false);

  const handleClick = () => {
    setIsClicked(!isClicked);
  };

  return (
    <div
      className={`thread-reply-indicator ${visible ? 'visible' : 'hidden'} ${isClicked ? 'clicked' : ''}`}
      onClick={handleClick}
      aria-hidden={!visible}
      role="button"
    >
      <span>Reply</span>
    </div>
  );
};

export default ThreadReplyIndicator;
