// libs/sveltekit/src/components/SearchInputWithFilterOptions/SearchInputWithFilterOptions.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  export let placeholder: string = 'Search...';
  export let query: string = '';
  export let filtersActive: boolean = false;
  export let disabled: boolean = false;
  export let noResults: boolean = false;

  const dispatch = createEventDispatcher();

  function handleInput(event: Event) {
    const target = event.target as HTMLInputElement;
    query = target.value;
    dispatch('input', { query });
  }

  function handleFilterClick() {
    if (!disabled) {
      filtersActive = !filtersActive;
      dispatch('filterToggle', { filtersActive });
    }
  }
</script>

<div class="search-input-container" aria-disabled={disabled}>
  <input
    type="text"
    bind:value={query}
    placeholder={placeholder}
    on:input={handleInput}
    disabled={disabled}
    aria-label="Search input"
  />
  <button
    on:click={handleFilterClick}
    aria-pressed={filtersActive}
    disabled={disabled}
    aria-label="Toggle filters"
  >
    Filters
  </button>
  {#if noResults}
    <p class="no-results-message">No results found</p>
  {/if}
</div>

<style lang="css">
  @import './SearchInputWithFilterOptions.css';
</style>

// libs/vue/src/components/SearchInputWithFilterOptions/SearchInputWithFilterOptions.vue


<template>
  <div class="search-container">
    <input 
      type="text" 
      :placeholder="placeholder" 
      :disabled="disabled"
      aria-label="Search input"
      v-model="query"
      @input="onInput"
    />
    <button 
      :aria-pressed="filtersActive" 
      @click="toggleFilters"
    >
      Filters
    </button>
    <div v-if="filtersActive" class="filter-options">
      <slot name="filters"></slot>
    </div>
    <div v-if="noResults" class="no-results">
      No Results Found
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'SearchInputWithFilterOptions',
  props: {
    placeholder: {
      type: String,
      default: 'Search...',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    filtersActive: {
      type: Boolean,
      default: false,
    },
    noResults: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['update:filtersActive', 'input'],
  setup(props, { emit }) {
    const query = ref('');

    const onInput = () => {
      emit('input', query.value);
    };

    const toggleFilters = () => {
      emit('update:filtersActive', !props.filtersActive);
    };

    return {
      query,
      onInput,
      toggleFilters,
    };
  },
});
</script>




<style scoped lang="css">
@import './SearchInputWithFilterOptions.css';
</style>
