// app/src/components/MessageBubble/MessageBubble.jsx
// MessageBubble.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './MessageBubble.css';

const MessageBubble = ({ message, state }) => {
  return (
    <div className={`message-bubble ${state}`}>
      {message}
    </div>
  );
};

MessageBubble.propTypes = {
  message: PropTypes.string.isRequired,
  state: PropTypes.oneOf(['sent', 'received', 'read', 'unread']).isRequired,
};

export default MessageBubble;

// libs/sveltekit/src/components/MessageBubble/MessageBubble.svelte
<script lang="ts">
  export let message: string = 'Hello!';
  export let status: 'sent' | 'received' | 'read' | 'unread' = 'unread';
</script>

<div class={`message-bubble message-bubble--${status}`} role="status">
  <p>{message}</p>
</div>

<style lang="css">
  @import './MessageBubble.css';
</style>
