// libs/react/src/components/ThreadPinnedMessage/ThreadPinnedMessage.tsx
import React from 'react';

interface ThreadPinnedMessageProps {
  state: 'pinned' | 'unpinned' | 'visible' | 'hidden';
  message: string;
}

const ThreadPinnedMessage: React.FC<ThreadPinnedMessageProps> = ({ state, message }) => {
  return (
    <div
      className={`thread-pinned-message ${state}`}
      aria-hidden={state === 'hidden'}
      role="status"
    >
      <p>{message}</p>
    </div>
  );
};

export default ThreadPinnedMessage;

// libs/sveltekit/src/components/ThreadPinnedMessage/ThreadPinnedMessage.svelte
<script lang="ts">
  export type PinnedState = 'pinned' | 'unpinned' | 'visible' | 'hidden';
  export let state: PinnedState = 'unpinned';

  function getMessage() {
    switch (state) {
      case 'pinned':
        return '📌 Pinned Message';
      case 'visible':
        return '👁️ Visible Message';
      case 'hidden':
        return '🙈 Hidden Message';
      default:
        return '📎 Unpinned Message';
    }
  }
</script>

<div class="pinned-message" aria-label={`Message is ${state}`}>
  {getMessage()}
</div>

<style lang="css">
  @import './ThreadPinnedMessage.css';
</style>
