// libs/react/src/components/ValidationMessages/ValidationMessages.tsx
import React from 'react';

interface ValidationMessagesProps {
  type: 'success' | 'error' | 'warning';
  message: string;
}

const ValidationMessages: React.FC<ValidationMessagesProps> = ({ type, message }) => {
  return (
    <div className={`validation-message ${type}`} role="alert" aria-live="assertive">
      {message}
    </div>
  );
};

export default ValidationMessages;

// libs/vue/src/components/ValidationMessages/ValidationMessages.vue
<template>
  <div class="validation-message" :class="type" role="alert" :aria-live="type === 'error' ? 'assertive' : 'polite'">
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'ValidationMessages',
  props: {
    type: {
      type: String as PropType<'success' | 'error' | 'warning'>,
      required: true,
    },
  },
});
</script>

<style lang="css">
@import './ValidationMessages.css';
</style>
