// app/src/components/ValidationMessages/ValidationMessages.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './ValidationMessages.css';

const ValidationMessages = ({ message, type }) => {
  return (
    <div className={`validation-message ${type}`}>
      {message}
    </div>
  );
};

ValidationMessages.propTypes = {
  message: PropTypes.string.isRequired,
  type: PropTypes.oneOf(['success', 'error', 'warning']),
};

ValidationMessages.defaultProps = {
  type: 'success',
};

export default ValidationMessages;

// libs/vue/src/components/ValidationMessages/ValidationMessages.vue
<template>
  <div class="validation-message" :class="type" role="alert" :aria-live="type === 'error' ? 'assertive' : 'polite'">
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'ValidationMessages',
  props: {
    type: {
      type: String as PropType<'success' | 'error' | 'warning'>,
      required: true,
    },
  },
});
</script>

<style lang="css">
@import './ValidationMessages.css';
</style>
