// libs/sveltekit/src/components/PasswordConfirmationField/PasswordConfirmationField.svelte
<script lang="ts">
  export let password: string = '';
  export let confirmPassword: string = '';
  export let disabled: boolean = false;

  $: isMatching = password === confirmPassword;
</script>

<div class="password-confirmation-field">
  <input 
    type="password" 
    bind:value={password} 
    placeholder="Enter password" 
    {disabled} 
    aria-label="Password" 
  />
  <input 
    type="password" 
    bind:value={confirmPassword} 
    placeholder="Confirm password" 
    {disabled} 
    aria-label="Confirm password" 
    aria-describedby="password-match-status"
  />
  <span id="password-match-status" class:isMatching={isMatching}>
    {isMatching ? 'Passwords match' : 'Passwords do not match'}
  </span>
</div>

<style lang="css">
  .password-confirmation-field {
    display: flex;
    flex-direction: column;
  }

  .password-confirmation-field input[type="password"] {
    padding: 5px;
    border: 1px solid #ccc;
    margin-bottom: 5px;
    font-size: 16px;
  }

  .password-confirmation-field span {
    font-size: 14px;
    color: red;
  }

  .password-confirmation-field span.isMatching {
    color: green;
  }
</style>

// app/src/components/PasswordConfirmationField/PasswordConfirmationField.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
`;

const Input = styled.input`
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  margin-bottom: 10px;
  box-sizing: border-box;
  &:focus {
    border-color: #888;
    outline: none;
  }
  &[disabled] {
    background-color: #f2f2f2;
    cursor: not-allowed;
  }
`;

const Message = styled.div`
  color: ${(props) => (props.match ? 'green' : 'red')};
  font-size: 0.9em;
`;

const PasswordConfirmationField = ({ password, onPasswordChange, confirmPassword, onConfirmPasswordChange, disabled }) => {
  const isMatch = password === confirmPassword;

  return (
    <Wrapper>
      <Input
        type="password"
        value={password}
        onChange={(e) => onPasswordChange(e.target.value)}
        placeholder="Password"
        disabled={disabled}
      />
      <Input
        type="password"
        value={confirmPassword}
        onChange={(e) => onConfirmPasswordChange(e.target.value)}
        placeholder="Confirm Password"
        disabled={disabled}
      />
      <Message match={isMatch}>
        {isMatch ? 'Passwords match' : 'Passwords do not match'}
      </Message>
    </Wrapper>
  );
};

PasswordConfirmationField.propTypes = {
  password: PropTypes.string.isRequired,
  onPasswordChange: PropTypes.func.isRequired,
  confirmPassword: PropTypes.string.isRequired,
  onConfirmPasswordChange: PropTypes.func.isRequired,
  disabled: PropTypes.bool,
};

PasswordConfirmationField.defaultProps = {
  disabled: false,
};

export default PasswordConfirmationField;
