// libs/sveltekit/src/components/PodcastPlayer/PodcastPlayer.svelte
<script lang="ts">
  export let isPlaying: boolean = false;
  export let isPaused: boolean = true;
  export let isEpisodeListVisible: boolean = false;
  export let isDownloading: boolean = false;
  export let episodes: string[] = [];
  export let currentEpisodeIndex: number = 0;

  function togglePlayPause() {
    isPlaying = !isPlaying;
    isPaused = !isPaused;
  }

  function toggleEpisodeList() {
    isEpisodeListVisible = !isEpisodeListVisible;
  }

  function downloadEpisode() {
    isDownloading = true;
    setTimeout(() => {
      isDownloading = false;
    }, 3000);
  }

  function selectEpisode(index: number) {
    currentEpisodeIndex = index;
    isPlaying = true;
    isPaused = false;
  }
</script>

<div class="podcast-player" role="region" aria-label="Podcast Player">
  <div class="player-controls">
    <button on:click={togglePlayPause} aria-pressed={isPlaying}>
      {isPlaying ? 'Pause' : 'Play'}
    </button>
    <button on:click={toggleEpisodeList} aria-expanded={isEpisodeListVisible}>
      {isEpisodeListVisible ? 'Hide Episodes' : 'Show Episodes'}
    </button>
    <button on:click={downloadEpisode} disabled={isDownloading}>
      {isDownloading ? 'Downloading...' : 'Download'}
    </button>
  </div>
  {#if isEpisodeListVisible}
    <ul class="episode-list">
      {#each episodes as episode, index}
        <li>
          <button on:click={() => selectEpisode(index)} class={index === currentEpisodeIndex ? 'active' : ''}>
            {episode}
          </button>
        </li>
      {/each}
    </ul>
  {/if}
</div>

<style lang="css">
  @import './PodcastPlayer.css';
</style>

// libs/react/src/components/PodcastPlayer/PodcastPlayer.tsx
import React, { useState } from 'react';

interface PodcastPlayerProps {
  episodes: string[];
  initialEpisodeIndex?: number;
}

const PodcastPlayer: React.FC<PodcastPlayerProps> = ({ episodes, initialEpisodeIndex = 0 }) => {
  const [currentEpisodeIndex, setCurrentEpisodeIndex] = useState(initialEpisodeIndex);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const togglePlayPause = () => {
    setIsPlaying(!isPlaying);
  };

  const handleDownload = () => {
    setIsDownloading(true);
    setTimeout(() => setIsDownloading(false), 2000);
  };

  const selectEpisode = (index: number) => {
    setCurrentEpisodeIndex(index);
    setIsPlaying(false);
  };

  return (
    <div className="podcast-player">
      <div className="episode-info">
        <h2>Episode {currentEpisodeIndex + 1}</h2>
        <p>{episodes[currentEpisodeIndex]}</p>
      </div>
      <div className="controls">
        <button onClick={togglePlayPause} aria-label={isPlaying ? 'Pause' : 'Play'}>
          {isPlaying ? 'Pause' : 'Play'}
        </button>
        <button onClick={handleDownload} disabled={isDownloading} aria-label="Download Episode">
          {isDownloading ? 'Downloading...' : 'Download'}
        </button>
      </div>
      <div className="episode-list">
        {episodes.map((episode, index) => (
          <button key={index} onClick={() => selectEpisode(index)} aria-label={`Select Episode ${index + 1}`}>
            Episode {index + 1}
          </button>
        ))}
      </div>
    </div>
  );
};

export default PodcastPlayer;
