// app/src/components/RichTextEditor/RichTextEditor.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './RichTextEditor.css';

const RichTextEditor = ({ content, onChange, readOnly }) => {
  const [editorContent, setEditorContent] = useState(content);

  const handleInputChange = (e) => {
    const newContent = e.target.innerHTML;
    setEditorContent(newContent);
    onChange(newContent);
  };

  return (
    <div
      className={`rich-text-editor ${readOnly ? 'read-only' : ''}`}
      contentEditable={!readOnly}
      suppressContentEditableWarning={true}
      onInput={handleInputChange}
      dangerouslySetInnerHTML={{ __html: editorContent }}
    />
  );
};

RichTextEditor.propTypes = {
  content: PropTypes.string,
  onChange: PropTypes.func,
  readOnly: PropTypes.bool,
};

RichTextEditor.defaultProps = {
  content: '',
  onChange: () => {},
  readOnly: false,
};

export default RichTextEditor;

// libs/sveltekit/src/components/RichTextEditor/RichTextEditor.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  export let content: string = '';
  export let readOnly: boolean = false;
  let editor: HTMLDivElement;

  onMount(() => {
    if (!readOnly) {
      editor.contentEditable = "true";
    }
  });

  function handleInput(event: InputEvent) {
    const target = event.target as HTMLDivElement;
    content = target.innerHTML;
  }
</script>

<div
  bind:this={editor}
  class="rich-text-editor"
  on:input={handleInput}
  role="textbox"
  aria-multiline="true"
  aria-readonly={readOnly}
  tabindex="0"
>
  {@html content}
</div>

<style lang="css">
  @import './RichTextEditor.css';
</style>
