// libs/react/src/components/LoadingSpinner/LoadingSpinner.tsx
import React from 'react';

interface LoadingSpinnerProps {
  active: boolean;
}

const LoadingSpinner: React.FC<LoadingSpinnerProps> = ({ active }) => {
  return (
    <div
      role="status"
      aria-live="polite"
      className={`loading-spinner ${active ? 'active' : 'inactive'}`}
    >
      {active && (
        <svg
          className="spinner"
          viewBox="0 0 50 50"
          aria-hidden="true"
          focusable="false"
        >
          <circle
            className="path"
            cx="25"
            cy="25"
            r="20"
            fill="none"
            strokeWidth="5"
          />
        </svg>
      )}
    </div>
  );
};

export default LoadingSpinner;

// libs/sveltekit/src/components/LoadingSpinner/LoadingSpinner.svelte
<script lang="ts">
  export let active: boolean = false;
</script>

<div class="loading-spinner" role="status" aria-live={active ? 'polite' : 'off'} aria-hidden={!active}>
  {#if active}
    <div class="spinner" aria-label="Loading"></div>
  {/if}
</div>

<style lang="css">
  @import './LoadingSpinner.css';
</style>
