// libs/vue/src/components/LoadingSpinner/LoadingSpinner.vue

<template>
  <div v-if="active" class="spinner" role="status" aria-live="polite" aria-label="Loading">
    <span class="visually-hidden">Loading...</span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'LoadingSpinner',
  props: {
    active: {
      type: Boolean,
      required: true,
    },
  },
});
</script>




<style scoped lang="css">
@import './LoadingSpinner.css';
</style>

// libs/sveltekit/src/components/LoadingSpinner/LoadingSpinner.svelte
<script lang="ts">
  export let active: boolean = false;
</script>

<div class="loading-spinner" role="status" aria-live={active ? 'polite' : 'off'} aria-hidden={!active}>
  {#if active}
    <div class="spinner" aria-label="Loading"></div>
  {/if}
</div>

<style lang="css">
  @import './LoadingSpinner.css';
</style>
