// libs/sveltekit/src/components/AudioPlayerAdvanced/AudioPlayerAdvanced.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let src: string;
  export let isPlaying: boolean = false;
  export let isMuted: boolean = false;
  export let volume: number = 1;
  export let playbackRate: number = 1;

  let audio: HTMLAudioElement;
  let currentTime: number = 0;

  function togglePlay() {
    isPlaying = !isPlaying;
    if (isPlaying) {
      audio.play();
    } else {
      audio.pause();
    }
  }

  function toggleMute() {
    isMuted = !isMuted;
    audio.muted = isMuted;
  }

  function handleVolumeChange(event: Event) {
    const target = event.target as HTMLInputElement;
    volume = parseFloat(target.value);
    audio.volume = volume;
  }

  function handleSpeedChange(event: Event) {
    const target = event.target as HTMLInputElement;
    playbackRate = parseFloat(target.value);
    audio.playbackRate = playbackRate;
  }

  function handleSeek(event: Event) {
    const target = event.target as HTMLInputElement;
    currentTime = parseFloat(target.value);
    audio.currentTime = currentTime;
  }

  function updateCurrentTime() {
    currentTime = audio.currentTime;
  }

  onMount(() => {
    audio.volume = volume;
    audio.muted = isMuted;
    audio.playbackRate = playbackRate;
    audio.addEventListener('timeupdate', updateCurrentTime);
  });
</script>

<div class="audio-player-advanced">
  <audio bind:this={audio} src={src} />

  <button on:click={togglePlay} aria-label="Play/Pause">
    {isPlaying ? 'Pause' : 'Play'}
  </button>

  <button on:click={toggleMute} aria-label="Mute/Unmute">
    {isMuted ? 'Unmute' : 'Mute'}
  </button>
  
  <input type="range" min="0" max="1" step="0.01" value={volume} on:input={handleVolumeChange} aria-label="Volume Control" />
  
  <input type="range" min="0.5" max="2" step="0.1" value={playbackRate} on:input={handleSpeedChange} aria-label="Speed Control" />
  
  <input type="range" min="0" max={audio?.duration || 0} step="0.1" value={currentTime} on:input={handleSeek} aria-label="Seek Control" />
</div>

<style lang="css">
  @import './AudioPlayerAdvanced.css';
</style>

// app/src/components/AudioPlayerAdvanced/AudioPlayerAdvanced.jsx
import React, { useState, useRef } from 'react';
import PropTypes from 'prop-types';
import './AudioPlayerAdvanced.css';

const AudioPlayerAdvanced = ({ src, autoPlay }) => {
  const audioRef = useRef(null);
  const [isPlaying, setIsPlaying] = useState(autoPlay);
  const [isMuted, setIsMuted] = useState(false);
  const [volume, setVolume] = useState(1);
  const [speed, setSpeed] = useState(1);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);

  const togglePlayPause = () => {
    if (audioRef.current) {
      if (isPlaying) {
        audioRef.current.pause();
      } else {
        audioRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  const toggleMute = () => {
    if (audioRef.current) {
      audioRef.current.muted = !isMuted;
      setIsMuted(!isMuted);
    }
  };

  const changeVolume = (event) => {
    const newVolume = event.target.value;
    if (audioRef.current) {
      audioRef.current.volume = newVolume;
      setVolume(newVolume);
    }
  };

  const changeSpeed = (event) => {
    const newSpeed = event.target.value;
    if (audioRef.current) {
      audioRef.current.playbackRate = newSpeed;
      setSpeed(newSpeed);
    }
  };

  const handleTimeUpdate = () => {
    if (audioRef.current) {
      setCurrentTime(audioRef.current.currentTime);
    }
  };

  const handleLoadedMetadata = () => {
    if (audioRef.current) {
      setDuration(audioRef.current.duration);
    }
  };

  const seekAudio = (event) => {
    const newTime = event.target.value;
    if (audioRef.current) {
      audioRef.current.currentTime = newTime;
      setCurrentTime(newTime);
    }
  };

  return (
    <div className="audio-player-advanced-container">
      <audio
        ref={audioRef}
        src={src}
        autoPlay={autoPlay}
        onTimeUpdate={handleTimeUpdate}
        onLoadedMetadata={handleLoadedMetadata}
      />
      <div className="controls">
        <button onClick={togglePlayPause}>{isPlaying ? 'Pause' : 'Play'}</button>
        <button onClick={toggleMute}>{isMuted ? 'Unmute' : 'Mute'}</button>
        <input
          type="range"
          min="0"
          max={duration}
          step="0.1"
          value={currentTime}
          onChange={seekAudio}
        />
        <input
          type="range"
          min="0"
          max="1"
          step="0.01"
          value={volume}
          onChange={changeVolume}
        />
        <select value={speed} onChange={changeSpeed}>
          <option value="0.5">0.5x</option>
          <option value="1">1x</option>
          <option value="1.5">1.5x</option>
          <option value="2">2x</option>
        </select>
      </div>
    </div>
  );
};

AudioPlayerAdvanced.propTypes = {
  src: PropTypes.string.isRequired,
  autoPlay: PropTypes.bool,
};

AudioPlayerAdvanced.defaultProps = {
  autoPlay: false,
};

export default AudioPlayerAdvanced;
