// libs/vue/src/components/CardbasedList/CardbasedList.vue
<template>
  <div class="cardbased-list" role="list">
    <div
      v-for="(card, index) in cards"
      :key="index"
      class="card"
      :class="{ hovered: hoveredIndex === index, selected: selectedIndex === index, disabled: card.disabled }"
      @mouseenter="hoveredIndex = index"
      @mouseleave="hoveredIndex = null"
      @click="selectCard(index)"
      :aria-disabled="card.disabled ? 'true' : 'false'"
    >
      <div class="card-content">
        <h3>{{ card.title }}</h3>
        <p>{{ card.description }}</p>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

interface Card {
  title: string;
  description: string;
  disabled?: boolean;
}

export default defineComponent({
  name: 'CardbasedList',
  props: {
    cards: {
      type: Array as () => Card[],
      required: true,
    },
  },
  setup() {
    const hoveredIndex = ref<number | null>(null);
    const selectedIndex = ref<number | null>(null);

    const selectCard = (index: number) => {
      if (!cards[index].disabled) {
        selectedIndex.value = index;
      }
    };

    return { hoveredIndex, selectedIndex, selectCard };
  },
});
</script>

<style scoped lang="css">
.cardbased-list {
  display: flex;
  flex-wrap: wrap;
  gap: var(--card-gap, 10px);
}

.card {
  background-color: var(--card-bg, #fff);
  border: var(--card-border, 1px solid #ddd);
  padding: var(--card-padding, 15px);
  transition: transform 0.3s ease, background-color 0.3s ease;
  cursor: pointer;
}

.card.hovered {
  background-color: var(--card-hover-bg, #f0f0f0);
}

.card.selected {
  border-color: var(--card-selected-border-color, #007bff);
}

.card.disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.card-content h3 {
  margin: 0;
  font-size: var(--card-title-font-size, 16px);
}

.card-content p {
  margin: 5px 0 0;
  font-size: var(--card-description-font-size, 14px);
}
</style>

// app/src/components/Cardbasedlist/Cardbasedlist.jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const CardContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
`;

const Card = styled.div`
  background-color: ${({ selected }) => (selected ? '#e0f7fa' : '#fff')};
  border: 1px solid #ccc;
  border-radius: 8px;
  padding: 20px;
  width: calc(33.3333% - 16px);
  box-sizing: border-box;
  cursor: ${({ disabled }) => (disabled ? 'not-allowed' : 'pointer')};
  opacity: ${({ disabled }) => (disabled ? 0.5 : 1)};
  &:hover {
    background-color: ${({ disabled }) => (disabled ? '#fff' : '#f0f0f0')};
  }
`;

const CardContent = styled.div`
  margin-bottom: 10px;
`;

const CardBasedList = ({ cards, onSelect, selectedCard, disabled }) => (
  <CardContainer>
    {cards.map((card, index) => (
      <Card
        key={index}
        onClick={() => !disabled && onSelect(card)}
        selected={selectedCard === card}
        disabled={disabled}
      >
        <CardContent>{card.content}</CardContent>
      </Card>
    ))}
  </CardContainer>
);

CardBasedList.propTypes = {
  cards: PropTypes.arrayOf(
    PropTypes.shape({
      content: PropTypes.string.isRequired,
    })
  ).isRequired,
  onSelect: PropTypes.func.isRequired,
  selectedCard: PropTypes.object,
  disabled: PropTypes.bool,
};

CardBasedList.defaultProps = {
  selectedCard: null,
  disabled: false,
};

export default CardBasedList;
