// app/src/components/Tooltip/Tooltip.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './Tooltip.css';

const Tooltip = ({ isVisible, content, type, children }) => {
  return (
    <div className="tooltip-container">
      {children}
      {isVisible && <div className={`tooltip-content ${type}`}>{content}</div>}
    </div>
  );
};

Tooltip.propTypes = {
  isVisible: PropTypes.bool,
  content: PropTypes.node.isRequired,
  type: PropTypes.oneOf(['default', 'error', 'information']),
  children: PropTypes.node.isRequired,
};

Tooltip.defaultProps = {
  isVisible: false,
  type: 'default',
};

export default Tooltip;

// libs/sveltekit/src/components/Tooltip/Tooltip.svelte
<script lang="ts">
  export let isVisible: boolean = false;
  export let content: string = 'This is a tooltip.';
  export let type: 'default' | 'error' | 'information' = 'default';

  const toggleTooltip = () => {
    isVisible = !isVisible;
  };
</script>

<div class="tooltip-container" role="tooltip" aria-hidden={!isVisible}>
  <button on:click={toggleTooltip} on:keydown={(e) => e.key === 'Enter' && toggleTooltip()} aria-expanded={isVisible}>
    Toggle Tooltip
  </button>
  {#if isVisible}
    <div class={`tooltip tooltip--${type}`}>
      <p>{content}</p>
    </div>
  {/if}
</div>

<style lang="css">
  @import './Tooltip.css';
</style>
