// libs/vue/src/components/Tooltip/Tooltip.vue
<template>
  <div class="tooltip-container" @mouseover="showTooltip" @mouseleave="hideTooltip">
    <slot name="trigger"></slot>
    <div v-if="isVisible" :class="['tooltip-content', type]" role="tooltip">
      <slot name="content"></slot>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

export default defineComponent({
  name: 'Tooltip',
  props: {
    visible: {
      type: Boolean,
      default: false,
    },
    type: {
      type: String,
      default: 'information',
      validator: (value: string) => ['information', 'error'].includes(value),
    },
  },
  setup(props) {
    const isVisible = ref(props.visible);

    const showTooltip = () => {
      isVisible.value = true;
    };

    const hideTooltip = () => {
      isVisible.value = false;
    };

    return {
      isVisible,
      showTooltip,
      hideTooltip,
    };
  },
});
</script>

<style lang="css">
@import './Tooltip.css';
</style>

// libs/sveltekit/src/components/Tooltip/Tooltip.svelte
<script lang="ts">
  export let isVisible: boolean = false;
  export let content: string = 'This is a tooltip.';
  export let type: 'default' | 'error' | 'information' = 'default';

  const toggleTooltip = () => {
    isVisible = !isVisible;
  };
</script>

<div class="tooltip-container" role="tooltip" aria-hidden={!isVisible}>
  <button on:click={toggleTooltip} on:keydown={(e) => e.key === 'Enter' && toggleTooltip()} aria-expanded={isVisible}>
    Toggle Tooltip
  </button>
  {#if isVisible}
    <div class={`tooltip tooltip--${type}`}>
      <p>{content}</p>
    </div>
  {/if}
</div>

<style lang="css">
  @import './Tooltip.css';
</style>
