// libs/sveltekit/src/components/ScrollableHorizontalNavigation/ScrollableHorizontalNavigation.svelte
<script lang="ts">
  export let items: { label: string; action: () => void }[] = [];
  export let activeIndex: number | null = null;

  const activateItem = (index: number) => {
    activeIndex = index;
    items[index].action();
  };
</script>

<div class="scrollable-horizontal-navigation" role="navigation">
  <div class="nav-container">
    <ul class="nav-items" role="menubar">
      {#each items as item, index}
        <li class={`nav-item ${activeIndex === index ? 'active' : ''}`} role="menuitem">
          <button class="item-link" on:click={() => activateItem(index)}>{item.label}</button>
        </li>
      {/each}
    </ul>
  </div>
</div>

<style lang="css">
  @import './ScrollableHorizontalNavigation.css';
</style>

// libs/react/src/components/ScrollableHorizontalNavigation/ScrollableHorizontalNavigation.tsx
import React, { useState } from 'react';

interface NavItem {
  label: string;
  onClick: () => void;
}

interface ScrollableHorizontalNavigationProps {
  items: NavItem[];
}

const ScrollableHorizontalNavigation: React.FC<ScrollableHorizontalNavigationProps> = ({ items }) => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  return (
    <nav className="scrollable-horizontal-navigation" aria-label="Scrollable Horizontal Navigation">
      <ul className="nav-items">
        {items.map((item, index) => (
          <li
            key={index}
            className={`nav-item ${activeIndex === index ? 'active' : ''}`}
            onMouseEnter={() => setActiveIndex(index)}
            onMouseLeave={() => setActiveIndex(null)}
          >
            <button onClick={item.onClick}>{item.label}</button>
          </li>
        ))}
      </ul>
    </nav>
  );
};

export default ScrollableHorizontalNavigation;
