// libs/sveltekit/src/components/Popover/Popover.svelte
<script lang="ts">
  export let isVisible: boolean = false;
  export let content: string = 'This is a popover content.';

  const togglePopover = () => {
    isVisible = !isVisible;
  };
</script>

<div class="popover-container" role="dialog" aria-hidden={!isVisible}>
  <button on:click={togglePopover} on:keydown={(e) => e.key === 'Enter' && togglePopover()} aria-expanded={isVisible}>
    Toggle Popover
  </button>
  {#if isVisible}
    <div class="popover">
      <p>{content}</p>
    </div>
  {/if}
</div>

<style lang="css">
  @import './Popover.css';
</style>

// libs/vue/src/components/Popover/Popover.vue
<template>
  <div class="popover-container" @click="toggleVisibility" role="button" aria-expanded="isVisible">
    <slot name="trigger"></slot>
    <div v-if="isVisible" class="popover-content" role="dialog" aria-hidden="false">
      <slot name="content"></slot>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'Popover',
  props: {
    visible: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const isVisible = ref(props.visible);

    const toggleVisibility = () => {
      isVisible.value = !isVisible.value;
    };

    return {
      isVisible,
      toggleVisibility,
    };
  },
});
</script>

<style lang="css">
@import './Popover.css';
</style>
