// libs/sveltekit/src/components/Upload/Upload.svelte
<script lang="ts">
  export type UploadState = 'uploading' | 'downloading' | 'completed' | 'paused' | 'failed';
  export let state: UploadState = 'uploading';
  export let fileName: string = '';
  export let progress: number = 0;

  function handlePause() {
    if (state === 'uploading') {
      state = 'paused';
    }
  }

  function handleResume() {
    if (state === 'paused') {
      state = 'uploading';
    }
  }
</script>

<div class={`upload upload-${state}`} role="status">
  <span>{fileName}</span>
  {#if state !== 'completed'}
    <div class="progress-bar">
      <div class="progress" style={`width: ${progress}%`}></div>
    </div>
  {/if}
  {#if state === 'paused'}
    <button on:click={handleResume} aria-label="Resume Upload">Resume</button>
  {:else if state === 'uploading'}
    <button on:click={handlePause} aria-label="Pause Upload">Pause</button>
  {/if}
</div>

<style lang="css">
  @import './Upload.css';
</style>

// libs/vue/src/components/Upload/Upload.vue
<template>
  <div class="upload" :class="status">
    <div class="status-indicator" role="status" aria-live="polite">
      <p>{{ statusMessage }}</p>
    </div>
    <button @click="togglePause" v-if="status === 'uploading' || status === 'paused'">
      {{ status === 'paused' ? 'Resume' : 'Pause' }}
    </button>
    <button @click="retry" v-if="status === 'failed'">Retry</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, PropType } from 'vue';

export default defineComponent({
  name: 'Upload',
  props: {
    status: {
      type: String as PropType<'uploading' | 'downloading' | 'completed' | 'paused' | 'failed'>,
      required: true,
    },
  },
  setup(props) {
    const statusMessage = computed(() => {
      switch (props.status) {
        case 'uploading':
          return 'Uploading...';
        case 'downloading':
          return 'Downloading...';
        case 'completed':
          return 'Completed';
        case 'paused':
          return 'Paused';
        case 'failed':
          return 'Failed';
        default:
          return '';
      }
    });

    const togglePause = () => {
      if (props.status === 'uploading') {
        props.status = 'paused';
      } else if (props.status === 'paused') {
        props.status = 'uploading';
      }
    };

    const retry = () => {
      if (props.status === 'failed') {
        props.status = 'uploading';
      }
    };

    return { statusMessage, togglePause, retry };
  },
});
</script>

<style lang="css">
@import './Upload.css';
</style>
