// libs/vue/src/components/SelectableListWithItemDetails/SelectableListWithItemDetails.vue

<template>
  <div class="selectable-list">
    <ul class="selectable-list-items">
      <li
        v-for="item in items"
        :key="item.id"
        :class="['selectable-list-item', { selected: item.id === selectedItem, disabled: disabled }]"
        @click="toggleSelection(item.id)"
      >
        <div class="item-content">
          {{ item.label }}
          <button @click.stop="toggleDetails(item.id)" class="details-button" :aria-expanded="item.id === openDetails ? 'true' : 'false'">
            {{ item.id === openDetails ? 'Hide Details' : 'Show Details' }}
          </button>
        </div>
        <div v-if="item.id === openDetails" class="item-details">
          {{ item.details }}
        </div>
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

interface ListItem {
  id: number;
  label: string;
  details: string;
}

export default defineComponent({
  name: 'SelectableListWithItemDetails',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const selectedItem = ref<number | null>(null);
    const openDetails = ref<number | null>(null);

    const toggleSelection = (id: number) => {
      if (!props.disabled) {
        selectedItem.value = selectedItem.value === id ? null : id;
      }
    };

    const toggleDetails = (id: number) => {
      openDetails.value = openDetails.value === id ? null : id;
    };

    return { selectedItem, openDetails, toggleSelection, toggleDetails };
  },
});
</script>




<style scoped lang="css">
@import './SelectableListWithItemDetails.css';
</style>

// libs/sveltekit/src/components/SelectableListWithItemDetails/SelectableListWithItemDetails.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export type ListItem = {
    id: number;
    text: string;
    details: string;
    selected?: boolean;
  };

  export let items: ListItem[] = [];
  const dispatch = createEventDispatcher();

  function toggleSelection(item: ListItem) {
    if (!item.selected) {
      dispatch('itemSelected', item);
    } else {
      dispatch('itemDeselected', item);
    }
    item.selected = !item.selected;
  }

  function toggleDetails(item: ListItem) {
    item.detailsOpen = !item.detailsOpen;
    dispatch(item.detailsOpen ? 'detailsOpened' : 'detailsClosed', item);
  }
</script>

<div class="selectable-list" role="list">
  {#each items as item (item.id)}
    <div
      class="selectable-list-item"
      class:selected={item.selected}
      role="listitem"
      tabindex="0"
      on:click={() => toggleSelection(item)}
      on:keydown={(e) => e.key === "Enter" && toggleSelection(item)}
      aria-selected={item.selected}
    >
      <div>{item.text}</div>
      <button
        type="button"
        class="details-button"
        on:click={() => toggleDetails(item)}
        on:keydown={(e) => e.key === "Enter" && toggleDetails(item)}
      >
        {item.detailsOpen ? 'Hide Details' : 'Show Details'}
      </button>
      {#if item.detailsOpen}
        <div class="item-details">{item.details}</div>
      {/if}
    </div>
  {/each}
</div>

<style lang="css">
  @import './SelectableListWithItemDetails.css';
</style>
