// libs/sveltekit/src/components/SkeletonSendButton/SkeletonSendButton.svelte
<script lang="ts">
  export type LoadingState = 'loading' | 'hidden';
  export let state: LoadingState = 'loading';
</script>

<div 
  class="skeleton-send-button" 
  aria-hidden={state === 'hidden'} 
  role="status" 
  aria-label="Loading send button"
>
  {#if state === 'loading'}
    <div class="skeleton-button"></div>
  {/if}
</div>

<style lang="css">
  @import './SkeletonSendButton.css';
</style>

// libs/react/src/components/SkeletonSendButton/SkeletonSendButton.tsx
import React from 'react';

interface SkeletonSendButtonProps {
  state: 'loading' | 'hidden';
}

const SkeletonSendButton: React.FC<SkeletonSendButtonProps> = ({ state }) => {
  return (
    <div
      className={`skeleton-send-button ${state}`}
      aria-hidden={state === 'hidden'}
      role="status"
      aria-live={state === 'loading' ? 'polite' : 'off'}
    >
      <div className="skeleton-button"></div>
    </div>
  );
};

export default SkeletonSendButton;
