// libs/vue/src/components/ContextualNavigation/ContextualNavigation.vue

<template>
  <div class="contextual-navigation" :aria-hidden="!isVisible">
    <button @click="toggleMenu" class="contextual-toggle" :aria-expanded="isVisible">
      <span v-if="isVisible">Close Menu</span>
      <span v-else>Open Menu</span>
    </button>
    <div v-if="isVisible" class="contextual-menu" role="menu">
      <ul>
        <li v-for="(item, index) in menuItems" :key="index" role="menuitem">
          <a :href="item.link">{{ item.name }}</a>
        </li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

interface MenuItem {
  name: string;
  link: string;
}

export default defineComponent({
  name: 'ContextualNavigation',
  props: {
    menuItems: {
      type: Array as () => MenuItem[],
      required: true,
    },
  },
  setup() {
    const isVisible = ref(false);
    const toggleMenu = () => {
      isVisible.value = !isVisible.value;
    };

    return {
      isVisible,
      toggleMenu,
    };
  },
});
</script>




<style scoped lang="css">
@import './ContextualNavigation.css';
</style>

// libs/sveltekit/src/components/ContextualNavigation/ContextualNavigation.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let items: { label: string; action: () => void }[] = [];
  export let isVisible: boolean = false;

  const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === 'Enter' || event.key === ' ') {
      toggleVisibility();
    }
  };

  const toggleVisibility = () => {
    isVisible = !isVisible;
  };

  onMount(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (!event.target.closest('.contextual-nav')) {
        isVisible = false;
      }
    };

    document.addEventListener('click', handleClickOutside);
    return () => document.removeEventListener('click', handleClickOutside);
  });
</script>

<div class="contextual-nav" role="navigation">
  <button class="contextual-trigger" aria-haspopup="true" aria-expanded={isVisible} on:click={toggleVisibility} on:keydown={handleKeydown}>
    Toggle Menu
  </button>
  {#if isVisible}
    <ul class="contextual-menu" role="menu">
      {#each items as item}
        <li class="contextual-item" role="menuitem">
          <button class="contextual-link" on:click={item.action}>{item.label}</button>
        </li>
      {/each}
    </ul>
  {/if}
</div>

<style lang="css">
  @import './ContextualNavigation.css';
</style>
