// libs/react/src/components/ThreadTimestamp/ThreadTimestamp.tsx
import React from 'react';

interface ThreadTimestampProps {
  timestamp: string;
  visible: boolean;
}

const ThreadTimestamp: React.FC<ThreadTimestampProps> = ({ timestamp, visible }) => {
  return (
    <span
      className="thread-timestamp"
      aria-hidden={!visible}
    >
      {visible ? timestamp : ''}
    </span>
  );
};

export default ThreadTimestamp;

// libs/sveltekit/src/components/ThreadTimestamp/ThreadTimestamp.svelte
<script lang="ts">
  export let timestamp: string = '';
  export let isVisible: boolean = true;
</script>

<div class="timestamp-container" aria-hidden={!isVisible}>
  {#if isVisible}
    <time class="timestamp" datetime={timestamp}>{timestamp}</time>
  {/if}
</div>

<style lang="css">
  @import './ThreadTimestamp.css';
</style>
