// libs/react/src/components/CardFooter/CardFooter.tsx
import React from 'react';
import './CardFooter.css';

interface CardFooterProps {
  children: React.ReactNode;
  align?: 'left' | 'center' | 'right';
}

const CardFooter: React.FC<CardFooterProps> = ({ children, align = 'left' }) => {
  return (
    <div className={`card-footer align-${align}`}>
      {children}
    </div>
  );
};

export default CardFooter;

// libs/vue/src/components/CardFooter/CardFooter.vue

<template>
  <footer class="card-footer" :style="{ justifyContent: alignment }">
    <slot></slot>
  </footer>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'CardFooter',
  props: {
    alignment: {
      type: String as () => 'flex-start' | 'center' | 'flex-end',
      default: 'flex-start',
    },
  },
});
</script>




<style scoped lang="css">
@import './CardFooter.css';
</style>
