// libs/react/src/components/EmbeddedMediaIframe/EmbeddedMediaIframe.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './EmbeddedMediaIframe.css';

const EmbeddedMediaIframe = ({ src, title, allowFullScreen, isBuffering }) => {
  return (
    <div className={`iframe-container ${isBuffering ? 'buffering' : ''}`}>
      <iframe
        src={src}
        title={title}
        allowFullScreen={allowFullScreen}
        className="embedded-media-iframe"
        frameBorder="0"
      />
      {isBuffering && <div className="buffering-overlay">Buffering...</div>}
    </div>
  );
};

EmbeddedMediaIframe.propTypes = {
  src: PropTypes.string.isRequired,
  title: PropTypes.string.isRequired,
  allowFullScreen: PropTypes.bool,
  isBuffering: PropTypes.bool,
};

EmbeddedMediaIframe.defaultProps = {
  allowFullScreen: true,
  isBuffering: false,
};

export default EmbeddedMediaIframe;

// libs/sveltekit/src/components/EmbeddedMediaIframe/EmbeddedMediaIframe.svelte
<script lang="ts">
  export let src: string = '';
  export let title: string = 'Embedded Media';
  export let isFullscreen: boolean = false;
  export let isBuffering: boolean = false;

  function toggleFullscreen() {
    isFullscreen = !isFullscreen;
  }
</script>

<div class="media-container" class:fullscreen={isFullscreen}>
  {#if isBuffering}
    <div class="buffering" role="alert" aria-live="assertive">Buffering...</div>
  {/if}
  <iframe
    src={src}
    title={title}
    frameborder="0"
    allowfullscreen
    class:fullscreen={isFullscreen}
    aria-label={title}
  ></iframe>
  <button on:click={toggleFullscreen} aria-label="Toggle Fullscreen">
    {isFullscreen ? 'Exit Fullscreen' : 'Enter Fullscreen'}
  </button>
</div>

<style lang="css">
  @import './EmbeddedMediaIframe.css';
</style>
