// libs/sveltekit/src/components/SortableTable/SortableTable.svelte
<script lang="ts">
  import { writable } from 'svelte/store';

  export type TableColumn = {
    key: string;
    label: string;
    sortable?: boolean;
  };

  export type TableRow = {
    [key: string]: string | number | boolean;
  };

  export let columns: TableColumn[] = [];
  export let rows: TableRow[] = [];

  const selectedRow = writable<TableRow | null>(null);
  let filterText = '';
  let sortKey = '';
  let sortOrder: 'asc' | 'desc' = 'asc';

  function sortRows(key: string) {
    if (sortKey === key) {
      sortOrder = sortOrder === 'asc' ? 'desc' : 'asc';
    } else {
      sortKey = key;
      sortOrder = 'asc';
    }
    rows = [...rows].sort((a, b) => {
      if (a[key] < b[key]) return sortOrder === 'asc' ? -1 : 1;
      if (a[key] > b[key]) return sortOrder === 'asc' ? 1 : -1;
      return 0;
    });
  }

  function filterRows() {
    return rows.filter(row =>
      Object.values(row).some(value =>
        String(value).toLowerCase().includes(filterText.toLowerCase())
      )
    );
  }

  function selectRow(row: TableRow) {
    selectedRow.set(row);
  }
</script>

<div class="filter">
  <input
    type="text"
    placeholder="Filter..."
    bind:value={filterText}
    on:input={() => filterRows()}
    aria-label="Filter rows"
  />
</div>
<table class="sortable-table" role="table">
  <thead>
    <tr>
      {#each columns as column}
        <th
          on:click={() => column.sortable && sortRows(column.key)}
          on:keydown={(e) => e.key === "Enter" && column.sortable && sortRows(column.key)}
          tabindex="0"
          aria-sort={sortKey === column.key ? sortOrder : 'none'}
          role="columnheader"
          class:sortable={column.sortable}
        >
          {column.label} {#if column.sortable && sortKey === column.key}{sortOrder === 'asc' ? '↑' : '↓'}{/if}
        </th>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each filterRows() as row (row.id)}
      <tr
        on:click={() => selectRow(row)}
        on:keydown={(e) => e.key === "Enter" && selectRow(row)}
        role="row"
        tabindex="0"
      >
        {#each columns as column}
          <td role="cell">{row[column.key]}</td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>

<style lang="css">
  @import './SortableTable.css';
</style>

// libs/vue/src/components/SortableTable/SortableTable.vue

<template>
  <div class="sortable-table">
    <input 
      type="text" 
      v-model="filterText" 
      class="filter-input" 
      placeholder="Filter table..."
      aria-label="Filter table"
    />
    <table>
      <thead>
        <tr>
          <th v-for="column in columns" :key="column.key" @click="sortBy(column.key)">
            {{ column.label }}
            <span :class="getSortDirection(column.key)"></span>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr 
          v-for="row in filteredAndSortedData" 
          :key="row.id" 
          :class="{ selected: row.id === selectedRow }" 
          @click="selectRow(row.id)"
        >
          <td v-for="column in columns" :key="column.key">{{ row[column.key] }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

interface TableColumn {
  key: string;
  label: string;
}

interface TableRow {
  id: number;
  [key: string]: any;
}

export default defineComponent({
  name: 'SortableTable',
  props: {
    columns: {
      type: Array as () => TableColumn[],
      required: true,
    },
    data: {
      type: Array as () => TableRow[],
      required: true,
    },
  },
  setup(props) {
    const sortKey = ref<string | null>(null);
    const sortDirection = ref<1 | -1 | number>(1);
    const filterText = ref<string>("");
    const selectedRow = ref<number | null>(null);

    const sortBy = (key: string) => {
      if (sortKey.value === key) {
        sortDirection.value = -sortDirection.value;
      } else {
        sortKey.value = key;
        sortDirection.value = 1;
      }
    };

    const selectRow = (id: number) => {
      selectedRow.value = selectedRow.value === id ? null : id;
    };

    const getSortDirection = (key: string) => {
      if (sortKey.value === key) {
        return sortDirection.value === 1 ? 'asc' : 'desc';
      }
      return '';
    };

    const filteredAndSortedData = computed(() => {
      let filteredData = props.data.filter(row => 
        Object.values(row).some(val => val.toString().toLowerCase().includes(filterText.value.toLowerCase()))
      );

      if (sortKey.value) {
        filteredData.sort((a, b) => {
          const aValue = a[sortKey.value!];
          const bValue = b[sortKey.value!];
          if (aValue < bValue) return -1 * sortDirection.value;
          if (aValue > bValue) return 1 * sortDirection.value;
          return 0;
        });
      }

      return filteredData;
    });

    return { sortBy, selectRow, getSortDirection, filteredAndSortedData, filterText, selectedRow };
  },
});
</script>




<style scoped lang="css">
@import './SortableTable.css';
</style>
