// libs/react/src/components/UserAvatar/UserAvatar.tsx
import React from 'react';

interface UserAvatarProps {
  status: 'online' | 'offline' | 'active' | 'away' | 'busy';
  src: string;
  alt: string;
}

const UserAvatar: React.FC<UserAvatarProps> = ({ status, src, alt }) => {
  return (
    <div className={`user-avatar ${status}`} aria-label={`User status: ${status}`}>
      <img src={src} alt={alt} className="avatar-image" />
      <span className={`status-indicator ${status}`} />
    </div>
  );
};

export default UserAvatar;

// libs/vue/src/components/UserAvatar/UserAvatar.vue
<template>
  <div class="avatar" :class="status" role="img" aria-label="User Avatar">
    <img :src="imageSrc" :alt="altText" />
    <span class="status-indicator" :aria-label="status"></span>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'UserAvatar',
  props: {
    imageSrc: {
      type: String,
      required: true,
    },
    altText: {
      type: String,
      default: 'User Avatar',
    },
    status: {
      type: String as PropType<'online' | 'offline' | 'active' | 'away' | 'busy'>,
      default: 'offline',
      validator: (value: string) => ['online', 'offline', 'active', 'away', 'busy'].includes(value),
    },
  },
});
</script>

<style lang="css">
@import './UserAvatar.css';
</style>
