// libs/vue/src/components/UndoRedoButtons/UndoRedoButtons.vue


<template>
  <div class="undo-redo-buttons">
    <button :disabled="!canUndo" @click="undo" aria-label="Undo" :class="{ active: canUndo }">Undo</button>
    <button :disabled="!canRedo" @click="redo" aria-label="Redo" :class="{ active: canRedo }">Redo</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'UndoRedoButtons',
  setup() {
    const canUndo = ref(false);
    const canRedo = ref(false);

    const undo = () => {
      if (canUndo.value) {
        // Perform undo action
        canRedo.value = true;
        canUndo.value = false; // Update based on actual action history
      }
    };

    const redo = () => {
      if (canRedo.value) {
        // Perform redo action
        canUndo.value = true;
        canRedo.value = false; // Update based on actual action history
      }
    };

    return {
      canUndo,
      canRedo,
      undo,
      redo,
    };
  },
});
</script>




<style scoped lang="css">
@import './UndoRedoButtons.css';
</style>

// libs/react/src/components/UndoRedoButtons/UndoRedoButtons.tsx
import React from 'react';
import './UndoRedoButtons.css';

interface UndoRedoButtonsProps {
  canUndo: boolean;
  canRedo: boolean;
  onUndo: () => void;
  onRedo: () => void;
}

const UndoRedoButtons: React.FC<UndoRedoButtonsProps> = ({ canUndo, canRedo, onUndo, onRedo }) => {
  return (
    <div className="undo-redo-buttons">
      <button 
        onClick={onUndo} 
        disabled={!canUndo} 
        aria-label="Undo" 
        className={`undo-button ${canUndo ? 'enabled' : 'disabled'}`}
      >
        Undo
      </button>
      <button 
        onClick={onRedo} 
        disabled={!canRedo} 
        aria-label="Redo" 
        className={`redo-button ${canRedo ? 'enabled' : 'disabled'}`}
      >
        Redo
      </button>
    </div>
  );
};

export default UndoRedoButtons;
