// libs/react/src/components/YesNoPoll/YesNoPoll.tsx
import React, { useState } from 'react';
import './YesNoPoll.css';

interface YesNoPollProps {
  question: string;
  disabled: boolean;
  showResults: boolean;
  onVote: (vote: 'yes' | 'no') => void;
}

const YesNoPoll: React.FC<YesNoPollProps> = ({ question, disabled, showResults, onVote }) => {
  const [vote, setVote] = useState<'yes' | 'no' | null>(null);

  const handleVoteClick = (selectedVote: 'yes' | 'no') => {
    if (!disabled) {
      setVote(selectedVote);
      onVote(selectedVote);
    }
  };

  return (
    <div className="yesno-poll">
      <h2 className="poll-question">{question}</h2>
      <div className="vote-container" role="radiogroup" aria-disabled={disabled}>
        <button 
          className={`vote-button ${vote === 'yes' ? 'selected' : ''} ${disabled ? 'disabled' : ''}`} 
          role="radio" 
          aria-checked={vote === 'yes'}
          onClick={() => handleVoteClick('yes')}
        >
          Yes
        </button>
        <button 
          className={`vote-button ${vote === 'no' ? 'selected' : ''} ${disabled ? 'disabled' : ''}`} 
          role="radio" 
          aria-checked={vote === 'no'}
          onClick={() => handleVoteClick('no')}
        >
          No
        </button>
      </div>
      {showResults && vote && <div className="results">You voted: {vote === 'yes' ? 'Yes' : 'No'}</div>}
    </div>
  );
};

export default YesNoPoll;

// libs/vue/src/components/YesNoPoll/YesNoPoll.vue


<template>
  <div class="yes-no-poll" role="radiogroup" aria-labelledby="poll-question">
    <p id="poll-question">{{ question }}</p>
    <div class="options">
      <button
        :aria-checked="selectedOption === 'yes'"
        :disabled="isDisabled"
        @click="selectOption('yes')"
        class="option"
        :class="{ selected: selectedOption === 'yes' }"
        role="radio"
      >
        Yes
      </button>
      <button
        :aria-checked="selectedOption === 'no'"
        :disabled="isDisabled"
        @click="selectOption('no')"
        class="option"
        :class="{ selected: selectedOption === 'no' }"
        role="radio"
      >
        No
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'YesNoPoll',
  props: {
    question: {
      type: String,
      required: true,
    },
    initialSelection: {
      type: String as () => 'yes' | 'no' | null,
      default: null,
    },
    isDisabled: {
      type: Boolean,
      default: false,
    },
    showResults: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const selectedOption = ref(props.initialSelection);

    const selectOption = (option: 'yes' | 'no') => {
      if (!props.isDisabled) {
        selectedOption.value = option;
      }
    };

    return {
      selectedOption,
      selectOption,
    };
  },
});
</script>




<style scoped lang="css">
@import './YesNoPoll.css';
</style>
