// libs/vue/src/components/UnreadMessageCounter/UnreadMessageCounter.vue
<template>
  <div class="unread-message-counter" v-if="count > 0" aria-label="Unread messages">
    {{ count }}
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'UnreadMessageCounter',
  props: {
    count: {
      type: Number,
      required: true,
      validator: (value: number) => value >= 0,
    },
  },
});
</script>

<style lang="css">
@import './UnreadMessageCounter.css';
</style>

// app/src/components/UnreadMessageCounter/UnreadMessageCounter.jsx
// UnreadMessageCounter.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './UnreadMessageCounter.css';

const UnreadMessageCounter = ({ count }) => {
  return (
    <div className={`unread-message-counter ${count > 0 ? 'displayed' : 'hidden'}`}>
      {count > 0 && <span>{count}</span>}
    </div>
  );
};

UnreadMessageCounter.propTypes = {
  count: PropTypes.number.isRequired,
};

export default UnreadMessageCounter;
