// libs/sveltekit/src/components/ChatList/ChatList.svelte
<script lang="ts">
  export type Chat = { id: number; name: string; lastMessage: string; isSelected: boolean };
  export let chats: Chat[] = [];
  export let onSelect: (id: number) => void = () => {};
  
  const handleKeyPress = (event: KeyboardEvent, id: number) => {
    if (event.key === 'Enter' || event.key === ' ') {
      onSelect(id);
    }
  };
</script>

<div class="chat-list" role="list">
  {#if chats.length > 0}
    {#each chats as { id, name, lastMessage, isSelected }}
      <div 
        class="chat-item {isSelected ? 'selected' : ''}" 
        role="listitem" 
        tabindex="0"
        aria-selected={isSelected}
        on:click={() => onSelect(id)}
        on:keydown={(event) => handleKeyPress(event, id)}
      >
        <div class="chat-name">{name}</div>
        <div class="chat-message">{lastMessage}</div>
      </div>
    {/each}
  {:else}
    <div class="empty-message" role="listitem">No chats available</div>
  {/if}
</div>

<style lang="css">
  @import './ChatList.css';
</style>

// libs/react/src/components/ChatList/ChatList.tsx
import React from 'react';

interface Chat {
  id: number;
  name: string;
  lastMessage: string;
  selected?: boolean;
}

interface ChatListProps {
  chats: Chat[];
  onSelect: (id: number) => void;
}

const ChatList: React.FC<ChatListProps> = ({ chats, onSelect }) => {
  return (
    <ul className="chat-list">
      {chats.length === 0 ? (
        <li className="chat-list-empty">No chats available</li>
      ) : (
        chats.map(chat => (
          <li
            key={chat.id}
            className={`chat-item ${chat.selected ? 'selected' : ''}`}
            onClick={() => onSelect(chat.id)}
            role="button"
            tabIndex={0}
            aria-selected={chat.selected}
          >
            <div className="chat-name">{chat.name}</div>
            <div className="chat-last-message">{chat.lastMessage}</div>
          </li>
        ))
      )}
    </ul>
  );
};

export default ChatList;
