// libs/react/src/components/Sticky/Sticky.tsx
import React, { useState, useEffect } from 'react';

interface StickyProps {
  content: React.ReactNode;
}

const Sticky: React.FC<StickyProps> = ({ content }) => {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isExpanded, setIsExpanded] = useState(true);

  const handleScroll = () => {
    setIsScrolled(window.scrollY > 0);
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const toggleExpand = () => {
    setIsExpanded(!isExpanded);
  };

  return (
    <header
      className={`sticky-header ${isScrolled ? 'scrolled' : ''} ${isExpanded ? 'expanded' : 'collapsed'}`}
      aria-expanded={isExpanded}
    >
      <button onClick={toggleExpand} className="toggle-button" aria-label="Toggle Sticky">
        {isExpanded ? 'Collapse' : 'Expand'}
      </button>
      <div className="sticky-content">
        {content}
      </div>
    </header>
  );
};

export default Sticky;

// libs/vue/src/components/Sticky/Sticky.vue
<template>
  <div class="sticky-container" :class="{ scrolled: isScrolled }" role="complementary">
    <div class="sticky-header" @click="toggleExpand" :aria-expanded="isExpanded">
      <slot name="header">Sticky Header</slot>
    </div>
    <div v-show="isExpanded" class="sticky-content">
      <slot name="content">Sticky Content</slot>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from 'vue';

export default defineComponent({
  name: 'Sticky',
  setup() {
    const isScrolled = ref(false);
    const isExpanded = ref(true);

    const handleScroll = () => {
      isScrolled.value = window.scrollY > 50;
    };

    const toggleExpand = () => {
      isExpanded.value = !isExpanded.value;
    };

    onMounted(() => {
      window.addEventListener('scroll', handleScroll);
    });

    return {
      isScrolled,
      isExpanded,
      toggleExpand,
    };
  },
});
</script>

<style lang="css">
@import './Sticky.css';
</style>
