// app/src/components/Sticky/Sticky.jsx
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import './Sticky.css';

const Sticky = ({ content }) => {
  const [isSticky, setSticky] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const handleScroll = () => {
    if (window.scrollY > 50) {
      setSticky(true);
    } else {
      setSticky(false);
    }
  };

  const toggleExpand = () => {
    setExpanded(!expanded);
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <div className={`sticky ${isSticky ? 'scrolled' : ''} ${expanded ? 'expanded' : 'collapsed'}`}>
      <button onClick={toggleExpand} className="expand-button">
        {expanded ? 'Collapse' : 'Expand'}
      </button>
      <div className="sticky-content">{content}</div>
    </div>
  );
};

Sticky.propTypes = {
  content: PropTypes.node.isRequired,
};

export default Sticky;

// libs/vue/src/components/Sticky/Sticky.vue
<template>
  <div class="sticky-container" :class="{ scrolled: isScrolled }" role="complementary">
    <div class="sticky-header" @click="toggleExpand" :aria-expanded="isExpanded">
      <slot name="header">Sticky Header</slot>
    </div>
    <div v-show="isExpanded" class="sticky-content">
      <slot name="content">Sticky Content</slot>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from 'vue';

export default defineComponent({
  name: 'Sticky',
  setup() {
    const isScrolled = ref(false);
    const isExpanded = ref(true);

    const handleScroll = () => {
      isScrolled.value = window.scrollY > 50;
    };

    const toggleExpand = () => {
      isExpanded.value = !isExpanded.value;
    };

    onMounted(() => {
      window.addEventListener('scroll', handleScroll);
    });

    return {
      isScrolled,
      isExpanded,
      toggleExpand,
    };
  },
});
</script>

<style lang="css">
@import './Sticky.css';
</style>
