// libs/sveltekit/src/components/Sticky/Sticky.svelte
<script lang="ts">
  export let expanded: boolean = false;
  export let scrolled: boolean = false;

  const toggleExpanded = () => {
    expanded = !expanded;
  };
</script>

<div class={`sticky ${scrolled ? 'scrolled' : ''} ${expanded ? 'expanded' : 'collapsed'}`} role="navigation">
  <button on:click={toggleExpanded} aria-expanded={expanded}>
    Toggle
  </button>
  <div class="content">
    <slot></slot>
  </div>
</div>

<style lang="css">
  @import './Sticky.css';
</style>

// libs/vue/src/components/Sticky/Sticky.vue
<template>
  <div class="sticky-container" :class="{ scrolled: isScrolled }" role="complementary">
    <div class="sticky-header" @click="toggleExpand" :aria-expanded="isExpanded">
      <slot name="header">Sticky Header</slot>
    </div>
    <div v-show="isExpanded" class="sticky-content">
      <slot name="content">Sticky Content</slot>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from 'vue';

export default defineComponent({
  name: 'Sticky',
  setup() {
    const isScrolled = ref(false);
    const isExpanded = ref(true);

    const handleScroll = () => {
      isScrolled.value = window.scrollY > 50;
    };

    const toggleExpand = () => {
      isExpanded.value = !isExpanded.value;
    };

    onMounted(() => {
      window.addEventListener('scroll', handleScroll);
    });

    return {
      isScrolled,
      isExpanded,
      toggleExpand,
    };
  },
});
</script>

<style lang="css">
@import './Sticky.css';
</style>
