// libs/react/src/components/ReadReceipt/ReadReceipt.tsx
import React from 'react';

interface ReadReceiptProps {
  status: 'seen' | 'unseen' | 'delivered' | 'failed';
}

const ReadReceipt: React.FC<ReadReceiptProps> = ({ status }) => {
  return (
    <div className={`read-receipt ${status}`} role="status" aria-label={`Message status: ${status}`}>
      <span className={`status-icon ${status}`} />
    </div>
  );
};

export default ReadReceipt;

// libs/sveltekit/src/components/ReadReceipt/ReadReceipt.svelte
<script lang="ts">
  export let status: 'seen' | 'unseen' | 'delivered' | 'failed' = 'unseen';

  function getStatusClass() {
    return `status-${status}`;
  }
</script>

<div class="read-receipt {getStatusClass()}" aria-label="{status}">
  <span class="icon"></span>
</div>

<style lang="css">
  @import './ReadReceipt.css';
</style>
