// libs/react-dprecated/src/components/ReadReceipt/ReadReceipt.jsx
// ReadReceipt.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './ReadReceipt.css';

const ReadReceipt = ({ status }) => {
  return <div className={`read-receipt ${status}`} />;
};

ReadReceipt.propTypes = {
  status: PropTypes.oneOf(['seen', 'unseen', 'delivered', 'failed']).isRequired,
};

export default ReadReceipt;

// libs/sveltekit/src/components/ReadReceipt/ReadReceipt.svelte
<script lang="ts">
  export let status: 'seen' | 'unseen' | 'delivered' | 'failed' = 'unseen';

  function getStatusClass() {
    return `status-${status}`;
  }
</script>

<div class="read-receipt {getStatusClass()}" aria-label="{status}">
  <span class="icon"></span>
</div>

<style lang="css">
  @import './ReadReceipt.css';
</style>
