// libs/sveltekit/src/components/Tabs/Tabs.svelte
<script lang="ts">
  export interface Tab {
    id: number;
    title: string;
    disabled?: boolean;
  }

  export let tabs: Tab[] = [];
  export let activeTabId: number;
  export let onTabChange: (activeTab: Tab) => void;

  function activateTab(tab: Tab) {
    if (tab.disabled) return;
    activeTabId = tab.id;
    onTabChange(tab);
  }
</script>

<div role="tablist" aria-label="Sample Tabs">
  {#each tabs as tab (tab.id)}
    <button
      role="tab"
      class="tab-button"
      aria-selected={tab.id === activeTabId}
      aria-disabled={tab.disabled ? 'true' : 'false'}
      on:click={() => activateTab(tab)}
    >
      {tab.title}
    </button>
  {/each}
</div>

<style lang="css">
  @import './Tabs.css';
</style>

// libs/vue/src/components/Tabs/Tabs.vue

<template>
  <div class="tabs" role="tablist">
    <button
      v-for="(tab, index) in tabs"
      :key="tab.id"
      :role="'tab'"
      :aria-selected="activeIndex === index"
      :disabled="tab.disabled"
      :class="{
        active: activeIndex === index,
        disabled: tab.disabled
      }"
      @click="selectTab(index)"
    >
      {{ tab.label }}
    </button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, PropType } from 'vue';

interface Tab {
  id: number;
  label: string;
  disabled?: boolean;
}

export default defineComponent({
  name: 'Tabs',
  props: {
    tabs: {
      type: Array as PropType<Tab[]>,
      required: true,
    },
    initialActiveIndex: {
      type: Number,
      default: 0,
    },
  },
  setup(props) {
    const activeIndex = ref(props.initialActiveIndex);

    const selectTab = (index: number) => {
      if (!props.tabs[index].disabled) {
        activeIndex.value = index;
      }
    };

    return { activeIndex, selectTab };
  },
});
</script>




<style scoped lang="css">
@import './Tabs.css';
</style>
