// libs/vue/src/components/ScrollableList/ScrollableList.vue
<template>
  <div class="scrollable-list" role="region" aria-label="Scrollable List">
    <ul
      class="list"
      role="list"
      @scroll="handleScroll"
      :aria-disabled="disabled"
    >
      <li
        v-for="item in items"
        :key="item.id"
        class="list-item"
        :class="{ hover: hoveredItem === item.id }"
        @mouseover="hoveredItem = item.id"
        @mouseleave="hoveredItem = null"
        role="listitem"
      >
        {{ item.name }}
      </li>
    </ul>
    <p v-if="endOfList" class="end-of-list">End of List</p>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

interface ListItem {
  id: number;
  name: string;
}

export default defineComponent({
  name: 'ScrollableList',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    const hoveredItem = ref<number | null>(null);
    const endOfList = ref<boolean>(false);

    const handleScroll = (event: Event) => {
      const target = event.target as HTMLElement;
      if (target.scrollHeight - target.scrollTop === target.clientHeight) {
        endOfList.value = true;
      } else {
        endOfList.value = false;
      }
    };

    return { hoveredItem, endOfList, handleScroll };
  },
});
</script>

<style lang="css">
@import './ScrollableList.css';
</style>

// libs/sveltekit/src/components/ScrollableList/ScrollableList.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export type ListItem = {
    id: number;
    text: string;
    disabled?: boolean;
  };

  export let items: ListItem[] = [];
  export let disabled: boolean = false;

  const dispatch = createEventDispatcher();

  function handleScroll(event: Event) {
    const target = event.target as HTMLElement;
    if (target.scrollHeight - target.scrollTop === target.clientHeight) {
      dispatch('endOfList');
    }
  }
</script>

<div
  class="scrollable-list"
  on:scroll={handleScroll}
  aria-disabled={disabled}
  tabindex={disabled ? -1 : 0}
>
  {#each items as item (item.id)}
    <div
      class="scrollable-list-item"
      class:hover={!disabled}
      class:disabled={item.disabled}
      role="listitem"
      aria-disabled={item.disabled}
    >
      {item.text}
    </div>
  {/each}
</div>

<style lang="css">
  @import './ScrollableList.css';
</style>
