// libs/sveltekit/src/components/ImageSlider/ImageSlider.svelte
<script lang="ts">
  export let images: string[] = [];
  export let activeIndex: number = 0;

  function nextImage() {
    activeIndex = (activeIndex + 1) % images.length;
  }

  function prevImage() {
    activeIndex = (activeIndex - 1 + images.length) % images.length;
  }
</script>

<div class="slider" role="region" aria-live="polite">
  <button on:click={prevImage} aria-label="Previous Image">Prev</button>
  {#if images.length > 0}
    <img src={images[activeIndex]} alt="Image Slider" class="slide" />
  {/if}
  <button on:click={nextImage} aria-label="Next Image">Next</button>
</div>

<style lang="css">
  @import './ImageSlider.css';
</style>

// libs/react/src/components/ImageSlider/ImageSlider.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './ImageSlider.css';

const ImageSlider = ({ images }) => {
  const [activeIndex, setActiveIndex] = useState(0);

  const handlePrevClick = () => {
    setActiveIndex((prevIndex) => (prevIndex - 1 + images.length) % images.length);
  };

  const handleNextClick = () => {
    setActiveIndex((prevIndex) => (prevIndex + 1) % images.length);
  };

  return (
    <div className="image-slider">
      <button className="slider-button prev" onClick={handlePrevClick}>
        &#10094;
      </button>
      <div className="slider-images">
        {images.map((image, index) => (
          <img
            key={index}
            src={image}
            alt={`Slide ${index}`}
            className={`slider-image ${index === activeIndex ? 'active' : ''}`}
          />
        ))}
      </div>
      <button className="slider-button next" onClick={handleNextClick}>
        &#10095;
      </button>
    </div>
  );
};

ImageSlider.propTypes = {
  images: PropTypes.arrayOf(PropTypes.string).isRequired,
};

export default ImageSlider;
