// libs/vue/src/components/CollapsibleMenuList/CollapsibleMenuList.vue
<template>
  <div class="collapsible-menu-list">
    <button
      class="menu-header"
      @click="toggleMenu"
      :aria-expanded="isExpanded"
      aria-controls="menu-list"
    >
      {{ title }}
    </button>
    <ul
      v-show="isExpanded"
      class="menu-list"
      id="menu-list"
      role="menu"
      aria-hidden="!isExpanded"
    >
      <li
        v-for="(item, index) in items"
        :key="index"
        class="menu-item"
        role="menuitem"
        tabindex="0"
      >
        {{ item }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'CollapsibleMenuList',
  props: {
    title: {
      type: String,
      default: 'Menu',
    },
    items: {
      type: Array as () => string[],
      default: () => [],
    },
    expanded: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const isExpanded = ref(props.expanded);

    const toggleMenu = () => {
      isExpanded.value = !isExpanded.value;
    };

    return {
      isExpanded,
      toggleMenu,
    };
  },
});
</script>

<style lang="css">
@import './CollapsibleMenuList.css';
</style>

// libs/sveltekit/src/components/CollapsibleMenuList/CollapsibleMenuList.svelte
<script lang="ts">
  export type MenuState = 'expanded' | 'collapsed' | 'hover' | 'active';
  export let state: MenuState = 'collapsed';
  export let menuItems: { label: string; active: boolean }[] = [];
  let isExpanded: boolean = state === 'expanded';

  function toggleMenu() {
    isExpanded = !isExpanded;
  }

  function handleKey(event: KeyboardEvent) {
    if (event.key === 'Enter' || event.key === ' ') {
      toggleMenu();
    }
  }
</script>

<div class={`collapsible-menu-list menu-${state}`}>
  <div
    class="menu-header"
    role="button"
    tabindex="0"
    aria-expanded={isExpanded}
    on:click={toggleMenu}
    on:keydown={handleKey}
  >
    Menu
  </div>
  {#if isExpanded}
    <ul>
      {#each menuItems as { label, active }}
        <li class:active={active}>{label}</li>
      {/each}
    </ul>
  {/if}
</div>

<style lang="css">
  @import './CollapsibleMenuList.css';
</style>
