// libs/sveltekit/src/components/SearchBar/SearchBar.svelte
<script lang="ts">
  export type SearchBarState = 'focused' | 'unfocused' | 'disabled';
  export let state: SearchBarState = 'unfocused';
  export let placeholder: string = 'Search...';

  function handleFocus() {
    if (state !== 'disabled') {
      state = 'focused';
    }
  }

  function handleBlur() {
    if (state !== 'disabled') {
      state = 'unfocused';
    }
  }
</script>

<input
  class={`search-bar search-bar-${state}`}
  type="text"
  placeholder={placeholder}
  on:focus={handleFocus}
  on:blur={handleBlur}
  disabled={state === 'disabled'}
  aria-label="Search"
  role="searchbox"
/>

<style lang="css">
  @import './SearchBar.css';
</style>

// libs/vue/src/components/SearchBar/SearchBar.vue

<template>
  <div class="search-bar" :class="{ focused: isFocused, disabled: isDisabled }">
    <input
      type="text"
      :placeholder="placeholder"
      :disabled="isDisabled"
      @focus="handleFocus"
      @blur="handleBlur"
      aria-label="Search"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'SearchBar',
  props: {
    placeholder: {
      type: String,
      default: 'Search...',
    },
    isFocused: {
      type: Boolean,
      default: false,
    },
    isDisabled: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const isFocused = ref(props.isFocused)
    const handleFocus = () => {
      isFocused.value = true;
    };

    const handleBlur = () => {
    isFocused.value = false;
    };

    return { handleFocus, handleBlur };
  },
});
</script>




<style scoped lang="css">
@import './SearchBar.css';
</style>
