// app/src/components/SearchBar/SearchBar.jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const SearchBarContainer = styled.div`
  display: flex;
  align-items: center;
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  transition: border-color 0.3s ease;

  ${({ isFocused }) =>
    isFocused &&
    `
    border-color: #1976d2;
  `}

  ${({ disabled }) =>
    disabled &&
    `
    background-color: #e0e0e0;
    border-color: #bdbdbd;
  `}
`;

const Input = styled.input`
  flex: 1;
  border: none;
  outline: none;
  padding: 0.5rem;
  background: transparent;

  &:disabled {
    background-color: #e0e0e0;
  }
`;

const SearchBar = ({ placeholder, isFocused, disabled }) => {
  return (
    <SearchBarContainer isFocused={isFocused} disabled={disabled}>
      <Input type="text" placeholder={placeholder} disabled={disabled} />
    </SearchBarContainer>
  );
};

SearchBar.propTypes = {
  placeholder: PropTypes.string,
  isFocused: PropTypes.bool,
  disabled: PropTypes.bool,
};

SearchBar.defaultProps = {
  placeholder: 'Search...',
  isFocused: false,
  disabled: false,
};

export default SearchBar;

// libs/vue/src/components/SearchBar/SearchBar.vue
<template>
  <div class="search-bar" :class="{ focused: isFocused, disabled: isDisabled }">
    <input
      type="text"
      :placeholder="placeholder"
      :disabled="isDisabled"
      @focus="handleFocus"
      @blur="handleBlur"
      aria-label="Search"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'SearchBar',
  props: {
    placeholder: {
      type: String,
      default: 'Search...',
    },
    isFocused: {
      type: Boolean,
      default: false,
    },
    isDisabled: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const handleFocus = () => {
      props.isFocused = true;
    };

    const handleBlur = () => {
      props.isFocused = false;
    };

    return { handleFocus, handleBlur };
  },
});
</script>

<style scoped lang="css">
.search-bar {
  display: flex;
  align-items: center;
  padding: var(--search-bar-padding, 8px);
  border: var(--search-bar-border, 1px solid #ccc);
  border-radius: var(--search-bar-border-radius, 4px);
  background-color: var(--search-bar-bg, #fff);
  transition: border-color 0.3s ease;
}

.search-bar input {
  flex: 1;
  border: none;
  outline: none;
  padding: var(--search-bar-input-padding, 8px);
}

.search-bar.focused {
  border-color: var(--search-bar-focused-border-color, #007bff);
}

.search-bar.disabled {
  background-color: var(--search-bar-disabled-bg, #f0f0f0);
}
</style>
