// libs/sveltekit/src/components/DatePicker/DatePicker.svelte
<script lang="ts">
  export let selectedDate: string = '';
  export let startDate: string = '';
  export let endDate: string = '';
  export let showTimePicker: boolean = false;

  function handleDateChange(event: Event, isStartDate = false) {
    const input = event.target as HTMLInputElement;
    if (isStartDate) {
      startDate = input.value;
    } else {
      selectedDate = input.value;
    }
  }

  function handleEndDateChange(event: Event) {
    const input = event.target as HTMLInputElement;
    endDate = input.value;
  }
</script>

<div class="date-picker-container">
  {#if showTimePicker}
    <label for="time-picker" aria-label="Select time">
      <input 
        type="datetime-local" 
        id="time-picker" 
        bind:value={selectedDate} 
        on:input={handleDateChange} 
      />
    </label>
  {:else if startDate && endDate}
    <label for="start-date-picker" aria-label="Select start date">
      <input 
        type="date" 
        id="start-date-picker" 
        bind:value={startDate} 
        on:input={(e) => handleDateChange(e, true)} 
      />
    </label>
    <label for="end-date-picker" aria-label="Select end date">
      <input 
        type="date" 
        id="end-date-picker" 
        bind:value={endDate} 
        on:input={handleEndDateChange} 
      />
    </label>
  {:else}
    <label for="single-date-picker" aria-label="Select date">
      <input 
        type="date" 
        id="single-date-picker" 
        bind:value={selectedDate} 
        on:input={handleDateChange} 
      />
    </label>
  {/if}
</div>

<style lang="css">
  @import './DatePicker.css';
</style>

// libs/vue/src/components/DatePicker/DatePicker.vue

<template>
  <div class="date-picker-container">
    <input 
      type="date" 
      :value="startDate" 
      :disabled="disabled" 
      @input="updateStartDate" 
      aria-label="Start Date"
      :aria-disabled="disabled"
    />
    <input 
      v-if="isDateRange" 
      type="date" 
      :value="endDate" 
      :disabled="disabled" 
      @input="updateEndDate" 
      aria-label="End Date"
      :aria-disabled="disabled"
    />
    <input 
      v-if="isTimePicker" 
      type="time" 
      :value="selectedTime" 
      :disabled="disabled" 
      @input="updateTime" 
      aria-label="Time Picker"
      :aria-disabled="disabled"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'DatePicker',
  props: {
    startDate: {
      type: String,
      default: '',
    },
    endDate: {
      type: String,
      default: '',
    },
    selectedTime: {
      type: String,
      default: '',
    },
    isDateRange: {
      type: Boolean,
      default: false,
    },
    isTimePicker: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  methods: {
    updateStartDate(event: Event) {
      const input = event.target as HTMLInputElement;
      this.$emit('update:startDate', input.value);
    },
    updateEndDate(event: Event) {
      const input = event.target as HTMLInputElement;
      this.$emit('update:endDate', input.value);
    },
    updateTime(event: Event) {
      const input = event.target as HTMLInputElement;
      this.$emit('update:selectedTime', input.value);
    },
  },
});
</script>




<style scoped lang="css">
@import './DatePicker.css';
</style>
