// libs/sveltekit/src/components/Button/Button.svelte
<script lang="ts">
  export let type: 'button' | 'submit' | 'reset' = 'button';
  export let disabled: boolean = false;
  export let variant: 'primary' | 'secondary' = 'primary';
</script>

<button type={type} disabled={disabled} class={`button ${variant}`} aria-disabled={disabled ? 'true' : 'false'}>
  <slot></slot>
</button>

<style lang="css">
  @import './Button.css';
</style>

// app/src/components/Button/Button.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './Button.css';

const Button = ({ children, variant, disabled, onClick }) => {
  return (
    <button
      className={`button ${variant}`}
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </button>
  );
};

Button.propTypes = {
  children: PropTypes.node.isRequired,
  variant: PropTypes.oneOf(['primary', 'secondary']),
  disabled: PropTypes.bool,
  onClick: PropTypes.func,
};

Button.defaultProps = {
  variant: 'primary',
  disabled: false,
  onClick: () => {},
};

export default Button;
