// libs/react/src/components/MessageInputBox/MessageInputBox.tsx
import React, { useState } from 'react';

interface MessageInputBoxProps {
  placeholder?: string;
  onChange?: (value: string) => void;
}

const MessageInputBox: React.FC<MessageInputBoxProps> = ({ placeholder = 'Type a message...', onChange }) => {
  const [value, setValue] = useState('');

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = event.target.value;
    setValue(newValue);
    if (onChange) {
      onChange(newValue);
    }
  };

  return (
    <input
      type="text"
      className={`message-input-box ${value ? 'typing' : 'empty'}`}
      value={value}
      onChange={handleInputChange}
      placeholder={placeholder}
      aria-label="Message input"
    />
  );
};

export default MessageInputBox;

// libs/sveltekit/src/components/MessageInputBox/MessageInputBox.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  export let value: string = '';
  export let placeholder: string = 'Type a message...';
  export let focused: boolean = false;

  let inputElement: HTMLInputElement;

  onMount(() => {
    if (focused && inputElement) {
      inputElement.focus();
    }
  });

  function handleInput(event: Event) {
    const target = event.target as HTMLInputElement;
    value = target.value;
  }
</script>

<input
  type="text"
  bind:value
  placeholder={placeholder}
  class="message-input"
  on:input={handleInput}
  bind:this={inputElement}
/>

<style lang="css">
  @import './MessageInputBox.css';
</style>
