// libs/sveltekit/src/components/InteractivePollResults/InteractivePollResults.svelte
<script lang="ts">
  export let options: { label: string; votes: number }[] = [];
  export let totalVotes: number = 0;
  export let status: 'live' | 'completed' | 'closed' = 'live';

  const calculatePercentage = (votes: number) => {
    return totalVotes ? Math.round((votes / totalVotes) * 100) : 0;
  };
</script>

<div class="poll-results" role="status" aria-live="polite">
  {#each options as { label, votes }}
    <div class="poll-option" tabindex="0" on:click={() => {}} on:keydown={(e) => e.key === 'Enter' && {}}>
      <span class="label">{label}</span>
      <span class="bar" style="width: {calculatePercentage(votes)}%;"></span>
      <span class="percentage">{calculatePercentage(votes)}%</span>
    </div>
  {/each}
  <div class="status">Status: {status}</div>
</div>

<style lang="css">
  @import './InteractivePollResults.css';
</style>

// libs/vue/src/components/InteractivePollResults/InteractivePollResults.vue

<template>
  <div class="poll-results" role="region" aria-live="polite">
    <h2>{{ title }}</h2>
    <ul>
      <li v-for="option in options" :key="option.id" :aria-label="`${option.text}: ${option.percentage}%`">
        <span class="option-text">{{ option.text }}</span>
        <div class="progress-bar" :style="{ '--progress': `${option.percentage}%` }">
          <span class="percentage">{{ option.percentage }}%</span>
        </div>
      </li>
    </ul>
    <div v-if="state === 'completed'" class="poll-status">Poll Completed</div>
    <div v-if="state === 'closed'" class="poll-status">Poll Closed</div>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

interface PollOption {
  id: number;
  text: string;
  percentage: number;
}

export default defineComponent({
  name: 'InteractivePollResults',
  props: {
    title: {
      type: String,
      required: true,
    },
    options: {
      type: Array as PropType<PollOption[]>,
      required: true,
    },
    state: {
      type: String as PropType<'live' | 'completed' | 'closed'>,
      required: true,
    },
  },
});
</script>




<style scoped lang="css">
@import './InteractivePollResults.css';
</style>
