// libs/sveltekit/src/components/NumberInputWithIncrement/NumberInputWithIncrement.svelte
<script lang="ts">
  export let value: number = 0;
  export let step: number = 1;
  export let disabled: boolean = false;

  function increment() {
    if (!disabled) {
      value += step;
    }
  }

  function decrement() {
    if (!disabled) {
      value -= step;
    }
  }
</script>

<div class="number-input">
  <button on:click={decrement} aria-label="Decrement" disabled={disabled}>-</button>
  <input type="number" bind:value {disabled} aria-label="Number input" />
  <button on:click={increment} aria-label="Increment" disabled={disabled}>+</button>
</div>

<style lang="css">
  .number-input {
    display: flex;
    align-items: center;
  }

  .number-input button {
    padding: 5px 10px;
    border: 1px solid #ccc;
    background-color: #f9f9f9;
    cursor: pointer;
    font-size: 16px;
  }

  .number-input button:disabled {
    background-color: #e0e0e0;
    cursor: not-allowed;
  }

  .number-input input[type="number"] {
    width: 60px;
    text-align: center;
    padding: 5px;
    border: 1px solid #ccc;
    margin: 0 5px;
    font-size: 16px;
  }
</style>

// app/src/components/NumberInputWithIncrement/NumberInputWithIncrement.jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const Wrapper = styled.div`
  display: flex;
  align-items: center;
`;

const Input = styled.input`
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  width: 60px;
  text-align: center;
  box-sizing: border-box;
  margin: 0 5px;
  &:focus {
    border-color: #888;
    outline: none;
  }
  &[disabled] {
    background-color: #f2f2f2;
    cursor: not-allowed;
  }
`;

const Button = styled.button`
  padding: 10px;
  border: 1px solid #ccc;
  background-color: #f9f9f9;
  border-radius: 4px;
  cursor: pointer;
  &:disabled {
    background-color: #e0e0e0;
    cursor: not-allowed;
  }
`;

const NumberInputWithIncrement = ({ value, onChange, disabled }) => {
  const handleIncrement = () => {
    onChange(value + 1);
  };

  const handleDecrement = () => {
    onChange(value - 1);
  };

  return (
    <Wrapper>
      <Button onClick={handleDecrement} disabled={disabled}>-</Button>
      <Input type="number" value={value} onChange={(e) => onChange(Number(e.target.value))} disabled={disabled} />
      <Button onClick={handleIncrement} disabled={disabled}>+</Button>
    </Wrapper>
  );
};

NumberInputWithIncrement.propTypes = {
  value: PropTypes.number.isRequired,
  onChange: PropTypes.func.isRequired,
  disabled: PropTypes.bool,
};

NumberInputWithIncrement.defaultProps = {
  disabled: false,
};

export default NumberInputWithIncrement;
