// libs/react/src/components/MediaGallery/MediaGallery.tsx
import React, { useState } from 'react';

interface MediaGalleryProps {
  images: string[];
  initialIndex?: number;
}

const MediaGallery: React.FC<MediaGalleryProps> = ({ images, initialIndex = 0 }) => {
  const [currentIndex, setCurrentIndex] = useState(initialIndex);
  const [isExpanded, setIsExpanded] = useState(false);
  const [isZoomed, setIsZoomed] = useState(false);

  const handleNext = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
  };

  const handlePrevious = () => {
    setCurrentIndex((prevIndex) => (prevIndex - 1 + images.length) % images.length);
  };

  const toggleExpand = () => {
    setIsExpanded(!isExpanded);
  };

  const toggleZoom = () => {
    setIsZoomed(!isZoomed);
  };

  return (
    <div className="media-gallery">
      <div className={`image-container ${isExpanded ? 'expanded' : ''} ${isZoomed ? 'zoomed' : ''}`}>
        <img src={images[currentIndex]} alt={`Image ${currentIndex + 1}`} />
      </div>
      <div className="controls">
        <button onClick={handlePrevious} aria-label="Previous Image">Previous</button>
        <button onClick={toggleExpand} aria-label={isExpanded ? 'Collapse Image' : 'Expand Image'}>
          {isExpanded ? 'Collapse' : 'Expand'}
        </button>
        <button onClick={toggleZoom} aria-label={isZoomed ? 'Zoom Out' : 'Zoom In'}>
          {isZoomed ? 'Zoom Out' : 'Zoom In'}
        </button>
        <button onClick={handleNext} aria-label="Next Image">Next</button>
      </div>
    </div>
  );
};

export default MediaGallery;

// libs/sveltekit/src/components/MediaGallery/MediaGallery.svelte
<script lang="ts">
  export let isThumbnail: boolean = true;
  export let isExpanded: boolean = false;
  export let isSlideshow: boolean = false;
  export let isZoomed: boolean = false;
  export let currentImageIndex: number = 0;
  export let images: string[] = [];

  function toggleExpand() {
    isExpanded = !isExpanded;
  }

  function toggleSlideshow() {
    isSlideshow = !isSlideshow;
  }

  function toggleZoom() {
    isZoomed = !isZoomed;
  }

  function nextImage() {
    currentImageIndex = (currentImageIndex + 1) % images.length;
  }

  function previousImage() {
    currentImageIndex = (currentImageIndex - 1 + images.length) % images.length;
  }
</script>

<div class="gallery-container" role="region" aria-label="Media Gallery">
  <div class="gallery-view" aria-hidden={isSlideshow}>
    {#if isThumbnail}
      <img src={images[currentImageIndex]} alt="thumbnail" class="thumbnail" on:click={toggleExpand} on:keydown={toggleExpand} tabindex="0" />
    {/if}
    {#if isExpanded}
      <img src={images[currentImageIndex]} alt="expanded view" class={isZoomed ? 'zoomed' : ''} on:click={toggleZoom} on:keydown={toggleZoom} tabindex="0" />
    {/if}
  </div>
  {#if isSlideshow}
    <div class="slideshow">
      <button on:click={previousImage} on:keydown={previousImage} tabindex="0">Previous</button>
      <img src={images[currentImageIndex]} alt="slideshow image" />
      <button on:click={nextImage} on:keydown={nextImage} tabindex="0">Next</button>
    </div>
  {/if}
  <div class="controls">
    <button on:click={toggleExpand} aria-pressed={isExpanded}>Toggle Expand</button>
    <button on:click={toggleSlideshow} aria-pressed={isSlideshow}>Toggle Slideshow</button>
    <button on:click={toggleZoom} aria-pressed={isZoomed}>Toggle Zoom</button>
  </div>
</div>

<style lang="css">
  @import './MediaGallery.css';
</style>
