// libs/sveltekit/src/components/BadgeWithCounts/BadgeWithCounts.svelte
<script lang="ts">
  export let count: number = 0;
  export let maxCount: number = 99;

  $: displayCount = count > maxCount ? `${maxCount}+` : count.toString();
</script>

<span class="badge-with-counts" role="status" aria-live="polite">
  {displayCount}
</span>

<style lang="css">
  @import './BadgeWithCounts.css';
</style>

// app/src/32342/BadgeWithCounts/BadgeWithCounts.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './BadgeWithCounts.css';

const BadgeWithCounts = ({ count, maxCount }) => {
  const displayCount = count > maxCount ? `${maxCount}+` : count;

  return (
    <span className="badge-with-counts">
      {displayCount}
    </span>
  );
};

BadgeWithCounts.propTypes = {
  count: PropTypes.number.isRequired,
  maxCount: PropTypes.number,
};

BadgeWithCounts.defaultProps = {
  maxCount: 99,
};

export default BadgeWithCounts;
