// libs/react/src/components/NumberedList/NumberedList.tsx
import React, { useState } from 'react';

interface NumberedListProps {
  items: string[];
  disabled?: boolean;
}

const NumberedList: React.FC<NumberedListProps> = ({ items, disabled = false }) => {
  const [selectedItem, setSelectedItem] = useState<number | null>(null);

  const handleItemClick = (index: number) => {
    if (disabled) return;
    setSelectedItem(index === selectedItem ? null : index);
  };

  return (
    <ol className="numbered-list" aria-disabled={disabled}>
      {items.map((item, index) => (
        <li
          key={index}
          className={`list-item ${selectedItem === index ? 'selected' : ''} ${disabled ? 'disabled' : ''}`}
          onClick={() => handleItemClick(index)}
          aria-selected={selectedItem === index}
        >
          {item}
        </li>
      ))}
    </ol>
  );
};

export default NumberedList;

// libs/sveltekit/src/components/NumberedList/NumberedList.svelte
<script lang="ts">
  export let items: { id: string; label: string; selected: boolean }[] = [];
  export let disabled: boolean = false;

  const handleSelect = (id: string) => {
    if (!disabled) {
      items = items.map(item =>
        item.id === id ? { ...item, selected: !item.selected } : item
      );
    }
  };
</script>

<ol class="numbered-list">
  {#each items as { id, label, selected } (id)}
    <li
      class={`list-item ${selected ? 'selected' : ''}`}
      on:click={() => handleSelect(id)}
      aria-selected={selected}
      aria-disabled={disabled}
      tabindex={disabled ? -1 : 0}
    >
      {label}
    </li>
  {/each}
</ol>

<style lang="css">
  @import './NumberedList.css';
</style>
