// libs/react/src/components/SkeletonMessageBubble/SkeletonMessageBubble.tsx
import React from 'react';

interface SkeletonMessageBubbleProps {
  state: 'loading' | 'hidden';
}

const SkeletonMessageBubble: React.FC<SkeletonMessageBubbleProps> = ({ state }) => {
  return (
    <div
      className={`skeleton-message-bubble ${state}`}
      aria-hidden={state === 'hidden'}
      role="status"
      aria-live={state === 'loading' ? 'polite' : 'off'}
    >
      <div className="skeleton-bubble"></div>
    </div>
  );
};

export default SkeletonMessageBubble;

// libs/sveltekit/src/components/SkeletonMessageBubble/SkeletonMessageBubble.svelte
<script lang="ts">
  export type LoadingState = 'loading' | 'hidden';
  export let state: LoadingState = 'loading';
</script>

<div
  class="skeleton-message-bubble"
  aria-hidden={state === 'hidden'}
  role="status"
  aria-live="polite"
>
  {#if state === 'loading'}
    <div class="skeleton"></div>
  {/if}
</div>

<style lang="css">
  @import './SkeletonMessageBubble.css';
</style>
