// libs/sveltekit/src/components/StatusDots/StatusDots.svelte
<script lang="ts">
  export enum Status {
    Online = 'online',
    Offline = 'offline',
    Busy = 'busy',
    Idle = 'idle'
  }

  export let status: Status = Status.Offline;
</script>

<div role="img" aria-label="Status Indicator" class={`status-dot ${status}`}></div>

<style lang="css">
  @import './StatusDots.css';
</style>

// libs/react/src/components/StatusDots/StatusDots.tsx
import React from 'react';

interface StatusDotsProps {
  status: 'online' | 'offline' | 'busy' | 'idle';
}

const StatusDots: React.FC<StatusDotsProps> = ({ status }) => {
  return (
    <div className="status-dots" aria-label={`Status: ${status}`}>
      <span className={`status-dot ${status}`}></span>
    </div>
  );
};

export default StatusDots;
