// libs/react/src/components/EventFilterBar/EventFilterBar.tsx
import React, { useState } from 'react';
import './EventFilterBar.css';

interface FilterOptions {
  category: string;
  dateRange: string;
  location: string;
  participants: number;
}

const EventFilterBar: React.FC = () => {
  const [filters, setFilters] = useState<FilterOptions>({
    category: '',
    dateRange: '',
    location: '',
    participants: 0,
  });

  const handleFilterChange = (field: keyof FilterOptions, value: string | number) => {
    setFilters({ ...filters, [field]: value });
    // Update calendar view based on filters
  };

  const handleResetFilters = () => {
    setFilters({ category: '', dateRange: '', location: '', participants: 0 });
    // Reset calendar view
  };

  return (
    <div className="event-filter-bar">
      <select
        value={filters.category}
        onChange={(e) => handleFilterChange('category', e.target.value)}
        aria-label="Event Category"
      >
        <option value="">All Categories</option>
        {/* Categories should be dynamically loaded */}
      </select>
      <input
        type="text"
        placeholder="Date Range"
        value={filters.dateRange}
        onChange={(e) => handleFilterChange('dateRange', e.target.value)}
        aria-label="Date Range"
      />
      <input
        type="text"
        placeholder="Location"
        value={filters.location}
        onChange={(e) => handleFilterChange('location', e.target.value)}
        aria-label="Location"
      />
      <input
        type="number"
        placeholder="Participants"
        value={filters.participants}
        onChange={(e) => handleFilterChange('participants', Number(e.target.value))}
        aria-label="Participants"
      />
      <button onClick={handleResetFilters}>Reset Filters</button>
    </div>
  );
};

export default EventFilterBar;

// libs/vue/src/components/EventFilterBar/EventFilterBar.vue


<template>
  <div class="event-filter-bar" role="toolbar" aria-label="Event Filter Bar">
    <form @submit.prevent="applyFilters">
      <div class="filter-group">
        <label for="category">Category</label>
        <select id="category" v-model="filters.category">
          <option value="">All Categories</option>
          <option v-for="category in categories" :key="category" :value="category">
            {{ category }}
          </option>
        </select>
      </div>

      <div class="filter-group">
        <label for="date-range">Date Range</label>
        <input type="date" id="start-date" v-model="filters.startDate" />
        <input type="date" id="end-date" v-model="filters.endDate" />
      </div>

      <div class="filter-group">
        <label for="location">Location</label>
        <input type="text" id="location" v-model="filters.location" placeholder="Enter location" />
      </div>

      <div class="filter-group">
        <label for="participants">Participants</label>
        <input type="number" id="participants" v-model="filters.participants" min="1" />
      </div>

      <div class="filter-buttons">
        <button type="submit">Apply Filters</button>
        <button type="button" @click="clearFilters">Clear Filters</button>
      </div>
    </form>

    <div v-if="activeFilters" class="active-filters">
      Active Filters: {{ activeFilters }}
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

export default defineComponent({
  name: 'EventFilterBar',
  setup() {
    const categories = ref(['Conference', 'Meetup', 'Workshop']);
    const filters = ref({
      category: '',
      startDate: '',
      endDate: '',
      location: '',
      participants: 1
    });

    const activeFilters = computed(() => {
      return Object.entries(filters.value)
        .filter(([, value]) => value)
        .map(([key, value]) => `${key}: ${value}`)
        .join(', ');
    });

    const applyFilters = () => {
      console.log('Filters applied:', filters.value);
    };

    const clearFilters = () => {
      filters.value = {
        category: '',
        startDate: '',
        endDate: '',
        location: '',
        participants: 1
      };
    };

    return {
      categories,
      filters,
      activeFilters,
      applyFilters,
      clearFilters
    };
  }
});
</script>




<style scoped lang="css">
@import './EventFilterBar.css';
</style>
