// libs/react/src/components/ChatWindow/ChatWindow.tsx
import React from 'react';

interface ChatWindowProps {
  state: 'open' | 'closed' | 'minimized' | 'maximized';
}

const ChatWindow: React.FC<ChatWindowProps> = ({ state }) => {
  return (
    <div className={`chat-window ${state}`} role="region" aria-label={`Chat window is ${state}`}>
      <div className="chat-content">
        {/* Chat content goes here */}
      </div>
    </div>
  );
};

export default ChatWindow;

// libs/sveltekit/src/components/ChatWindow/ChatWindow.svelte
<script lang="ts">
  export let state: 'open' | 'closed' | 'minimized' | 'maximized' = 'closed';

  function getStateClass() {
    return `state-${state}`;
  }

  function toggleWindow() {
    if (state === 'closed') {
      state = 'open';
    } else {
      state = 'closed';
    }
  }
</script>

<div class="chat-window {getStateClass()}" aria-expanded="{state !== 'closed'}" role="dialog">
  <button on:click={toggleWindow} on:keydown={(e) => e.key === 'Enter' && toggleWindow()} aria-label="Toggle Chat Window">
    Toggle
  </button>
  {#if state !== 'closed'}
    <div class="content">
      <p>Chat content goes here...</p>
    </div>
  {/if}
</div>

<style lang="css">
  @import './ChatWindow.css';
</style>
