// libs/react/src/components/Header/Header.tsx
import React from 'react';

interface HeaderProps {
  state: 'visible' | 'hidden' | 'sticky' | 'collapsed' | 'expanded';
  title: string;
  navItems: string[];
}

const Header: React.FC<HeaderProps> = ({ state, title, navItems }) => {
  if (state === 'hidden') {
    return null;
  }

  return (
    <header className={`header ${state}`} role="banner">
      <div className="header-title">{title}</div>
      {state !== 'collapsed' && (
        <nav className="header-nav" aria-label="Main Navigation">
          <ul>
            {navItems.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </nav>
      )}
    </header>
  );
};

export default Header;

// libs/sveltekit/src/components/Header/Header.svelte
<script lang="ts">
  export type HeaderState = 'visible' | 'hidden' | 'sticky' | 'collapsed' | 'expanded';
  export let state: HeaderState = 'visible';
  export let title: string = 'My Website';
</script>

<header class="header" class:hidden={state === 'hidden'} class:sticky={state === 'sticky'}>
  <div class="header-content" class:collapsed={state === 'collapsed'} class:expanded={state === 'expanded'}>
    <h1>{title}</h1>
    <button on:click={() => alert('Menu Clicked!')} aria-label="Toggle Menu">☰</button>
  </div>
</header>

<style lang="css">
  @import './Header.css';
</style>
