// libs/vue/src/components/DataGrid/DataGrid.vue

<template>
  <div class="data-grid" role="grid">
    <div class="search-bar" v-if="searchEnabled">
      <input type="text" v-model="searchQuery" placeholder="Search..." aria-label="Search Data Grid" />
    </div>
    <table>
      <thead>
        <tr>
          <th v-for="(header, index) in headers" :key="index" :style="{ width: resizable ? 'auto' : 'initial' }">
            {{ header }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, rowIndex) in filteredData" :key="rowIndex">
          <td v-for="(cell, cellIndex) in row" :key="cellIndex">{{ cell }}</td>
        </tr>
      </tbody>
    </table>
    <div class="pagination" v-if="paginationEnabled">
      <button @click="prevPage" :disabled="page === 1" aria-label="Previous Page">Previous</button>
      <span>Page {{ page }} of {{ totalPages }}</span>
      <button @click="nextPage" :disabled="page === totalPages" aria-label="Next Page">Next</button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

export default defineComponent({
  name: 'DataGrid',
  props: {
    headers: {
      type: Array as () => string[],
      required: true,
    },
    data: {
      type: Array as () => Array<Array<string>>,
      required: true,
    },
    paginationEnabled: {
      type: Boolean,
      default: false,
    },
    searchEnabled: {
      type: Boolean,
      default: false,
    },
    resizable: {
      type: Boolean,
      default: false,
    },
    itemsPerPage: {
      type: Number,
      default: 10,
    },
  },
  setup(props) {
    const page = ref(1);
    const searchQuery = ref('');

    const filteredData = computed(() => {
      let filtered = props.data;
      if (props.searchEnabled && searchQuery.value) {
        filtered = filtered.filter(row =>
          row.some(cell => cell.toLowerCase().includes(searchQuery.value.toLowerCase()))
        );
      }
      if (props.paginationEnabled) {
        const start = (page.value - 1) * props.itemsPerPage;
        return filtered.slice(start, start + props.itemsPerPage);
      }
      return filtered;
    });

    const totalPages = computed(() => Math.ceil(props.data.length / props.itemsPerPage));

    const prevPage = () => {
      if (page.value > 1) page.value -= 1;
    };

    const nextPage = () => {
      if (page.value < totalPages.value) page.value += 1;
    };

    return { page, searchQuery, filteredData, totalPages, prevPage, nextPage };
  },
});
</script>




<style scoped lang="css">
@import './DataGrid.css';
</style>

// libs/sveltekit/src/components/DataGrid/DataGrid.svelte
<script lang="ts">
  export type GridState = 'paginated' | 'search' | 'resizable';
  export let state: GridState = 'paginated';
  export let data: { [key: string]: any }[] = [];
  export let columns: string[] = [];
  export let pageSize: number = 5;

  let currentPage: number = 1;
  let searchTerm: string = '';
  let filteredData = data;

  function paginateData() {
    const start = (currentPage - 1) * pageSize;
    const end = start + pageSize;
    return filteredData.slice(start, end);
  }

  function handleSearch() {
    filteredData = data.filter(item =>
      columns.some(column => item[column].toString().toLowerCase().includes(searchTerm.toLowerCase()))
    );
    currentPage = 1;
  }

  function nextPage() {
    if (currentPage < Math.ceil(filteredData.length / pageSize)) currentPage++;
  }

  function prevPage() {
    if (currentPage > 1) currentPage--;
  }
</script>

{#if state === 'search'}
  <input
    type="text"
    placeholder="Search..."
    bind:value={searchTerm}
    on:input={handleSearch}
  />
{/if}

<table class={`data-grid grid-${state}`}>
  <thead>
    <tr>
      {#each columns as column}
        <th>{column}</th>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each paginateData() as row}
      <tr>
        {#each columns as column}
          <td>{row[column]}</td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>

{#if state === 'paginated'}
  <div class="pagination-controls">
    <button on:click={prevPage} disabled={currentPage === 1} aria-label="Previous Page">Previous</button>
    <span>Page {currentPage}</span>
    <button on:click={nextPage} disabled={currentPage === Math.ceil(filteredData.length / pageSize)} aria-label="Next Page">Next</button>
  </div>
{/if}

<style lang="css">
  @import './DataGrid.css';
</style>
