// libs/vue/src/components/CheckList/CheckList.vue
<template>
  <div class="checklist">
    <div
      v-for="(item, index) in items"
      :key="index"
      class="checklist-item"
      :class="{ disabled: item.disabled }"
    >
      <input
        type="checkbox"
        :checked="item.checked"
        :indeterminate="item.indeterminate"
        :disabled="item.disabled"
        @change="toggleCheck(index)"
        :id="'checklist-item-' + index"
        aria-checked="item.indeterminate ? 'mixed' : item.checked"
        :aria-disabled="item.disabled"
      />
      <label :for="'checklist-item-' + index">{{ item.label }}</label>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

interface CheckListItem {
  label: string;
  checked: boolean;
  indeterminate: boolean;
  disabled: boolean;
}

export default defineComponent({
  name: 'CheckList',
  props: {
    items: {
      type: Array as () => CheckListItem[],
      required: true,
    },
  },
  methods: {
    toggleCheck(index: number) {
      if (!this.items[index].disabled) {
        this.items[index].checked = !this.items[index].checked;
        this.items[index].indeterminate = false;
        this.$emit('item-checked', index, this.items[index].checked);
      }
    },
  },
});
</script>

<style lang="css">
@import './CheckList.css';
</style>

// libs/sveltekit/src/components/CheckList/CheckList.svelte
<script lang="ts">
  export let items: { id: number; label: string; checked?: boolean; partiallyChecked?: boolean; disabled?: boolean }[] = [];

  const toggleCheck = (item: { id: number; label: string; checked?: boolean; partiallyChecked?: boolean; disabled?: boolean }) => {
    if (!item.disabled) {
      if (item.partiallyChecked) {
        item.partiallyChecked = false;
        item.checked = true;
      } else {
        item.checked = !item.checked;
      }
    }
  };
</script>

<ul class="checklist">
  {#each items as item (item.id)}
    <li 
      class="checklist-item {item.checked ? 'checked' : ''} {item.partiallyChecked ? 'partially-checked' : ''} {item.disabled ? 'disabled' : ''}"
    >
      <input 
        type="checkbox" 
        bind:checked={item.checked} 
        on:change={() => toggleCheck(item)} 
        disabled={item.disabled}
        aria-checked={item.partiallyChecked ? 'mixed' : item.checked}
      />
      <label>{item.label}</label>
    </li>
  {/each}
</ul>

<style lang="css">
  @import './CheckList.css';
</style>
