// libs/sveltekit/src/components/Avatar/Avatar.svelte
<script lang="ts">
  export let imageUrl: string | null = null;
  export let altText: string = 'Avatar';
  export let isGrouped: boolean = false;
</script>

<div class="avatar" role="img" aria-label={altText}>
  {#if imageUrl}
    <img src={imageUrl} alt={altText} />
  {:else}
    <div class="placeholder">{altText.charAt(0)}</div>
  {/if}
  {#if isGrouped}
    <div class="group-indicator" aria-hidden="true"></div>
  {/if}
</div>

<style lang="css">
  @import './Avatar.css';
</style>

// libs/vue/src/components/Avatar/Avatar.vue
<template>
  <div class="avatar" role="img" :aria-label="altText">
    <img v-if="imageSource" :src="imageSource" :alt="altText" />
    <div v-else class="placeholder">{{ initials }}</div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Avatar',
  props: {
    imageSource: {
      type: String,
      default: '',
    },
    altText: {
      type: String,
      default: 'User avatar',
    },
    initials: {
      type: String,
      default: '',
    },
  },
});
</script>

<style lang="css">
@import './Avatar.css';
</style>
