// libs/vue/src/components/VideoPlayer/VideoPlayer.vue
<template>
  <div class="video-player" role="region" aria-label="Video Player">
    <video ref="videoRef" @play="onPlay" @pause="onPause" @waiting="onBuffering" controls>
      <source :src="videoSource" type="video/mp4" />
      Your browser does not support the video tag.
    </video>
    <div class="controls">
      <button @click="togglePlayPause" aria-label="Play/Pause">
        {{ state === 'Play' ? 'Pause' : 'Play' }}
      </button>
      <button @click="toggleFullscreen" aria-label="Fullscreen">
        Fullscreen
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'VideoPlayer',
  props: {
    state: {
      type: String,
      default: 'Pause',
    },
    videoSource: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const videoRef = ref<HTMLVideoElement | null>(null);

    const togglePlayPause = () => {
      if (!videoRef.value) return;
      if (videoRef.value.paused) {
        videoRef.value.play();
      } else {
        videoRef.value.pause();
      }
    };

    const toggleFullscreen = () => {
      if (!videoRef.value) return;
      if (videoRef.value.requestFullscreen) {
        videoRef.value.requestFullscreen();
      }
    };

    const onPlay = () => {
      props.state = 'Play';
    };

    const onPause = () => {
      props.state = 'Pause';
    };

    const onBuffering = () => {
      props.state = 'Buffering';
    };

    return { videoRef, togglePlayPause, toggleFullscreen, onPlay, onPause, onBuffering };
  },
});
</script>

<style lang="css">
@import './VideoPlayer.css';
</style>

// libs/sveltekit/src/components/VideoPlayer/VideoPlayer.svelte
<script lang="ts">
  export let isPlaying: boolean = false;
  export let isPaused: boolean = true;
  export let isBuffering: boolean = false;
  export let isFullscreen: boolean = false;

  function togglePlayPause() {
    isPlaying = !isPlaying;
    isPaused = !isPaused;
  }

  function enterFullscreen() {
    isFullscreen = true;
  }

  function exitFullscreen() {
    isFullscreen = false;
  }

  function toggleFullscreen() {
    isFullscreen ? exitFullscreen() : enterFullscreen();
  }
</script>

<div class="video-player" role="region" aria-label="Video Player">
  <video controls bind:currentTime bind:paused={isPaused}>
    <source src="video.mp4" type="video/mp4" />
    Your browser does not support the video tag.
  </video>
  <div class="player-controls">
    <button on:click={togglePlayPause} aria-pressed={isPlaying}>
      {isPlaying ? 'Pause' : 'Play'}
    </button>
    <button on:click={toggleFullscreen} aria-pressed={isFullscreen}>
      {isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
    </button>
  </div>
</div>

<style lang="css">
  @import './VideoPlayer.css';
</style>
