// libs/react/src/components/NavigationBar/NavigationBar.tsx
import React, { useState } from 'react';

interface NavItem {
  label: string;
  onClick: () => void;
}

interface NavigationBarProps {
  items: NavItem[];
  expanded: boolean;
}

const NavigationBar: React.FC<NavigationBarProps> = ({ items, expanded }) => {
  const [isExpanded, setIsExpanded] = useState(expanded);

  const handleToggle = () => {
    setIsExpanded(!isExpanded);
  };

  return (
    <nav className="navigation-bar">
      <button onClick={handleToggle} aria-expanded={isExpanded} className="nav-toggle">
        Menu
      </button>
      <ul className={`nav-items ${isExpanded ? 'expanded' : 'collapsed'}`}>
        {items.map((item, index) => (
          <li key={index} className="nav-item">
            <button onClick={item.onClick}>{item.label}</button>
          </li>
        ))}
      </ul>
    </nav>
  );
};

export default NavigationBar;

// libs/sveltekit/src/components/NavigationBar/NavigationBar.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let items: { label: string; action: () => void }[] = [];
  export let isExpanded: boolean = false;
  export let activeIndex: number | null = null;

  const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === 'Enter' || event.key === ' ') {
      toggleExpanded();
    }
  };

  const toggleExpanded = () => {
    isExpanded = !isExpanded;
  };

  const activateItem = (index: number) => {
    activeIndex = index;
    items[index].action();
  };

  onMount(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (!event.target.closest('.navigation-bar')) {
        isExpanded = false;
      }
    };

    document.addEventListener('click', handleClickOutside);
    return () => document.removeEventListener('click', handleClickOutside);
  });
</script>

<div class="navigation-bar" role="navigation">
  <button class="nav-trigger" aria-haspopup="true" aria-expanded={isExpanded} on:click={toggleExpanded} on:keydown={handleKeydown}>
    ☰
  </button>
  <ul class="nav-items" class:expanded={isExpanded} role="menu">
    {#each items as item, index}
      <li class={`nav-item ${activeIndex === index ? 'active' : ''}`} role="menuitem">
        <button class="item-link" on:click={() => activateItem(index)}>{item.label}</button>
      </li>
    {/each}
  </ul>
</div>

<style lang="css">
  @import './NavigationBar.css';
</style>
