// libs/sveltekit/src/components/TimelineList/TimelineList.svelte
<script lang="ts">
  export interface TimelineItem {
    id: number;
    title: string;
    description: string;
    completed?: boolean;
  }

  export let items: TimelineItem[] = [];
  export let activeItemId: number;
  export let onItemSelect: (item: TimelineItem) => void;

  function selectItem(item: TimelineItem) {
    activeItemId = item.id;
    onItemSelect(item);
  }
</script>

<ul>
  {#each items as item (item.id)}
    <li
      role="listitem"
      class="timeline-item"
      aria-current={item.id === activeItemId ? 'step' : undefined}
      on:click={() => selectItem(item)}
      on:keydown={(event) => event.key === 'Enter' && selectItem(item)}
      tabindex="0"
    >
      <div class="content">
        <h3>{item.title}</h3>
        <p>{item.description}</p>
      </div>
      {#if item.completed}
        <span class="status completed">Completed</span>
      {:else}
        <span class="status">{item.id === activeItemId ? 'Active' : 'Inactive'}</span>
      {/if}
    </li>
  {/each}
</ul>

<style lang="css">
  @import './TimelineList.css';
</style>

// libs/vue/src/components/TimelineList/TimelineList.vue

<template>
  <ul class="timeline-list" role="list">
    <li
      v-for="(item, index) in items"
      :key="item.id"
      :class="{
        active: index === activeIndex,
        completed: item.completed,
        inactive: !item.completed && index !== activeIndex
      }"
      role="listitem"
    >
      <div class="timeline-content">
        <span class="timeline-label">{{ item.label }}</span>
      </div>
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

interface TimelineItem {
  id: number;
  label: string;
  completed?: boolean;
}

export default defineComponent({
  name: 'TimelineList',
  props: {
    items: {
      type: Array as PropType<TimelineItem[]>,
      required: true,
    },
    activeIndex: {
      type: Number,
      default: 0,
    },
  },
});
</script>




<style scoped lang="css">
@import './TimelineList.css';
</style>
