// libs/sveltekit/src/components/ExpandableList/ExpandableList.svelte
<script lang="ts">
  export let items: Array<{ title: string; content: string; expanded: boolean }> = [];
  export let selectedItemIndex: number | null = null;

  function toggleItem(index: number) {
    items = items.map((item, i) => ({
      ...item,
      expanded: i === index ? !item.expanded : item.expanded
    }));
  }

  function selectItem(index: number) {
    selectedItemIndex = index;
  }
</script>

<ul class="expandable-list">
  {#each items as item, index}
    <li
      class="list-item"
      class:selected={selectedItemIndex === index}
      on:click={() => selectItem(index)}
    >
      <div
        class="list-item-title"
        on:click|stopPropagation={() => toggleItem(index)}
        tabindex="0"
        aria-expanded={item.expanded}
        aria-controls={`content-${index}`}
      >
        {item.title}
      </div>
      {#if item.expanded}
        <div id={`content-${index}`} class="list-item-content">
          {item.content}
        </div>
      {/if}
    </li>
  {/each}
</ul>

<style lang="css">
  .expandable-list {
    list-style-type: none;
    padding: 0;
    margin: 0;
  }

  .list-item {
    border: 1px solid #ddd;
    margin-bottom: 5px;
    cursor: pointer;
    padding: 10px;
    background-color: #f9f9f9;
  }

  .list-item:hover {
    background-color: #f1f1f1;
  }

  .list-item.selected {
    background-color: #e0e0e0;
  }

  .list-item-title {
    font-weight: bold;
  }

  .list-item-content {
    margin-top: 5px;
  }
</style>

// libs/react/src/components/ExpandableList/ExpandableList.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const ListContainer = styled.ul`
  list-style: none;
  padding: 0;
  margin: 0;
`;

const ListItem = styled.li`
  padding: 10px;
  border: 1px solid #ddd;
  margin-bottom: 5px;
  cursor: pointer;
  background-color: ${({ selected }) => (selected ? '#e0f3ff' : 'white')};
  &:hover {
    background-color: #f9f9f9;
  }
`;

const ItemDetail = styled.div`
  margin-top: 5px;
  background-color: #f3f3f3;
  padding: 10px;
  display: ${({ expanded }) => (expanded ? 'block' : 'none')};
`;

const ExpandableList = ({ items }) => {
  const [expandedIndex, setExpandedIndex] = useState(null);
  const [selectedIndex, setSelectedIndex] = useState(null);

  const handleItemClick = (index) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  const handleSelectClick = (index) => {
    setSelectedIndex(selectedIndex === index ? null : index);
  };

  return (
    <ListContainer>
      {items.map((item, index) => (
        <ListItem
          key={index}
          onClick={() => handleItemClick(index)}
          onDoubleClick={() => handleSelectClick(index)}
          selected={selectedIndex === index}
        >
          {item.title}
          <ItemDetail expanded={expandedIndex === index}>{item.detail}</ItemDetail>
        </ListItem>
      ))}
    </ListContainer>
  );
};

ExpandableList.propTypes = {
  items: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string.isRequired,
      detail: PropTypes.string.isRequired,
    })
  ).isRequired,
};

export default ExpandableList;
