// libs/react/src/components/LiveStreamPlayer/LiveStreamPlayer.tsx
import React, { useState, useRef } from 'react';

interface LiveStreamPlayerProps {
  src: string;
  width?: string;
  height?: string;
  autoPlay?: boolean;
  muted?: boolean;
}

const LiveStreamPlayer: React.FC<LiveStreamPlayerProps> = ({
  src,
  width = '800px',
  height = '450px',
  autoPlay = false,
  muted = false,
}) => {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [isPlaying, setIsPlaying] = useState(autoPlay);
  const [isMuted, setIsMuted] = useState(muted);
  const [isBuffering, setIsBuffering] = useState(false);

  const togglePlay = () => {
    if (videoRef.current) {
      if (isPlaying) {
        videoRef.current.pause();
      } else {
        videoRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  const toggleMute = () => {
    if (videoRef.current) {
      videoRef.current.muted = !isMuted;
      setIsMuted(!isMuted);
    }
  };

  const handleBuffering = () => {
    setIsBuffering(true);
  };

  const handlePlaying = () => {
    setIsBuffering(false);
  };

  return (
    <div className="live-stream-player" style={{ width, height }}>
      {isBuffering && <div className="buffering">Buffering...</div>}
      <video
        ref={videoRef}
        src={src}
        width="100%"
        height="100%"
        autoPlay={autoPlay}
        muted={muted}
        onPlay={handlePlaying}
        onWaiting={handleBuffering}
        controls
      />
      <button onClick={togglePlay} aria-label={isPlaying ? 'Pause' : 'Play'}>
        {isPlaying ? 'Pause' : 'Play'}
      </button>
      <button onClick={toggleMute} aria-label={isMuted ? 'Unmute' : 'Mute'}>
        {isMuted ? 'Unmute' : 'Mute'}
      </button>
    </div>
  );
};

export default LiveStreamPlayer;

// libs/sveltekit/src/components/LiveStreamPlayer/LiveStreamPlayer.svelte
<script lang="ts">
  export let isLive: boolean = true;
  export let isPaused: boolean = false;
  export let isBuffering: boolean = false;
  export let isMuted: boolean = false;

  function togglePlayPause() {
    isPaused = !isPaused;
  }

  function toggleMute() {
    isMuted = !isMuted;
  }
</script>

<div class="player-container" role="application" aria-label="Live Stream Player">
  <div class="video-placeholder" aria-hidden={isBuffering || isPaused}>
    {#if isBuffering}
      <div class="status" role="status" aria-live="polite">Buffering...</div>
    {:else if isPaused}
      <div class="status" role="status" aria-live="polite">Paused</div>
    {:else if isLive}
      <div class="status" role="status" aria-live="polite">Live</div>
    {/if}
  </div>
  <div class="controls">
    <button on:click={togglePlayPause} aria-pressed={isPaused}>
      {#if isPaused}Play{#else}Pause{/if}
    </button>
    <button on:click={toggleMute} aria-pressed={isMuted}>
      {#if isMuted}Unmute{#else}Mute{/if}
    </button>
  </div>
</div>

<style lang="css">
  @import './LiveStreamPlayer.css';
</style>
