// libs/sveltekit/src/components/SearchWithAutocomplete/SearchWithAutocomplete.svelte
<script lang="ts">
  export let suggestions: string[] = [];
  export let query: string = '';
  let filteredSuggestions: string[] = [];
  let showSuggestions: boolean = false;

  function onInput(event: InputEvent) {
    const target = event.target as HTMLInputElement;
    query = target.value;
    filteredSuggestions = suggestions.filter((suggestion) =>
      suggestion.toLowerCase().includes(query.toLowerCase())
    );
    showSuggestions = query.length > 0 && filteredSuggestions.length > 0;
  }

  function selectSuggestion(suggestion: string) {
    query = suggestion;
    showSuggestions = false;
  }
</script>

<div class="search-container">
  <input
    type="text"
    bind:value={query}
    on:input={onInput}
    placeholder="Search..."
    aria-autocomplete="list"
    aria-controls="suggestions-list"
  />
  {#if showSuggestions}
    <ul id="suggestions-list" role="listbox" class="suggestions">
      {#each filteredSuggestions as suggestion}
        <li
          role="option"
          on:click={() => selectSuggestion(suggestion)}
          on:keypress={(e) => e.key === 'Enter' && selectSuggestion(suggestion)}
          tabindex="0"
        >
          {suggestion}
        </li>
      {/each}
    </ul>
  {/if}
</div>

<style lang="css">
  @import './SearchWithAutocomplete.css';
</style>

// libs/react/src/components/SearchWithAutocomplete/SearchWithAutocomplete.tsx
import React, { useState, ChangeEvent } from 'react';

interface SearchWithAutocompleteProps {
  suggestions: string[];
}

const SearchWithAutocomplete: React.FC<SearchWithAutocompleteProps> = ({ suggestions }) => {
  const [query, setQuery] = useState('');
  const [filteredSuggestions, setFilteredSuggestions] = useState<string[]>([]);

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value;
    setQuery(value);

    if (value) {
      const filtered = suggestions.filter(suggestion =>
        suggestion.toLowerCase().includes(value.toLowerCase())
      );
      setFilteredSuggestions(filtered);
    } else {
      setFilteredSuggestions([]);
    }
  };

  return (
    <div className="search-with-autocomplete">
      <input
        type="text"
        value={query}
        onChange={handleChange}
        aria-label="Search"
        placeholder="Search..."
      />
      {query && (
        <ul className="suggestions-list" role="listbox">
          {filteredSuggestions.length > 0 ? (
            filteredSuggestions.map((suggestion, index) => (
              <li key={index} role="option" tabIndex={0}>
                {suggestion}
              </li>
            ))
          ) : (
            <li role="option" tabIndex={0}>
              No Results
            </li>
          )}
        </ul>
      )}
    </div>
  );
};

export default SearchWithAutocomplete;
