// libs/vue/src/components/Button/Button.vue
<template>
  <button
    :class="buttonClass"
    :disabled="disabled"
    @click="onClick"
    aria-pressed="active"
  >
    <slot></slot>
  </button>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'Button',
  props: {
    variant: {
      type: String as PropType<'primary' | 'secondary'>,
      default: 'primary',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    active: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    buttonClass() {
      return {
        'button-primary': this.variant === 'primary',
        'button-secondary': this.variant === 'secondary',
        'button-disabled': this.disabled,
        'button-active': this.active,
      };
    },
  },
  methods: {
    onClick() {
      if (!this.disabled) {
        this.$emit('click');
      }
    },
  },
});
</script>

<style lang="css">
@import './Button.css';
</style>

// libs/sveltekit/src/components/Button/Button.svelte
<script lang="ts">
  export let type: 'button' | 'submit' | 'reset' = 'button';
  export let disabled: boolean = false;
  export let variant: 'primary' | 'secondary' = 'primary';
</script>

<button type={type} disabled={disabled} class={`button ${variant}`} aria-disabled={disabled ? 'true' : 'false'}>
  <slot></slot>
</button>

<style lang="css">
  @import './Button.css';
</style>
