// libs/react/src/components/Button/Button.tsx
import React from 'react';

interface ButtonProps {
  label: string;
  onClick: () => void;
  disabled?: boolean;
  variant?: 'primary' | 'secondary';
}

const Button: React.FC<ButtonProps> = ({ label, onClick, disabled = false, variant = 'primary' }) => {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={`button ${variant}`}
      aria-pressed={disabled}
    >
      {label}
    </button>
  );
};

export default Button;

// libs/sveltekit/src/components/Button/Button.svelte
<script lang="ts">
  export let type: 'button' | 'submit' | 'reset' = 'button';
  export let disabled: boolean = false;
  export let variant: 'primary' | 'secondary' = 'primary';
</script>

<button type={type} disabled={disabled} class={`button ${variant}`} aria-disabled={disabled ? 'true' : 'false'}>
  <slot></slot>
</button>

<style lang="css">
  @import './Button.css';
</style>
