// libs/sveltekit/src/components/PinnedList/PinnedList.svelte
<script lang="ts">
  export interface Item {
    id: number;
    text: string;
    pinned: boolean;
    selected: boolean;
  }

  export let items: Item[] = [];
  export let onPinToggle: (id: number) => void;
  export let onSelect: (id: number) => void;

  function handlePinToggle(item: Item) {
    onPinToggle(item.id);
  }

  function handleSelect(item: Item) {
    onSelect(item.id);
  }
</script>

<ul class="pinned-list">
  {#each items as item}
    <li
      class:selected={item.selected}
      on:click={() => handleSelect(item)}
      on:keydown={(e) => e.key === 'Enter' && handleSelect(item)}
      role="button"
      tabindex="0"
    >
      <span>{item.text}</span>
      <button
        on:click={(e) => {
          e.stopPropagation();
          handlePinToggle(item);
        }}
        on:keydown={(e) => {
          if (e.key === 'Enter') {
            e.stopPropagation();
            handlePinToggle(item);
          }
        }}
        aria-label={item.pinned ? 'Unpin item' : 'Pin item'}
      >
        {item.pinned ? '📌' : '📍'}
      </button>
    </li>
  {/each}
</ul>

<style lang="css">
  @import './PinnedList.css';
</style>

// libs/react/src/components/PinnedList/PinnedList.tsx
import React from 'react';

interface PinnedListItem {
  id: string;
  content: string;
  pinned: boolean;
}

interface PinnedListProps {
  items: PinnedListItem[];
  onPinToggle: (id: string) => void;
  onSelect: (id: string) => void;
  selectedItemId: string | null;
}

const PinnedList: React.FC<PinnedListProps> = ({ items, onPinToggle, onSelect, selectedItemId }) => {
  return (
    <ul className="pinned-list">
      {items.map(item => (
        <li
          key={item.id}
          className={`list-item ${item.pinned ? 'pinned' : 'unpinned'} ${selectedItemId === item.id ? 'selected' : ''}`}
          onClick={() => onSelect(item.id)}
          aria-selected={selectedItemId === item.id}
        >
          <span>{item.content}</span>
          <button onClick={() => onPinToggle(item.id)} aria-label={`Toggle pin for ${item.content}`}>
            {item.pinned ? 'Unpin' : 'Pin'}
          </button>
        </li>
      ))}
    </ul>
  );
};

export default PinnedList;
