// libs/react-deprecated/src/components/Breadcrumbs/Breadcrumbs.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './Breadcrumbs.css';

const Breadcrumbs = ({ items, activeIndex }) => {
  return (
    <nav className="breadcrumbs-nav">
      {items.map((item, index) => (
        <span
          key={item}
          className={`breadcrumb-item ${index === activeIndex ? 'active' : ''}`}
        >
          {item}
          {index < items.length - 1 && <span className="breadcrumb-separator">/</span>}
        </span>
      ))}
    </nav>
  );
};

Breadcrumbs.propTypes = {
  items: PropTypes.arrayOf(PropTypes.string).isRequired,
  activeIndex: PropTypes.number,
};

Breadcrumbs.defaultProps = {
  activeIndex: null,
};

export default Breadcrumbs;

// libs/vue/src/components/Breadcrumbs/Breadcrumbs.vue
<template>
  <nav class="breadcrumbs" aria-label="Breadcrumb">
    <ol>
      <li v-for="(item, index) in breadcrumbItems" :key="item.label" :class="{ active: index === activeIndex }">
        <span @click="navigateTo(item)">
          {{ index === activeIndex ? item.label : truncate(item.label) }}
        </span>
        <span v-if="index < breadcrumbItems.length - 1" class="separator">/</span>
      </li>
    </ol>
  </nav>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

interface BreadcrumbItem {
  label: string;
}

export default defineComponent({
  name: 'Breadcrumbs',
  props: {
    breadcrumbItems: {
      type: Array as PropType<BreadcrumbItem[]>,
      required: true,
    },
    activeIndex: {
      type: Number,
      default: 0,
    },
  },
  methods: {
    truncate(label: string) {
      return label.length > 10 ? label.slice(0, 7) + '...' : label;
    },
    navigateTo(item: BreadcrumbItem) {
      this.$emit('navigate', item);
    },
  },
});
</script>

<style lang="css">
@import './Breadcrumbs.css';
</style>
