// libs/sveltekit/src/components/Breadcrumbs/Breadcrumbs.svelte
<script lang="ts">
  export let items: { label: string; href?: string }[] = [];
  export let activeIndex: number | null = null;
  export let truncate: boolean = false;
</script>

<nav class="breadcrumbs-nav" aria-label="Breadcrumb">
  <ol class="breadcrumbs-list" role="list">
    {#each items as item, index}
      <li class="breadcrumb-item" role="listitem">
        {#if truncate && index > 0 && index < items.length - 1}
          {#if index === 1}
            <span class="breadcrumb-ellipsis">...</span>
          {/if}
        {:else}
          <a href={item.href} class="breadcrumb-link" aria-current={activeIndex === index ? 'page' : undefined}>
            {item.label}
          </a>
        {/if}
      </li>
    {/each}
  </ol>
</nav>

<style lang="css">
  @import './Breadcrumbs.css';
</style>

// libs/vue/src/components/Breadcrumbs/Breadcrumbs.vue

<template>
  <nav aria-label="Breadcrumb" class="breadcrumbs">
    <ol class="breadcrumbs-list">
      <li
        v-for="(crumb, index) in breadcrumbs"
        :key="index"
        :class="['breadcrumbs-item', { active: index === activeIndex }]"
      >
        <span
          v-if="index === activeIndex"
          aria-current="page"
          class="breadcrumbs-link"
        >
          {{ crumb.name }}
        </span>
        <span
          v-else
          class="breadcrumbs-link"
          @click="navigateTo(crumb.link)"
        >
          {{ crumb.name }}
        </span>
      </li>
    </ol>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

interface Breadcrumb {
  name: string;
  link?: string;
}

export default defineComponent({
  name: 'Breadcrumbs',
  props: {
    breadcrumbs: {
      type: Array as () => Breadcrumb[],
      required: true,
    },
    activeIndex: {
      type: Number,
      default: 0,
    },
  },
  methods: {
    navigateTo(link?: string) {
      if (link) {
        window.location.href = link;
      }
    },
  },
});
</script>




<style scoped lang="css">
@import './Breadcrumbs.css';
</style>
