// libs/vue/src/components/ColumnVisibilityToggle/ColumnVisibilityToggle.vue

<script lang="ts">
import { defineComponent} from 'vue';

export default defineComponent({
  name: 'ColumnVisibilityToggle',
  props: {
    columns: {
      type: Array as () => { name: string; visible: boolean }[],
      default: () => [],
    },
  },
  setup(props, { emit }) {
    const toggleColumnVisibility = (index: number) => {
      props.columns[index].visible = !props.columns[index].visible;
      emit('update:columns', props.columns);
    };

    return {
      toggleColumnVisibility,
    };
  },
});
</script>

<template>
  <div class="column-visibility-toggle">
    <ul>
      <li v-for="(column, index) in columns" :key="column.name">
        <button @click="toggleColumnVisibility(index)" :aria-pressed="column.visible">
          {{ column.visible ? 'Hide' : 'Show' }} {{ column.name }}
        </button>
      </li>
    </ul>
  </div>
</template>




<style scoped lang="css">
@import './ColumnVisibilityToggle.css';
</style>

// libs/react/src/components/ColumnVisibilityToggle/ColumnVisibilityToggle.tsx
import React, { useState } from 'react';
import './ColumnVisibilityToggle.css';

interface ColumnVisibilityToggleProps {
  columns: { id: string; label: string }[];
  onToggle: (id: string, visible: boolean) => void;
}

const ColumnVisibilityToggle: React.FC<ColumnVisibilityToggleProps> = ({ columns, onToggle }) => {
  const [visibleColumns, setVisibleColumns] = useState<Record<string, boolean>>(
    columns.reduce((acc, column) => ({ ...acc, [column.id]: true }), {})
  );

  const handleToggle = (id: string) => {
    const newState = !visibleColumns[id];
    setVisibleColumns({ ...visibleColumns, [id]: newState });
    onToggle(id, newState);
  };

  return (
    <div className="column-visibility-toggle">
      {columns.map((column) => (
        <div key={column.id} className="column-toggle-item">
          <label>
            <input
              type="checkbox"
              checked={visibleColumns[column.id]}
              onChange={() => handleToggle(column.id)}
              aria-label={`Toggle ${column.label} visibility`}
            />
            {column.label}
          </label>
        </div>
      ))}
    </div>
  );
};

export default ColumnVisibilityToggle;
