// libs/react/src/components/FillTool/FillTool.tsx
import React, { useState } from 'react';
import './FillTool.css';

interface FillToolProps {
  active: boolean;
  onFill: (color: string) => void;
  tolerance: number;
}

const FillTool: React.FC<FillToolProps> = ({ active, onFill, tolerance }) => {
  const [color, setColor] = useState<string>('#000000');

  const handleFillClick = () => {
    if (active) {
      onFill(color);
    }
  };

  return (
    <div className={`fill-tool ${active ? 'active' : 'disabled'}`}>
      <input 
        type="color" 
        value={color} 
        onChange={(e) => setColor(e.target.value)} 
        aria-label="Choose fill color"
      />
      <button 
        onClick={handleFillClick} 
        disabled={!active} 
        aria-label="Fill selected area"
      >
        Fill
      </button>
      <input 
        type="range" 
        min="0" 
        max="100" 
        value={tolerance} 
        aria-label="Adjust fill tolerance"
        className="tolerance-slider"
      />
    </div>
  );
};

export default FillTool;

// libs/vue/src/components/FillTool/FillTool.vue


<template>
  <div class="fill-tool">
    <button :disabled="isDisabled" @click="toggleActive" :class="{ active: isActive }" aria-label="Fill Tool">
      Fill
    </button>
    <div v-if="isActive" class="fill-options">
      <label for="tolerance">Tolerance:</label>
      <input id="tolerance" type="range" min="0" max="100" v-model="tolerance" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'FillTool',
  setup() {
    const isActive = ref(false);
    const isDisabled = ref(false);
    const tolerance = ref(50);

    const toggleActive = () => {
      if (!isDisabled.value) {
        isActive.value = !isActive.value;
      }
    };

    return {
      isActive,
      isDisabled,
      tolerance,
      toggleActive,
    };
  },
});
</script>




<style scoped lang="css">
@import './FillTool.css';
</style>
