// libs/sveltekit/src/components/Textarea/Textarea.svelte
<script lang="ts">
  export let value: string = '';
  export let disabled: boolean = false;

  function handleInput(event: InputEvent) {
    const target = event.target as HTMLTextAreaElement;
    value = target.value;
  }
</script>

<div class="textarea-container">
  <textarea
    class="textarea"
    bind:value={value}
    on:input={handleInput}
    placeholder="Enter text here..."
    disabled={disabled}
    aria-disabled={disabled}
  ></textarea>
</div>

<style lang="css">
  .textarea-container {
    width: 100%;
  }

  .textarea {
    width: 100%;
    padding: 8px;
    border: 1px solid #ccc;
    border-radius: 4px;
    resize: vertical;
  }

  .textarea:disabled {
    background-color: #f5f5f5;
  }
</style>

// app/src/components/TextArea/TextArea.jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const StyledTextarea = styled.textarea`
  width: 100%;
  padding: 10px;
  font-size: 16px;
  border: 1px solid #ccc;
  border-radius: 5px;
  resize: vertical;
  background-color: ${(props) => (props.disabled ? '#f5f5f5' : '#fff')};
  &:focus {
    outline: none;
    border-color: #007bff;
  }
`;

const Textarea = ({ placeholder, disabled, value, onChange }) => {
  return (
    <StyledTextarea
      placeholder={placeholder}
      disabled={disabled}
      value={value}
      onChange={onChange}
    />
  );
};

Textarea.propTypes = {
  placeholder: PropTypes.string,
  disabled: PropTypes.bool,
  value: PropTypes.string,
  onChange: PropTypes.func.isRequired,
};

Textarea.defaultProps = {
  placeholder: 'Enter text...',
  disabled: false,
  value: '',
};

export default Textarea;
