// app/src/components/Upload/Upload.jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const UploadContainer = styled.div`
  display: flex;
  align-items: center;
  padding: 1rem;
  margin: 0.5rem;
  border-radius: 4px;
  background-color: ${({ status }) => {
    switch (status) {
      case 'uploading':
        return '#e8f7ff';
      case 'downloading':
        return '#e0f7fa';
      case 'completed':
        return '#e8f5e9';
      case 'paused':
        return '#fff3e0';
      case 'failed':
        return '#ffebee';
      default:
        return '#f5f5f5';
    }
  }};
  color: ${({ status }) => {
    switch (status) {
      case 'uploading':
        return '#0277bd';
      case 'downloading':
        return '#00838f';
      case 'completed':
        return '#388e3c';
      case 'paused':
        return '#f57c00';
      case 'failed':
        return '#d32f2f';
      default:
        return '#424242';
    }
  }};
`;

const StatusMessage = styled.span`
  margin-left: 1rem;
`;

const Upload = ({ filename, status }) => {
  return (
    <UploadContainer status={status}>
      <span>{filename}</span>
      <StatusMessage>
        {status.charAt(0).toUpperCase() + status.slice(1)}
      </StatusMessage>
    </UploadContainer>
  );
};

Upload.propTypes = {
  filename: PropTypes.string.isRequired,
  status: PropTypes.oneOf(['uploading', 'downloading', 'completed', 'paused', 'failed']).isRequired,
};

export default Upload;

// libs/sveltekit/src/components/Upload/Upload.svelte
<script lang="ts">
  export let status: 'uploading' | 'downloading' | 'completed' | 'paused' | 'failed' = 'completed';
  export let progress: number = 0;

  const getStatusMessage = () => {
    switch (status) {
      case 'uploading':
        return 'Uploading...';
      case 'downloading':
        return 'Downloading...';
      case 'completed':
        return 'Completed';
      case 'paused':
        return 'Paused';
      case 'failed':
        return 'Failed';
      default:
        return '';
    }
  };
</script>

<div class="upload" role="progressbar" aria-valuenow={progress} aria-valuemin="0" aria-valuemax="100">
  <div class="upload-status">{getStatusMessage()}</div>
  <div class="progress-bar">
    <div class="progress" style="width: {progress}%"></div>
  </div>
</div>

<style lang="css">
  .upload {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    max-width: 400px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    margin: 10px 0;
  }

  .upload-status {
    margin-bottom: 10px;
    font-size: 16px;
  }

  .progress-bar {
    width: 100%;
    background-color: #f5f5f5;
    border-radius: 4px;
    overflow: hidden;
  }

  .progress {
    height: 10px;
    background-color: #4caf50;
    transition: width 0.3s ease;
  }
</style>
