// libs/vue/src/components/SignalStrengthIndicator/SignalStrengthIndicator.vue
<template>
  <div class="signal-strength" role="img" aria-label="Signal Strength">
    <div 
      v-for="bar in 5" 
      :key="bar" 
      :class="['bar', { active: bar <= strength }]" 
      aria-hidden="true"
    ></div>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'SignalStrengthIndicator',
  props: {
    strength: {
      type: Number as PropType<number>,
      required: true,
    },
    state: {
      type: String as PropType<'full' | 'weak' | 'none'>,
      default: 'none',
    },
  },
});
</script>

<style lang="css">
@import './SignalStrengthIndicator.css';
</style>

// libs/react/src/components/SignalStrengthIndicator/SignalStrengthIndicator.tsx
import React from 'react';

interface SignalStrengthIndicatorProps {
  strength: 'full' | 'weak' | 'none';
}

const SignalStrengthIndicator: React.FC<SignalStrengthIndicatorProps> = ({ strength }) => {
  return (
    <div className="signal-strength-indicator" aria-label={`Signal strength: ${strength}`}>
      <div className={`signal-bar ${strength === 'full' ? 'active' : ''}`}></div>
      <div className={`signal-bar ${strength !== 'none' ? 'active' : ''}`}></div>
      <div className={`signal-bar ${strength === 'full' ? 'active' : ''}`}></div>
    </div>
  );
};

export default SignalStrengthIndicator;
