// libs/vue/src/components/LoadingBarsWithSteps/LoadingBarsWithSteps.vue
<template>
  <div class="loading-bars" role="progressbar" aria-valuenow="activeStep" aria-valuemin="1" :aria-valuemax="steps.length">
    <div v-for="(step, index) in steps" :key="step.id" class="step" :class="getStepClass(index)">
      <div class="step-bar"></div>
      <span class="step-label">{{ step.label }}</span>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

interface Step {
  id: number;
  label: string;
}

export default defineComponent({
  name: 'LoadingBarsWithSteps',
  props: {
    steps: {
      type: Array as () => Step[],
      required: true,
    },
    activeStep: {
      type: Number,
      required: true,
    },
  },
  methods: {
    getStepClass(index: number): string {
      if (index < this.activeStep) return 'completed';
      if (index === this.activeStep) return 'active';
      return 'inactive';
    },
  },
});
</script>

<style lang="css">
@import './LoadingBarsWithSteps.css';
</style>

// libs/sveltekit/src/components/LoadingBarsWithSteps/LoadingBarsWithSteps.svelte
<script lang="ts">
  export let steps: { label: string; status: 'active' | 'completed' | 'inactive' }[] = [];

  const getStepClass = (status: string) => {
    switch (status) {
      case 'active':
        return 'step-active';
      case 'completed':
        return 'step-completed';
      case 'inactive':
        return 'step-inactive';
      default:
        return '';
    }
  };
</script>

<div class="loading-bars">
  {#each steps as { label, status }, index}
    <div class="step {getStepClass(status)}" role="progressbar" aria-valuenow={index + 1} aria-valuemin="0" aria-valuemax={steps.length}>
      <div class="bar"></div>
      <span class="label">{label}</span>
    </div>
  {/each}
</div>

<style lang="css">
  @import './LoadingBarsWithSteps.css';
</style>
