// libs/vue/src/components/HandOfCards/HandOfCards.vue

<template>
  <div class="hand" :class="{ full: isFull, maxLimit: maxLimitReached }">
    <div
      v-for="(card) in hand"
      :key="card.id"
      class="card"
      :class="{ selected: selectedCards.includes(card.id) }"
      @click="toggleSelect(card.id)"
    >
      <slot name="card" :card="card"></slot>
    </div>
    <div v-if="maxLimitReached" class="limit-notification">Max card limit reached</div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

interface Card {
  id: number;
  content: string;
}

export default defineComponent({
  name: 'HandOfCards',
  props: {
    cards: {
      type: Array as () => Card[],
      required: true,
    },
    maxCards: {
      type: Number,
      default: 5,
    },
  },
  setup(props) {
    const hand = ref<Card[]>([...props.cards]);
    const selectedCards = ref<number[]>([]);

    const toggleSelect = (cardId: number) => {
      if (selectedCards.value.includes(cardId)) {
        selectedCards.value = selectedCards.value.filter(id => id !== cardId);
      } else if (selectedCards.value.length < props.maxCards) {
        selectedCards.value.push(cardId);
      }
    };

    const isFull = computed(() => hand.value.length >= props.maxCards);
    const maxLimitReached = computed(() => selectedCards.value.length >= props.maxCards);

    return {
      hand,
      selectedCards,
      isFull,
      maxLimitReached,
      toggleSelect,
    };
  },
});
</script>




<style scoped lang="css">
@import './HandOfCards.css';
</style>

// libs/react/src/components/HandOfCards/HandOfCards.tsx
import React from 'react';
import './HandOfCards.css';

interface CardProps {
  id: number;
  suit: string;
  value: string;
  selected: boolean;
}

interface HandOfCardsProps {
  cards: CardProps[];
  onSelect: (id: number) => void;
  maxCards: number;
}

const HandOfCards: React.FC<HandOfCardsProps> = ({ cards, onSelect, maxCards }) => {
  return (
    <div className="hand-container">
      {cards.length >= maxCards && (
        <div className="limit-notification">Max limit reached</div>
      )}
      <div className="hand-of-cards">
        {cards.map((card) => (
          <div
            key={card.id}
            className={`card ${card.selected ? 'selected' : 'unselected'}`}
            onClick={() => onSelect(card.id)}
          >
            <svg viewBox="0 0 100 140" className="card-svg">
              <rect
                x="5"
                y="5"
                width="90"
                height="130"
                rx="10"
                ry="10"
                className="card-border"
              />
              <text x="10" y="20" className="card-value">{card.value}</text>
              <text x="10" y="40" className="card-suit">{card.suit}</text>
            </svg>
          </div>
        ))}
      </div>
    </div>
  );
};

export default HandOfCards;
