// libs/sveltekit/src/components/SkeletonGroupMemberList/SkeletonGroupMemberList.svelte
<script lang="ts">
  export type LoadingState = 'loading' | 'hidden';
  export let state: LoadingState = 'loading';
</script>

<div 
  class="skeleton-group-member-list" 
  aria-hidden={state === 'hidden'} 
  role="status" 
  aria-label="Loading group member list"
>
  {#if state === 'loading'}
    <div class="skeleton-member" aria-label="Skeleton member"></div>
    <div class="skeleton-member" aria-label="Skeleton member"></div>
    <div class="skeleton-member" aria-label="Skeleton member"></div>
  {/if}
</div>

<style lang="css">
  @import './SkeletonGroupMemberList.css';
</style>

// libs/react/src/components/SkeletonGroupMemberList/SkeletonGroupMemberList.tsx
import React from 'react';

interface SkeletonGroupMemberListProps {
  state: 'loading' | 'hidden';
}

const SkeletonGroupMemberList: React.FC<SkeletonGroupMemberListProps> = ({ state }) => {
  const members = Array.from({ length: 5 });

  return (
    <div
      className={`skeleton-group-member-list ${state}`}
      aria-hidden={state === 'hidden'}
      role="status"
      aria-live={state === 'loading' ? 'polite' : 'off'}
    >
      {members.map((_, index) => (
        <div key={index} className="skeleton-member"></div>
      ))}
    </div>
  );
};

export default SkeletonGroupMemberList;
