// libs/react/src/components/ImageSlider/ImageSlider.tsx
import React, { useState } from 'react';

interface ImageSliderProps {
  images: string[];
  width?: string;
  height?: string;
}

const ImageSlider: React.FC<ImageSliderProps> = ({ images, width = '600px', height = '400px' }) => {
  const [currentIndex, setCurrentIndex] = useState(0);

  const handleNext = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
  };

  const handlePrev = () => {
    setCurrentIndex((prevIndex) => (prevIndex - 1 + images.length) % images.length);
  };

  return (
    <div className="image-slider" style={{ width, height }}>
      <button className="prev-button" onClick={handlePrev} aria-label="Previous image">‹</button>
      <img src={images[currentIndex]} alt={`Slide ${currentIndex + 1}`} className="slider-image" />
      <button className="next-button" onClick={handleNext} aria-label="Next image">›</button>
    </div>
  );
};

export default ImageSlider;

// libs/sveltekit/src/components/ImageSlider/ImageSlider.svelte
<script lang="ts">
  export let images: string[] = [];
  export let activeIndex: number = 0;

  function nextImage() {
    activeIndex = (activeIndex + 1) % images.length;
  }

  function prevImage() {
    activeIndex = (activeIndex - 1 + images.length) % images.length;
  }
</script>

<div class="slider" role="region" aria-live="polite">
  <button on:click={prevImage} aria-label="Previous Image">Prev</button>
  {#if images.length > 0}
    <img src={images[activeIndex]} alt="Image Slider" class="slide" />
  {/if}
  <button on:click={nextImage} aria-label="Next Image">Next</button>
</div>

<style lang="css">
  @import './ImageSlider.css';
</style>
