// libs/react/src/components/DarkModeToggle/DarkModeToggle.tsx
import React, { useState } from 'react';

interface DarkModeToggleProps {
  onToggle: (isDarkMode: boolean) => void;
}

const DarkModeToggle: React.FC<DarkModeToggleProps> = ({ onToggle }) => {
  const [isDarkMode, setIsDarkMode] = useState(false);

  const handleToggle = () => {
    setIsDarkMode(!isDarkMode);
    onToggle(!isDarkMode);
  };

  return (
    <button
      onClick={handleToggle}
      aria-pressed={isDarkMode}
      className={`dark-mode-toggle ${isDarkMode ? 'dark' : 'light'}`}
    >
      {isDarkMode ? 'Switch to Light Mode' : 'Switch to Dark Mode'}
    </button>
  );
};

export default DarkModeToggle;

// libs/sveltekit/src/components/DarkModeToggle/DarkModeToggle.svelte
<script lang="ts">
  import { writable } from 'svelte/store';

  export let isDarkMode: boolean = false;
  const theme = writable(isDarkMode ? 'dark' : 'light');

  function toggleTheme() {
    isDarkMode = !isDarkMode;
    theme.set(isDarkMode ? 'dark' : 'light');
  }
</script>

<div class="dark-mode-toggle" role="switch" aria-checked={isDarkMode} tabindex="0" on:click={toggleTheme} on:keypress={(e) => e.key === 'Enter' && toggleTheme()}>
  <span class={isDarkMode ? 'dark' : 'light'}>
    {isDarkMode ? 'Dark Mode' : 'Light Mode'}
  </span>
</div>

<style lang="css">
  @import './DarkModeToggle.css';
</style>
