// libs/react/src/components/VirtualizedList/VirtualizedList.tsx
import React, { useState, useEffect, useRef } from 'react';

interface VirtualizedListProps {
  items: string[];
  loadMoreItems: () => void;
  isLoading: boolean;
  hasMore: boolean;
}

const VirtualizedList: React.FC<VirtualizedListProps> = ({ items, loadMoreItems, isLoading, hasMore }) => {
  const listRef = useRef<HTMLDivElement | null>(null);

  const onScroll = () => {
    if (!listRef.current || isLoading || !hasMore) return;
    const { scrollTop, scrollHeight, clientHeight } = listRef.current;
    if (scrollHeight - scrollTop === clientHeight) {
      loadMoreItems();
    }
  };

  useEffect(() => {
    const currentRef = listRef.current;
    if (currentRef) {
      currentRef.addEventListener('scroll', onScroll);
    }
    return () => {
      if (currentRef) {
        currentRef.removeEventListener('scroll', onScroll);
      }
    };
  }, [isLoading, hasMore]);

  return (
    <div ref={listRef} className="virtualized-list">
      {items.map((item, index) => (
        <div key={index} className="list-item">
          {item}
        </div>
      ))}
      {isLoading && <div className="loading">Loading more items...</div>}
      {!hasMore && <div className="end-of-list">End of List</div>}
    </div>
  );
};

export default VirtualizedList;

// libs/sveltekit/src/components/VirtualizedList/VirtualizedList.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let items: string[] = [];
  export let isLoadingMore: boolean = false;
  export let hasMoreItems: boolean = true;
  export let loadMoreItems: () => void;

  let listContainer: HTMLDivElement;

  function handleScroll() {
    const bottomThreshold = listContainer.scrollHeight - listContainer.scrollTop - listContainer.clientHeight < 100;
    if (bottomThreshold && hasMoreItems && !isLoadingMore) {
      loadMoreItems();
    }
  }

  onMount(() => {
    listContainer.addEventListener('scroll', handleScroll);
    return () => listContainer.removeEventListener('scroll', handleScroll);
  });
</script>

<div class="virtualized-list" bind:this={listContainer}>
  {#each items as item, index}
    <div class="list-item" tabindex="0">
      {item}
    </div>
  {/each}
  {#if isLoadingMore}
    <div class="loading">Loading more items...</div>
  {/if}
  {#if !hasMoreItems}
    <div class="end-of-list">End of List</div>
  {/if}
</div>

<style lang="css">
  @import './VirtualizedList.css';
</style>
