// libs/react/src/components/TaskCompletionCheckList/TaskCompletionCheckList.tsx
import React from 'react';

interface TaskCompletionCheckListProps {
  items: { label: string; checked: boolean }[];
}

const TaskCompletionCheckList: React.FC<TaskCompletionCheckListProps> = ({ items }) => {
  return (
    <ul className="task-completion-checklist">
      {items.map((item, index) => (
        <li key={index} className={`checklist-item ${item.checked ? 'checked' : 'unchecked'}`} aria-checked={item.checked}>
          <input type="checkbox" checked={item.checked} readOnly />
          <span>{item.label}</span>
        </li>
      ))}
    </ul>
  );
};

export default TaskCompletionCheckList;

// svelte/components/TaskCompletionCheckList/TaskCompletionCheckList.svelte
<script lang="ts">
  export interface Task {
    id: number;
    label: string;
    completed: boolean;
  }

  export let tasks: Task[] = [];
  export let ariaLabel: string = 'Task Completion Checklist';

  function toggleTaskCompletion(taskId: number) {
    tasks = tasks.map(task => 
      task.id === taskId ? { ...task, completed: !task.completed } : task
    );
  }
</script>

<ul class="checklist" aria-label={ariaLabel}>
  {#each tasks as { id, label, completed }}
    <li>
      <input 
        type="checkbox" 
        id={"task-" + id} 
        checked={completed} 
        on:change={() => toggleTaskCompletion(id)} 
      />
      <label for={"task-" + id}>{label}</label>
    </li>
  {/each}
</ul>

<style lang="css">
  @import './TaskCompletionCheckList.css';
</style>
