// libs/vue/src/components/DateTimeStamp/DateTimeStamp.vue
<template>
  <time v-if="isDisplayed" class="date-time-stamp" :datetime="dateTime" aria-label="Date and Time">
    {{ formattedDateTime }}
  </time>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue';

export default defineComponent({
  name: 'DateTimeStamp',
  props: {
    dateTime: {
      type: String,
      required: true,
    },
    state: {
      type: String as PropType<'displayed' | 'hidden'>,
      default: 'displayed',
      validator: (value: string) => ['displayed', 'hidden'].includes(value),
    },
  },
  setup(props) {
    const isDisplayed = computed(() => props.state === 'displayed');
    const formattedDateTime = computed(() => new Date(props.dateTime).toLocaleString());

    return { isDisplayed, formattedDateTime };
  },
});
</script>

<style lang="css">
@import './DateTimeStamp.css';
</style>

// libs/react/src/components/DateTimeStamp/DateTimeStamp.tsx
import React from 'react';

interface DateTimeStampProps {
  state: 'displayed' | 'hidden';
  dateTime: string;
}

const DateTimeStamp: React.FC<DateTimeStampProps> = ({ state, dateTime }) => {
  return (
    <div 
      className={`date-time-stamp ${state}`} 
      aria-hidden={state === 'hidden'} 
      aria-label={`Date and time is ${state}`}>
      {state === 'displayed' ? dateTime : null}
    </div>
  );
};

export default DateTimeStamp;
