// vue/components/MultiselectList/MultiselectList.vue
<template>
  <div class="multiselect-list" role="listbox" aria-multiselectable="true">
    <ul class="item-list" role="list" aria-label="Selectable Items">
      <li
        v-for="(item, index) in items"
        :key="item.value"
        :class="['list-item', { selected: selectedItems.includes(item.value), disabled: item.disabled }]"
        @click="toggleItemSelection(item)"
        @mouseover="hoveredItem = item.value"
        @mouseleave="hoveredItem = null"
        :aria-selected="selectedItems.includes(item.value)"
        :aria-disabled="item.disabled"
      >
        {{ item.label }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

interface Item {
  value: string;
  label: string;
  disabled?: boolean;
}

export default defineComponent({
  name: 'MultiselectList',
  props: {
    items: {
      type: Array as () => Item[],
      required: true,
    },
  },
  setup() {
    const selectedItems = ref<string[]>([]);
    const hoveredItem = ref<string | null>(null);

    const toggleItemSelection = (item: Item) => {
      if (item.disabled) return;
      const index = selectedItems.value.indexOf(item.value);
      if (index === -1) {
        selectedItems.value.push(item.value);
      } else {
        selectedItems.value.splice(index, 1);
      }
    };

    return { selectedItems, hoveredItem, toggleItemSelection };
  },
});
</script>

<style scoped lang="css">
.multiselect-list {
  width: 100%;
}

.item-list {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.list-item {
  padding: var(--list-item-padding, 8px);
  border-bottom: var(--list-item-border, 1px solid #ccc);
  cursor: pointer;
  transition: background-color 0.2s;
}

.list-item.selected {
  background-color: var(--selected-bg, #d1e7dd);
  color: var(--selected-color, #0f5132);
}

.list-item.disabled {
  background-color: var(--disabled-bg, #f8f9fa);
  color: var(--disabled-color, #6c757d);
  cursor: not-allowed;
}

.list-item:hover:not(.disabled) {
  background-color: var(--hover-bg, #e2e6ea);
}
</style>

// app/src/components/Multiselectlist/Multiselectlist.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const ListContainer = styled.div`
  width: 100%;
`;

const List = styled.ul`
  list-style-type: none;
  padding: 0;
  margin: 0;
`;

const ListItem = styled.li`
  padding: 10px;
  border: 1px solid #ccc;
  margin-bottom: 5px;
  background-color: ${props => (props.selected ? '#007bff' : '#fff')};
  color: ${props => (props.selected ? '#fff' : '#000')};
  cursor: ${props => (props.disabled ? 'not-allowed' : 'pointer')};
  opacity: ${props => (props.disabled ? 0.5 : 1)};
  &:hover {
    background-color: ${props => (props.selected ? '#0056b3' : '#f0f0f0')};
  }
`;

const MultiSelectList = ({ items, disabled }) => {
  const [selectedItems, setSelectedItems] = useState([]);

  const handleItemClick = (item) => {
    if (disabled) return;
    if (selectedItems.includes(item)) {
      setSelectedItems(selectedItems.filter(i => i !== item));
    } else {
      setSelectedItems([...selectedItems, item]);
    }
  };

  return (
    <ListContainer>
      <List>
        {items.map((item, index) => (
          <ListItem
            key={index}
            selected={selectedItems.includes(item)}
            disabled={disabled}
            onClick={() => handleItemClick(item)}
          >
            {item}
          </ListItem>
        ))}
      </List>
    </ListContainer>
  );
};

MultiSelectList.propTypes = {
  items: PropTypes.arrayOf(PropTypes.string).isRequired,
  disabled: PropTypes.bool,
};

MultiSelectList.defaultProps = {
  disabled: false,
};

export default MultiSelectList;
