// libs/vue/src/components/AudioPlayer/AudioPlayer.vue

<template>
  <div class="audio-player" role="region" aria-label="Audio player">
    <audio ref="audioElement" :src="src" @loadeddata="onLoadedData"></audio>
    <button @click="togglePlay" class="control-button" aria-label="Play/Pause">
      {{ isPlaying ? 'Pause' : 'Play' }}
    </button>
    <button @click="toggleMute" class="control-button" aria-label="Mute/Unmute">
      {{ isMuted ? 'Unmute' : 'Mute' }}
    </button>
    <input
      type="range"
      class="volume-control"
      min="0"
      max="1"
      step="0.1"
      v-model="volume"
      @input="changeVolume"
      aria-label="Volume control"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'AudioPlayer',
  props: {
    src: {
      type: String,
      required: true,
    },
  },
  setup() {
    const audioElement = ref<HTMLAudioElement | null>(null);
    const isPlaying = ref(false);
    const isMuted = ref(false);
    const volume = ref(1);

    const togglePlay = () => {
      const audio = audioElement.value;
      if (audio) {
        if (isPlaying.value) {
          audio.pause();
        } else {
          audio.play();
        }
        isPlaying.value = !isPlaying.value;
      }
    };

    const toggleMute = () => {
      const audio = audioElement.value;
      if (audio) {
        audio.muted = !audio.muted;
        isMuted.value = audio.muted;
      }
    };

    const changeVolume = () => {
      const audio = audioElement.value;
      if (audio) {
        audio.volume = volume.value;
      }
    };

    const onLoadedData = () => {
      const audio = audioElement.value;
      if (audio) {
        volume.value = audio.volume;
      }
    };

    return { isPlaying, isMuted, volume, togglePlay, toggleMute, changeVolume, onLoadedData };
  },
});
</script>



<style scoped lang="css">
@import './AudioPlayer.css';
</style>

// libs/sveltekit/src/components/AudioPlayer/AudioPlayer.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let src: string;
  export let isPlaying: boolean = false;
  export let isMuted: boolean = false;
  export let volume: number = 1;

  let audio: HTMLAudioElement;

  function togglePlay() {
    isPlaying = !isPlaying;
    if (isPlaying) {
      audio.play();
    } else {
      audio.pause();
    }
  }

  function toggleMute() {
    isMuted = !isMuted;
    audio.muted = isMuted;
  }

  function handleVolumeChange(event: Event) {
    const target = event.target as HTMLInputElement;
    volume = parseFloat(target.value);
    audio.volume = volume;
  }

  onMount(() => {
    audio.volume = volume;
    audio.muted = isMuted;
  });
</script>

<div class="audio-player">
  <audio bind:this={audio} src={src} />

  <button on:click={togglePlay} aria-label="Play/Pause">
    {isPlaying ? 'Pause' : 'Play'}
  </button>

  <button on:click={toggleMute} aria-label="Mute/Unmute">
    {isMuted ? 'Unmute' : 'Mute'}
  </button>
  
  <input type="range" min="0" max="1" step="0.01" value={volume} on:input={handleVolumeChange} aria-label="Volume Control" />
</div>

<style lang="css">
  @import './AudioPlayer.css';
</style>
