// libs/sveltekit/src/components/ScrollableHorizontalNavigation/ScrollableHorizontalNavigation.svelte
<script lang="ts">
  export let items: { label: string; action: () => void }[] = [];
  export let activeIndex: number | null = null;

  const activateItem = (index: number) => {
    activeIndex = index;
    items[index].action();
  };
</script>

<div class="scrollable-horizontal-navigation" role="navigation">
  <div class="nav-container">
    <ul class="nav-items" role="menubar">
      {#each items as item, index}
        <li class={`nav-item ${activeIndex === index ? 'active' : ''}`} role="menuitem">
          <button class="item-link" on:click={() => activateItem(index)}>{item.label}</button>
        </li>
      {/each}
    </ul>
  </div>
</div>

<style lang="css">
  @import './ScrollableHorizontalNavigation.css';
</style>

// app/src/components/ScrollableHorizontalNavigation/ScrollableHorizontalNavigation.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './ScrollableHorizontalNavigation.css';

const ScrollableHorizontalNavigation = ({ items }) => {
  return (
    <div className="scrollable-horizontal-navigation">
      <ul className="nav-items">
        {items.map((item, index) => (
          <li key={index} className="nav-item">
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
};

ScrollableHorizontalNavigation.propTypes = {
  items: PropTypes.arrayOf(PropTypes.string).isRequired,
};

export default ScrollableHorizontalNavigation;
