// libs/vue/src/components/GroupMemberList/GroupMemberList.vue
<template>
  <div class="group-member-list">
    <button @click="toggleExpanded" class="toggle-button" aria-expanded="isExpanded">
      {{ isExpanded ? 'Collapse' : 'Expand' }}
    </button>
    <ul v-if="isExpanded" class="member-list" aria-label="Group Members">
      <li v-for="member in members" :key="member.id" class="member-item">
        {{ member.name }}
      </li>
      <li v-if="members.length === 0" class="no-members">
        No members
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

interface Member {
  id: number;
  name: string;
}

export default defineComponent({
  name: 'GroupMemberList',
  props: {
    members: {
      type: Array as () => Member[],
      required: true,
    },
  },
  setup() {
    const isExpanded = ref(false);
    const toggleExpanded = () => {
      isExpanded.value = !isExpanded.value;
    };
    return { isExpanded, toggleExpanded };
  },
});
</script>

<style lang="css">
@import './GroupMemberList.css';
</style>

// libs/sveltekit/src/components/GroupMemberList/GroupMemberList.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export type Member = {
    id: string;
    name: string;
  };

  export let members: Member[] = [];
  export let expanded: boolean = false;

  const dispatch = createEventDispatcher();

  const toggleExpanded = () => {
    expanded = !expanded;
    dispatch('toggle', expanded);
  };

  const handleKeyPress = (event: KeyboardEvent) => {
    if (event.key === 'Enter') {
      toggleExpanded();
    }
  };
</script>

<div class="group-member-list" role="button" tabindex="0" on:click={toggleExpanded} on:keypress={handleKeyPress} aria-expanded={expanded}>
  <div class="header">
    <h3>Group Members ({members.length})</h3>
    <span>{expanded ? '▲' : '▼'}</span>
  </div>
  {#if expanded}
    <ul>
      {#if members.length > 0}
        {#each members as member}
          <li>{member.name}</li>
        {/each}
      {:else}
        <li>No members</li>
      {/if}
    </ul>
  {/if}
</div>

<style lang="css">
  @import './GroupMemberList.css';
</style>
