// libs/react/src/components/RangeSlider/RangeSlider.tsx
import React from 'react';

interface RangeSliderProps {
  min: number;
  max: number;
  value: number;
  step?: number;
  disabled?: boolean;
  labelPosition?: 'left' | 'center' | 'right';
  onChange: (value: number) => void;
}

const RangeSlider: React.FC<RangeSliderProps> = ({ min, max, value, step = 1, disabled = false, labelPosition = 'left', onChange }) => {
  return (
    <div className={`range-slider label-${labelPosition}`}>
      {labelPosition === 'left' && <span className="slider-label">{value}</span>}
      <input
        type="range"
        min={min}
        max={max}
        value={value}
        step={step}
        disabled={disabled}
        onChange={(e) => onChange(Number(e.target.value))}
        aria-valuemin={min}
        aria-valuemax={max}
        aria-valuenow={value}
        aria-disabled={disabled}
      />
      {(labelPosition === 'center' || labelPosition === 'right') && <span className="slider-label">{value}</span>}
    </div>
  );
};

export default RangeSlider;

// libs/sveltekit/src/components/RangeSlider/RangeSlider.svelte
<script lang="ts">
  export let min: number = 0;
  export let max: number = 100;
  export let value: number = 50;
  export let disabled: boolean = false;
  export let label: string = '';
  export let labelPosition: 'left' | 'center' | 'right' = 'right';

  function handleInput(event: Event) {
    value = (event.target as HTMLInputElement).valueAsNumber;
  }
</script>

<div class="range-slider" aria-disabled={disabled} style={`justify-content: ${labelPosition}`}>
  {#if labelPosition === 'left'}
    <label>{label}</label>
  {/if}
  <input
    type="range"
    min={min}
    max={max}
    value={value}
    disabled={disabled}
    on:input={handleInput}
    aria-valuemin={min}
    aria-valuemax={max}
    aria-valuenow={value}
    aria-label={label}
  />
  {#if labelPosition === 'center'}
    <label>{label}</label>
  {/if}
  {#if labelPosition === 'right'}
    <label>{label}</label>
  {/if}
</div>

<style lang="css">
  @import './RangeSlider.css';
</style>
