// libs/sveltekit/src/components/PinnedMessages/PinnedMessages.svelte
<script lang="ts">
  export let visible: boolean = true;
  export let pinned: boolean = false;
  export let messageContent: string = 'This is a pinned message';

  function togglePin() {
    pinned = !pinned;
  }
</script>

{#if visible}
  <div 
    class="pinned-message" 
    role="button" 
    aria-pressed={pinned}
    tabindex="0"
    on:click={togglePin} 
    on:keydown={(e) => e.key === 'Enter' ? togglePin() : null}
  >
    {messageContent}
  </div>
{/if}

<style lang="css">
  @import './PinnedMessages.css';
</style>

// libs/react/src/components/PinnedMessages/PinnedMessages.tsx
import React from 'react';

interface PinnedMessagesProps {
  state: 'pinned' | 'unpinned' | 'visible' | 'hidden';
  messageContent: string;
  onPinToggle: () => void;
}

const PinnedMessages: React.FC<PinnedMessagesProps> = ({ state, messageContent, onPinToggle }) => {
  const isHidden = state === 'hidden';

  return (
    <div
      className={`pinned-message ${state}`}
      role="listitem"
      aria-hidden={isHidden}
      aria-label={state === 'pinned' ? 'Pinned message' : 'Unpinned message'}
    >
      <p>{messageContent}</p>
      <button onClick={onPinToggle} aria-pressed={state === 'pinned'}>
        {state === 'pinned' ? 'Unpin' : 'Pin'}
      </button>
    </div>
  );
};

export default PinnedMessages;
