// libs/vue/src/components/SortableList/SortableList.vue

<template>
  <ul class="sortable-list" :aria-disabled="disabled">
    <li 
      v-for="(item, index) in items" 
      :key="item.id" 
      :draggable="!disabled" 
      @dragstart="onDragStart(index)" 
      @dragover.prevent 
      @drop="onDrop(index)"
      :class="{ dragging: draggingIndex === index }"
    >
      {{ item.label }}
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent, ref, PropType } from 'vue';

interface ListItem {
  id: number;
  label: string;
}

export default defineComponent({
  name: 'SortableList',
  props: {
    items: {
      type: Array as PropType<ListItem[]>,
      required: true,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const draggingIndex = ref<number | null>(null);

    const onDragStart = (index: number) => {
      if (!props.disabled) {
        draggingIndex.value = index;
      }
    };

    const onDrop = (index: number) => {
      if (draggingIndex.value !== null && draggingIndex.value !== index && !props.disabled) {
        const item = props.items[draggingIndex.value];
        props.items.splice(draggingIndex.value, 1);
        props.items.splice(index, 0, item);
        draggingIndex.value = null;
      }
    };

    return { onDragStart, onDrop, draggingIndex };
  },
});
</script>




<style scoped lang="css">
@import './SortableList.css';
</style>

// libs/react/src/components/SortableList/SortableList.tsx
import React, { useState } from 'react';

interface SortableListProps {
  items: string[];
  disabled?: boolean;
}

const SortableList: React.FC<SortableListProps> = ({ items, disabled = false }) => {
  const [list, setList] = useState(items);
  const [draggingIndex, setDraggingIndex] = useState<number | null>(null);

  const handleDragStart = (index: number) => {
    setDraggingIndex(index);
  };

  const handleDragEnter = (index: number) => {
    if (draggingIndex !== null && draggingIndex !== index) {
      const newList = [...list];
      const [removed] = newList.splice(draggingIndex, 1);
      newList.splice(index, 0, removed);
      setDraggingIndex(index);
      setList(newList);
    }
  };

  const handleDrop = () => {
    setDraggingIndex(null);
  };

  return (
    <ul className={`sortable-list ${disabled ? 'disabled' : ''}`} aria-disabled={disabled}>
      {list.map((item, index) => (
        <li
          key={index}
          draggable={!disabled}
          onDragStart={() => handleDragStart(index)}
          onDragEnter={() => handleDragEnter(index)}
          onDragEnd={handleDrop}
          className={draggingIndex === index ? 'dragging' : ''}
        >
          {item}
        </li>
      ))}
    </ul>
  );
};

export default SortableList;
