// libs/sveltekit/src/components/Video/Video.svelte
<script lang="ts">
  export let uploadState: 'uploading' | 'paused' | 'completed' | 'error' = 'completed';

  function handlePause() {
    if (uploadState === 'uploading') {
      uploadState = 'paused';
    }
  }

  function handleResume() {
    if (uploadState === 'paused') {
      uploadState = 'uploading';
    }
  }
</script>

<div class="video" role="region" aria-label="Video Upload">
  <div class="upload-status">
    {#if uploadState === 'uploading'}
      Uploading...
      <button on:click={handlePause}>Pause</button>
    {:else if uploadState === 'paused'}
      Paused
      <button on:click={handleResume}>Resume</button>
    {:else if uploadState === 'completed'}
      Upload Completed
    {:else if uploadState === 'error'}
      Error
    {/if}
  </div>
</div>

<style lang="css">
  @import './Video.css';
</style>

// libs/vue/src/components/Video/Video.vue

<template>
  <div class="video-container" role="region" aria-label="Video Player">
    <video
      ref="videoElement"
      :src="videoSrc"
      @play="onPlay"
      @pause="onPause"
      controls
      class="video-element"
    ></video>
    <div class="status" aria-live="polite">
      <span v-if="isUploading" class="status-text">Uploading...</span>
      <span v-if="isPaused" class="status-text">Paused</span>
      <span v-if="isCompleted" class="status-text">Completed</span>
      <span v-if="isError" class="status-text">Error</span>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'Video',
  props: {
    videoSrc: {
      type: String,
      required: true,
    },
    initialState: {
      type: String as () => 'uploading' | 'paused' | 'completed' | 'error',
      default: 'paused',
    },
  },
  setup(props) {
    const isUploading = ref(props.initialState === 'uploading');
    const isPaused = ref(props.initialState === 'paused');
    const isCompleted = ref(props.initialState === 'completed');
    const isError = ref(props.initialState === 'error');
    const videoElement = ref<HTMLVideoElement | null>(null);

    const onPlay = () => {
      isPaused.value = false;
    };

    const onPause = () => {
      isPaused.value = true;
    };

    return {
      isUploading,
      isPaused,
      isCompleted,
      isError,
      videoElement,
      onPlay,
      onPause,
    };
  },
});
</script>




<style scoped lang="css">
@import './Video.css';
</style>
