// libs/sveltekit/src/components/SearchWithAutocomplete/SearchWithAutocomplete.svelte
<script lang="ts">
  export let suggestions: string[] = [];
  export let query: string = '';
  let filteredSuggestions: string[] = [];
  let showSuggestions: boolean = false;

  function onInput(event: InputEvent) {
    const target = event.target as HTMLInputElement;
    query = target.value;
    filteredSuggestions = suggestions.filter((suggestion) =>
      suggestion.toLowerCase().includes(query.toLowerCase())
    );
    showSuggestions = query.length > 0 && filteredSuggestions.length > 0;
  }

  function selectSuggestion(suggestion: string) {
    query = suggestion;
    showSuggestions = false;
  }
</script>

<div class="search-container">
  <input
    type="text"
    bind:value={query}
    on:input={onInput}
    placeholder="Search..."
    aria-autocomplete="list"
    aria-controls="suggestions-list"
  />
  {#if showSuggestions}
    <ul id="suggestions-list" role="listbox" class="suggestions">
      {#each filteredSuggestions as suggestion}
        <li
          role="option"
          on:click={() => selectSuggestion(suggestion)}
          on:keypress={(e) => e.key === 'Enter' && selectSuggestion(suggestion)}
          tabindex="0"
        >
          {suggestion}
        </li>
      {/each}
    </ul>
  {/if}
</div>

<style lang="css">
  @import './SearchWithAutocomplete.css';
</style>

// libs/react-dprecated/src/components/SearchWithAutocomplete/SearchWithAutocomplete.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './SearchWithAutocomplete.css';

const SearchWithAutocomplete = ({ suggestions }) => {
  const [query, setQuery] = useState('');
  const [filteredSuggestions, setFilteredSuggestions] = useState([]);
  const [showSuggestions, setShowSuggestions] = useState(false);

  const handleChange = (e) => {
    const userInput = e.target.value;
    setQuery(userInput);

    const newFilteredSuggestions = suggestions.filter(
      (suggestion) =>
        suggestion.toLowerCase().indexOf(userInput.toLowerCase()) > -1
    );

    setFilteredSuggestions(newFilteredSuggestions);
    setShowSuggestions(true);
  };

  const handleClick = (suggestion) => {
    setQuery(suggestion);
    setFilteredSuggestions([]);
    setShowSuggestions(false);
  };

  return (
    <div className="autocomplete">
      <input
        type="text"
        onChange={handleChange}
        value={query}
        placeholder="Search..."
        className="search-input"
      />
      {showSuggestions && query && (
        <ul className="suggestions-list">
          {filteredSuggestions.length ? (
            filteredSuggestions.map((suggestion, index) => (
              <li
                key={index}
                onClick={() => handleClick(suggestion)}
                className="suggestion-item"
              >
                {suggestion}
              </li>
            ))
          ) : (
            <li className="no-suggestions">No results found</li>
          )}
        </ul>
      )}
    </div>
  );
};

SearchWithAutocomplete.propTypes = {
  suggestions: PropTypes.arrayOf(PropTypes.string).isRequired,
};

export default SearchWithAutocomplete;
