// libs/svelte/src/components/FileUpload/FileUpload.svelte
<script lang="ts">
  export let multiple: boolean = false;
  export let uploadProgress: number = 0;
  export let isDragAndDrop: boolean = true;

  let files: File[] = [];

  function handleFileChange(event: Event) {
    const inputFiles = Array.from((event.target as HTMLInputElement).files || []);
    files = inputFiles;
  }

  function handleDragOver(event: DragEvent) {
    event.preventDefault();
  }

  function handleDrop(event: DragEvent) {
    event.preventDefault();
    const droppedFiles = Array.from(event.dataTransfer?.files || []);
    files = droppedFiles;
  }
</script>

<div
  class="file-upload"
  on:dragover={handleDragOver}
  on:drop={handleDrop}
  aria-label="File Upload"
>
  {#if isDragAndDrop}
    <div class="drop-area" tabindex="0">
      Drag and drop files here or click to browse
    </div>
  {/if}
  <input
    type="file"
    class="file-input"
    multiple={multiple}
    on:change={handleFileChange}
    aria-hidden="true"
  />
  {#if uploadProgress > 0}
    <div class="progress-bar" role="progressbar" aria-valuenow={uploadProgress} aria-valuemin="0" aria-valuemax="100">
      <div class="progress" style="width: {uploadProgress}%"></div>
    </div>
  {/if}
</div>

<style lang="css">
  @import './FileUpload.css';
</style>

// libs/react/src/components/FileUpload/FileUpload.tsx
import React, { useState } from 'react';

interface FileUploadProps {
  multiple?: boolean;
  onFilesUploaded: (files: FileList) => void;
}

const FileUpload: React.FC<FileUploadProps> = ({ multiple = false, onFilesUploaded }) => {
  const [uploadProgress, setUploadProgress] = useState<number[]>([]);
  const [dragging, setDragging] = useState<boolean>(false);

  const handleFilesChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files) {
      setUploadProgress(new Array(files.length).fill(0));
      onFilesUploaded(files);
    }
  };

  const handleDragOver = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setDragging(true);
  };

  const handleDragLeave = () => {
    setDragging(false);
  };

  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setDragging(false);
    const files = event.dataTransfer.files;
    if (files) {
      setUploadProgress(new Array(files.length).fill(0));
      onFilesUploaded(files);
    }
  };

  return (
    <div
      className={`file-upload ${dragging ? 'dragging' : ''}`}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <input
        type="file"
        multiple={multiple}
        onChange={handleFilesChange}
        aria-label={multiple ? "Upload Multiple Files" : "Upload Single File"}
      />
      <div className="progress-bar">
        {uploadProgress.map((progress, index) => (
          <div key={index} className="progress" style={{ width: `${progress}%` }}></div>
        ))}
      </div>
    </div>
  );
};

export default FileUpload;
