// libs/sveltekit/src/components/InteractivePollResults/InteractivePollResults.svelte
<script lang="ts">
  export let options: { label: string; votes: number }[] = [];
  export let totalVotes: number = 0;
  export let status: 'live' | 'completed' | 'closed' = 'live';

  const calculatePercentage = (votes: number) => {
    return totalVotes ? Math.round((votes / totalVotes) * 100) : 0;
  };
</script>

<div class="poll-results" role="status" aria-live="polite">
  {#each options as { label, votes }}
    <div class="poll-option" tabindex="0" on:click={() => {}} on:keydown={(e) => e.key === 'Enter' && {}}>
      <span class="label">{label}</span>
      <span class="bar" style="width: {calculatePercentage(votes)}%;"></span>
      <span class="percentage">{calculatePercentage(votes)}%</span>
    </div>
  {/each}
  <div class="status">Status: {status}</div>
</div>

<style lang="css">
  @import './InteractivePollResults.css';
</style>

// libs/react/src/components/InteractivePollResults/InteractivePollResults.tsx
import React from 'react';

interface PollOption {
  id: number;
  text: string;
  votes: number;
}

interface InteractivePollResultsProps {
  options: PollOption[];
  totalVotes: number;
  status: 'Live' | 'Completed' | 'Closed';
}

const InteractivePollResults: React.FC<InteractivePollResultsProps> = ({ options, totalVotes, status }) => {
  return (
    <div className="poll-results" aria-label={`Poll status: ${status}`}>
      {options.map((option) => (
        <div key={option.id} className="poll-option">
          <span className="option-text">{option.text}</span>
          <span className="option-votes">{((option.votes / totalVotes) * 100).toFixed(1)}%</span>
          <div className="option-bar-container">
            <div
              className="option-bar"
              style={{ width: `${(option.votes / totalVotes) * 100}%` }}
            />
          </div>
        </div>
      ))}
      <div className="poll-status">Status: {status}</div>
    </div>
  );
};

export default InteractivePollResults;
