// libs/sveltekit/src/components/UserAvatar/UserAvatar.svelte
<script lang="ts">
  export let status: 'online' | 'offline' | 'active' | 'away' | 'busy' = 'offline';

  function getStatusClass() {
    return `status-${status}`;
  }
</script>

<div class="user-avatar {getStatusClass()}" aria-label="{status}">
  <img src="/path/to/avatar.png" alt="User Avatar" />
</div>

<style lang="css">
  @import './UserAvatar.css';
</style>

// libs/react/src/components/UserAvatar/UserAvatar.tsx
import React from 'react';

interface UserAvatarProps {
  status: 'online' | 'offline' | 'active' | 'away' | 'busy';
  src: string;
  alt: string;
}

const UserAvatar: React.FC<UserAvatarProps> = ({ status, src, alt }) => {
  return (
    <div className={`user-avatar ${status}`} aria-label={`User status: ${status}`}>
      <img src={src} alt={alt} className="avatar-image" />
      <span className={`status-indicator ${status}`} />
    </div>
  );
};

export default UserAvatar;
