// libs/vue/src/components/DiscardPile/DiscardPile.vue

<template>
  <div
    class="discard-pile"
    :class="{ empty: isEmpty, full: isFull, hovered: isHovered }"
    @dragover.prevent="handleDragOver"
    @dragleave="handleDragLeave"
  >
    <div
      v-for="(card, index) in cards"
      :key="card.id"
      class="card"
      :style="{ top: `${index * overlapOffset}px`, left: `${index * overlapOffset}px` }"
    >
      <slot name="card" :card="card"></slot>
    </div>
    <div v-if="isEmpty" class="empty-notification">Pile is empty</div>
    <div v-if="isFull" class="full-notification">Pile is full</div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

interface Card {
  id: number;
  content: string;
}

export default defineComponent({
  name: 'DiscardPile',
  props: {
    cards: {
      type: Array as () => Card[],
      required: true,
    },
    maxCards: {
      type: Number,
      default: 10,
    },
    overlapOffset: {
      type: Number,
      default: 5,
    },
  },
  setup(props) {
    const cards = ref<Card[]>([...props.cards]);
    const isHovered = ref(false);

    const isEmpty = computed(() => cards.value.length === 0);
    const isFull = computed(() => cards.value.length >= props.maxCards);

    const handleDragOver = () => {
      isHovered.value = true;
    };

    const handleDragLeave = () => {
      isHovered.value = false;
    };

    return {
      cards,
      isEmpty,
      isFull,
      isHovered,
      handleDragOver,
      handleDragLeave,
    };
  },
});
</script>




<style scoped lang="css">
@import './DiscardPile.css';
</style>

// libs/react/src/components/DiscardPile/DiscardPile.tsx
import React from 'react';
import './DiscardPile.css';

interface CardProps {
  id: number;
  suit: string;
  value: string;
}

interface DiscardPileProps {
  cards: CardProps[];
  maxCards: number;
  isHovered: boolean;
  onCardDrop: () => void;
}

const DiscardPile: React.FC<DiscardPileProps> = ({ cards, maxCards, isHovered, onCardDrop }) => {
  return (
    <div
      className={`discard-pile ${isHovered ? 'hovered' : ''}`}
      onDragOver={(e) => e.preventDefault()}
      onDrop={onCardDrop}
    >
      {cards.length === 0 && <div className="empty-cue">Pile is empty</div>}
      {cards.length > 0 && (
        <div className="cards-stack">
          {cards.map((card, index) => (
            <div 
              key={card.id} 
              className="card"
              style={{ top: `-${index * 2}px`, left: `-${index * 2}px` }}
            >
              <svg viewBox="0 0 100 140" className="card-svg">
                <rect
                  x="5"
                  y="5"
                  width="90"
                  height="130"
                  rx="10"
                  ry="10"
                  className="card-border"
                />
                <text x="10" y="20" className="card-value">{card.value}</text>
                <text x="10" y="40" className="card-suit">{card.suit}</text>
              </svg>
            </div>
          ))}
        </div>
      )}
      {cards.length >= maxCards && <div className="full-cue">Pile is full</div>}
    </div>
  );
};

export default DiscardPile;
