// libs/vue/src/components/MediaGallery/MediaGallery.vue
<template>
  <div class="media-gallery" role="region" aria-label="Media Gallery">
    <div class="thumbnails" v-if="state === 'Thumbnail'">
      <img
        v-for="(image, index) in images"
        :key="index"
        :src="image"
        alt="Thumbnail Image"
        @click="selectImage(index)"
        class="thumbnail"
      />
    </div>
    <div class="expanded" v-if="state === 'Expanded' || state === 'Slideshow'">
      <img :src="currentImage" alt="Expanded Image" class="expanded-image" />
      <div class="controls">
        <button @click="previousImage" aria-label="Previous Image">Previous</button>
        <button @click="nextImage" aria-label="Next Image">Next</button>
      </div>
    </div>
    <div class="zoom" v-if="state === 'Zoom In/Out'">
      <img :src="currentImage" alt="Zoomed Image" :style="{ transform: `scale(${zoomLevel})` }" class="zoomed-image" />
      <div class="zoom-controls">
        <button @click="zoomIn" aria-label="Zoom In">Zoom In</button>
        <button @click="zoomOut" aria-label="Zoom Out">Zoom Out</button>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'MediaGallery',
  props: {
    state: {
      type: String,
      default: 'Thumbnail',
    },
    images: {
      type: Array as () => string[],
      required: true,
    },
  },
  setup(props) {
    const currentIndex = ref(0);
    const zoomLevel = ref(1);

    const currentImage = ref(props.images[currentIndex.value]);

    const selectImage = (index: number) => {
      currentIndex.value = index;
      currentImage.value = props.images[index];
    };

    const nextImage = () => {
      if (currentIndex.value < props.images.length - 1) {
        currentIndex.value++;
        currentImage.value = props.images[currentIndex.value];
      }
    };

    const previousImage = () => {
      if (currentIndex.value > 0) {
        currentIndex.value--;
        currentImage.value = props.images[currentIndex.value];
      }
    };

    const zoomIn = () => {
      zoomLevel.value += 0.1;
    };

    const zoomOut = () => {
      if (zoomLevel.value > 0.1) {
        zoomLevel.value -= 0.1;
      }
    };

    return { currentImage, selectImage, nextImage, previousImage, zoomIn, zoomOut, zoomLevel };
  },
});
</script>

<style lang="css">
@import './MediaGallery.css';
</style>

// libs/react-deprecated/src/components/MediaGallery/MediaGallery.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './MediaGallery.css';

const MediaGallery = ({ images }) => {
  const [currentImage, setCurrentImage] = useState(0);
  const [isExpanded, setIsExpanded] = useState(false);
  const [zoomLevel, setZoomLevel] = useState(1);

  const handleNext = () => {
    setCurrentImage((currentImage + 1) % images.length);
  };

  const handlePrevious = () => {
    setCurrentImage((currentImage - 1 + images.length) % images.length);
  };

  const toggleExpand = () => {
    setIsExpanded(!isExpanded);
  };

  const handleZoomIn = () => {
    setZoomLevel(zoomLevel + 0.2);
  };

  const handleZoomOut = () => {
    setZoomLevel(zoomLevel - 0.2 > 0 ? zoomLevel - 0.2 : zoomLevel);
  };

  return (
    <div className="media-gallery">
      <div className={`gallery-image ${isExpanded ? 'expanded' : ''}`}>
        <img 
          src={images[currentImage]} 
          alt={`Image ${currentImage + 1}`} 
          style={{ transform: `scale(${zoomLevel})` }} 
        />
      </div>
      <div className="gallery-controls">
        <button onClick={handlePrevious}>Previous</button>
        <button onClick={toggleExpand}>{isExpanded ? 'Collapse' : 'Expand'}</button>
        <button onClick={handleNext}>Next</button>
        <button onClick={handleZoomIn}>Zoom In</button>
        <button onClick={handleZoomOut}>Zoom Out</button>
      </div>
    </div>
  );
};

MediaGallery.propTypes = {
  images: PropTypes.arrayOf(PropTypes.string).isRequired,
};

export default MediaGallery;
