// libs/react/src/components/EditableDataTable/EditableDataTable.tsx
import React, { useState } from 'react';
import './EditableDataTable.css';

interface Column {
  key: string;
  header: string;
  inputType: 'text' | 'textarea';
  width?: string;
  align?: 'left' | 'center' | 'right';
}

interface EditableDataTableProps {
  data: Record<string, any>[];
  columns: Column[];
  onRowSave: (rowIndex: number, updatedRow: Record<string, any>) => void;
  onRowDelete: (rowIndex: number) => void;
  onAddRow: () => void;
}

const EditableDataTable: React.FC<EditableDataTableProps> = ({ data, columns, onRowSave, onRowDelete, onAddRow }) => {
  const [editingRowIndex, setEditingRowIndex] = useState<number | null>(null);
  const [editedData, setEditedData] = useState<Record<string, any> | null>(null);

  const handleEditClick = (index: number) => {
    setEditingRowIndex(index);
    setEditedData({ ...data[index] });
  };

  const handleSaveClick = (index: number) => {
    if (editedData) {
      onRowSave(index, editedData);
      setEditingRowIndex(null);
    }
  };

  const handleCancelClick = () => {
    setEditingRowIndex(null);
    setEditedData(null);
  };

  const handleInputChange = (key: string, value: string) => {
    if (editedData) {
      setEditedData({
        ...editedData,
        [key]: value,
      });
    }
  };

  return (
    <div className="editable-data-table">
      <button onClick={onAddRow} className="add-row-button">Add Row</button>
      <table>
        <thead>
          <tr>
            {columns.map((column) => (
              <th key={column.key} style={{ width: column.width, textAlign: column.align }}>
                {column.header}
              </th>
            ))}
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {data.map((row, index) => (
            <tr key={index} className={editingRowIndex === index ? 'editing' : ''}>
              {columns.map((column) => (
                <td key={column.key} style={{ textAlign: column.align }}>
                  {editingRowIndex === index ? (
                    column.inputType === 'text' ? (
                      <input
                        type="text"
                        value={editedData ? editedData[column.key] : row[column.key]}
                        onChange={(e) => handleInputChange(column.key, e.target.value)}
                      />
                    ) : (
                      <textarea
                        value={editedData ? editedData[column.key] : row[column.key]}
                        onChange={(e) => handleInputChange(column.key, e.target.value)}
                      />
                    )
                  ) : (
                    row[column.key]
                  )}
                </td>
              ))}
              <td className="row-actions">
                {editingRowIndex === index ? (
                  <>
                    <button onClick={() => handleSaveClick(index)}>Save</button>
                    <button onClick={handleCancelClick}>Cancel</button>
                  </>
                ) : (
                  <>
                    <button onClick={() => handleEditClick(index)}>Edit</button>
                    <button onClick={() => onRowDelete(index)}>Delete</button>
                  </>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default EditableDataTable;

// libs/vue/src/components/EditableDataTable/EditableDataTable.vue

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

interface Column {
  key: string;
  label: string;
  editable?: boolean;
  multiline?: boolean;
  width?: string;
  align?: 'left' | 'center' | 'right';
}

interface Row {
  [key: string]: any;
}

export default defineComponent({
  name: 'EditableDataTable',
  props: {
    columns: {
      type: Array as () => Column[],
      required: true,
    },
    rows: {
      type: Array as () => Row[],
      required: true,
    },
    pagination: Boolean,
    itemsPerPage: {
      type: Number,
      default: 10,
    },
  },
  setup(props) {
    const currentPage = ref(1);
    const editingRow = ref<number | null>(null);
    const editedRows = ref<Row[]>([...props.rows]);

    const paginatedRows = computed(() => {
      if (!props.pagination) return editedRows.value;
      const start = (currentPage.value - 1) * props.itemsPerPage;
      const end = currentPage.value * props.itemsPerPage;
      return editedRows.value.slice(start, end);
    });

    const toggleEditRow = (index: number) => {
      editingRow.value = editingRow.value === index ? null : index;
    };

    const saveRow = (index: number) => {
      // Implement save logic
      toggleEditRow(index);
    };

    const deleteRow = (index: number) => {
      editedRows.value.splice(index, 1);
    };

    return {
      paginatedRows,
      currentPage,
      editingRow,
      toggleEditRow,
      saveRow,
      deleteRow,
      editedRows,
    };
  },
});
</script>

<template>
  <div class="editable-data-table">
    <table>
      <thead>
        <tr>
          <th v-for="column in columns" :key="column.key" :style="{ width: column.width, textAlign: column.align }">
            {{ column.label }}
          </th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, rowIndex) in paginatedRows" :key="row.id" :class="{ editing: editingRow === rowIndex }">
          <td v-for="column in columns" :key="column.key">
            <div v-if="editingRow === rowIndex && column.editable">
              <input v-if="!column.multiline" type="text" v-model="row[column.key]" />
              <textarea v-else v-model="row[column.key]"></textarea>
            </div>
            <div v-else>{{ row[column.key] }}</div>
          </td>
          <td>
            <button @click="toggleEditRow(rowIndex)" v-if="editingRow !== rowIndex">Edit</button>
            <button @click="saveRow(rowIndex)" v-if="editingRow === rowIndex">Save</button>
            <button @click="deleteRow(rowIndex)">Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
    <div v-if="pagination" class="pagination-controls">
      <button @click="currentPage--" :disabled="currentPage === 1">Previous</button>
      <button @click="currentPage++" :disabled="currentPage * itemsPerPage >= editedRows.length">Next</button>
    </div>
  </div>
</template>




<style scoped lang="css">
@import './EditableDataTable.css';
</style>
