// libs/react/src/components/CountdownTimer/CountdownTimer.tsx
import React, { useEffect, useState } from 'react';

interface CountdownTimerProps {
  initialTime: number;
  autoStart: boolean;
}

const CountdownTimer: React.FC<CountdownTimerProps> = ({ initialTime, autoStart }) => {
  const [timeLeft, setTimeLeft] = useState(initialTime);
  const [isRunning, setIsRunning] = useState(autoStart);

  useEffect(() => {
    if (!isRunning) return;
    const timer = setInterval(() => {
      setTimeLeft((prev) => (prev > 0 ? prev - 1 : 0));
    }, 1000);

    return () => clearInterval(timer);
  }, [isRunning]);

  const startTimer = () => setIsRunning(true);
  const pauseTimer = () => setIsRunning(false);
  const resetTimer = () => {
    setIsRunning(false);
    setTimeLeft(initialTime);
  };

  const getStatus = () => {
    if (timeLeft === 0) return 'Completed';
    return isRunning ? 'Running' : 'Paused';
  };

  return (
    <div className="countdown-timer" aria-label={`Timer status: ${getStatus()}`}>
      <div className="timer-display">{timeLeft}s</div>
      {!autoStart && (
        <div className="timer-controls">
          <button onClick={startTimer} disabled={isRunning}>Start</button>
          <button onClick={pauseTimer} disabled={!isRunning}>Pause</button>
          <button onClick={resetTimer}>Reset</button>
        </div>
      )}
    </div>
  );
};

export default CountdownTimer;

// libs/vue/src/components/CountdownTimer/CountdownTimer.vue
<template>
  <div class="countdown-timer" role="timer" :aria-live="isRunning ? 'assertive' : 'polite'" :aria-label="status">
    <div class="time-display">{{ formattedTime }}</div>
    <button @click="toggleRunning">{{ isRunning ? 'Pause' : 'Start' }}</button>
    <button @click="resetTimer">Reset</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';

export default defineComponent({
  name: 'CountdownTimer',
  props: {
    initialTime: {
      type: Number,
      required: true,
    },
  },
  setup(props) {
    const timeLeft = ref(props.initialTime);
    const isRunning = ref(false);
    const interval = ref<number | null>(null);

    const formattedTime = computed(() => {
      const minutes = Math.floor(timeLeft.value / 60);
      const seconds = timeLeft.value % 60;
      return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
    });

    const status = computed(() => {
      if (timeLeft.value === 0) return 'Completed';
      return isRunning.value ? 'Running' : 'Paused';
    });

    const toggleRunning = () => {
      if (isRunning.value) {
        clearInterval(interval.value!);
        interval.value = null;
      } else {
        interval.value = setInterval(() => {
          if (timeLeft.value > 0) timeLeft.value -= 1;
        }, 1000);
      }
      isRunning.value = !isRunning.value;
    };

    const resetTimer = () => {
      timeLeft.value = props.initialTime;
      if (isRunning.value) toggleRunning();
    };

    watch(timeLeft, (newTime) => {
      if (newTime === 0) {
        clearInterval(interval.value!);
        isRunning.value = false;
      }
    });

    return {
      formattedTime,
      toggleRunning,
      resetTimer,
      isRunning,
      status,
    };
  },
});
</script>

<style lang="css">
@import './CountdownTimer.css';
</style>
