// libs/sveltekit/src/components/ContextualList/ContextualList.svelte
<script lang="ts">
  export type ListState = 'default' | 'actionTriggered' | 'dismissed';
  export let state: ListState = 'default';
  export let listItems: { label: string; action: () => void }[] = [];
  let isVisible: boolean = state !== 'dismissed';

  function triggerAction(index: number) {
    listItems[index].action();
  }

  function handleKey(event: KeyboardEvent, index: number) {
    if (event.key === 'Enter' || event.key === ' ') {
      triggerAction(index);
    }
  }
</script>

{#if isVisible}
  <ul class={`contextual-list list-${state}`}>
    {#each listItems as { label, action }, index}
      <li
        role="button"
        tabindex="0"
        on:click={() => triggerAction(index)}
        on:keydown={(event) => handleKey(event, index)}
      >
        {label}
      </li>
    {/each}
  </ul>
{/if}

<style lang="css">
  @import './ContextualList.css';
</style>

// libs/vue/src/components/ContextualList/ContextualList.vue

<template>
  <div class="contextual-list" role="list">
    <div
      v-for="(item, index) in items"
      :key="index"
      class="list-item"
      :class="{ actionTriggered: item.actionTriggered, dismissed: item.dismissed }"
    >
      <span>{{ item.label }}</span>
      <button @click="triggerAction(index)">Action</button>
      <button @click="dismissItem(index)">Dismiss</button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

interface ListItem {
  label: string;
  actionTriggered: boolean;
  dismissed: boolean;
}

export default defineComponent({
  name: 'ContextualList',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
  },
  setup(props) {
    const triggerAction = (index: number) => {
      props.items[index].actionTriggered = true;
    };

    const dismissItem = (index: number) => {
      props.items[index].dismissed = true;
    };

    return { triggerAction, dismissItem };
  },
});
</script>




<style scoped lang="css">
@import './ContextualList.css';
</style>
