// libs/sveltekit/src/components/Textarea/Textarea.svelte
<script lang="ts">
  export let value: string = '';
  export let disabled: boolean = false;

  function handleInput(event: Event) {
    value = (event.target as HTMLTextAreaElement).value;
  }
</script>

<textarea
  class="textarea"
  bind:value={value}
  on:input={handleInput}
  disabled={disabled}
  aria-label="Textarea"
>
</textarea>

<style lang="css">
  @import './Textarea.css';
</style>

// libs/react/src/components/Textarea/Textarea.tsx
import React from 'react';

interface TextareaProps {
  disabled?: boolean;
  placeholder?: string;
  value?: string;
  onChange?: (value: string) => void;
}

const Textarea: React.FC<TextareaProps> = ({ disabled = false, placeholder = '', value = '', onChange }) => {
  const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    if (onChange) {
      onChange(event.target.value);
    }
  };

  return (
    <textarea
      className="custom-textarea"
      disabled={disabled}
      aria-disabled={disabled}
      placeholder={placeholder}
      value={value}
      onChange={handleChange}
    />
  );
};

export default Textarea;
