// libs/react/src/components/SelectableListWithItemDetails/SelectableListWithItemDetails.tsx
import React, { useState } from 'react';

interface SelectableListItem {
  id: string;
  title: string;
  details: string;
}

interface SelectableListWithItemDetailsProps {
  items: SelectableListItem[];
}

const SelectableListWithItemDetails: React.FC<SelectableListWithItemDetailsProps> = ({ items }) => {
  const [selectedItemId, setSelectedItemId] = useState<string | null>(null);
  const [detailsOpen, setDetailsOpen] = useState<boolean>(false);

  const handleSelect = (id: string) => {
    setSelectedItemId(id);
    setDetailsOpen(!detailsOpen);
  };

  return (
    <div>
      <ul className="selectable-list">
        {items.map(item => (
          <li
            key={item.id}
            className={`list-item ${selectedItemId === item.id ? 'selected' : ''}`}
            onClick={() => handleSelect(item.id)}
            aria-expanded={detailsOpen && selectedItemId === item.id}
          >
            {item.title}
          </li>
        ))}
      </ul>
      {selectedItemId && detailsOpen && (
        <div className="details">
          {items.find(item => item.id === selectedItemId)?.details}
        </div>
      )}
    </div>
  );
};

export default SelectableListWithItemDetails;

// svelte/components/SelectableListWithItemDetails/SelectableListWithItemDetails.svelte
<script lang="ts">
  export type ListItem = {
    id: number;
    text: string;
    details: string;
  };

  export let items: ListItem[] = [];
  export let selectedItemId: number | null = null;
  export let detailsOpen: boolean = false;

  const toggleSelection = (itemId: number) => {
    selectedItemId = selectedItemId === itemId ? null : itemId;
    detailsOpen = selectedItemId === itemId;
  };

  const toggleDetails = () => {
    detailsOpen = !detailsOpen;
  };
</script>

<div class="selectable-list" role="list">
  {#each items as item (item.id)}
    <div
      class="list-item {selectedItemId === item.id ? 'selected' : ''}"
      on:click={() => toggleSelection(item.id)}
      role="listitem"
      aria-selected={selectedItemId === item.id}
      tabindex="0"
    >
      {item.text}
      {#if selectedItemId === item.id && detailsOpen}
        <div class="item-details">{item.details}</div>
      {/if}
    </div>
  {/each}
</div>

<style lang="css">
  @import './SelectableListWithItemDetails.css';
</style>
