// libs/react/src/components/ProgressBar/ProgressBar.tsx
import React from 'react';

interface ProgressBarProps {
  progress: number;
  disabled?: boolean;
}

const ProgressBar: React.FC<ProgressBarProps> = ({ progress, disabled }) => {
  return (
    <div
      className={`progress-bar ${disabled ? 'disabled' : ''}`}
      role="progressbar"
      aria-valuenow={progress}
      aria-valuemin={0}
      aria-valuemax={100}
      aria-disabled={disabled}
    >
      <div
        className="progress-bar-fill"
        style={{ width: `${progress}%` }}
      ></div>
    </div>
  );
};

export default ProgressBar;

// libs/sveltekit/src/components/ProgressBar/ProgressBar.svelte
<script lang="ts">
  export let progress: number = 0;
  export let isDisabled: boolean = false;

  $: progressWidth = `${Math.min(Math.max(progress, 0), 100)}%`;
</script>

<div
  class="progress-bar-container"
  aria-valuenow={progress}
  aria-valuemin="0"
  aria-valuemax="100"
  aria-disabled={isDisabled}
>
  <div class="progress-bar" style="width: {progressWidth}"></div>
</div>

<style lang="css">
  @import './ProgressBar.css';
</style>
