// libs/vue/src/components/FileUpload/FileUpload.vue
<template>
  <div
    class="file-upload-container"
    :class="{ 'drag-active': dragActive }"
    @dragover.prevent="handleDragOver"
    @dragleave.prevent="handleDragLeave"
    @drop.prevent="handleDrop"
  >
    <input
      type="file"
      :multiple="multiple"
      @change="handleFileChange"
      ref="fileInput"
    />
    <div v-if="progress > 0" class="progress-bar">
      <div class="progress" :style="{ width: progress + '%' }"></div>
    </div>
    <button type="button" @click="triggerFileInput">Upload Files</button>
    <div v-if="files.length" class="file-list">
      <ul>
        <li v-for="(file, index) in files" :key="index">{{ file.name }}</li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue';

export default defineComponent({
  name: 'FileUpload',
  props: {
    multiple: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    const files = ref<File[]>([]);
    const fileInput = ref<HTMLInputElement | null>(null);
    const dragActive = ref(false);
    const progress = ref(0);

    const handleFileChange = (event: Event) => {
      const target = event.target as HTMLInputElement;
      const selectedFiles = target.files ? Array.from(target.files) : [];
      files.value = selectedFiles;
      simulateProgress();
    };

    const handleDragOver = () => {
      dragActive.value = true;
    };

    const handleDragLeave = () => {
      dragActive.value = false;
    };

    const handleDrop = (event: DragEvent) => {
      const droppedFiles = event.dataTransfer?.files
        ? Array.from(event.dataTransfer.files)
        : [];
      files.value = droppedFiles;
      dragActive.value = false;
      simulateProgress();
    };

    const simulateProgress = () => {
      progress.value = 0;
      const interval = setInterval(() => {
        progress.value += 10;
        if (progress.value >= 100) {
          clearInterval(interval);
        }
      }, 100);
    };

    const triggerFileInput = () => {
      fileInput.value?.click();
    };

    return {
      files,
      fileInput,
      dragActive,
      progress,
      handleFileChange,
      handleDragOver,
      handleDragLeave,
      handleDrop,
      triggerFileInput,
    };
  },
});
</script>

<style lang="css">
@import './FileUpload.css';
</style>

// libs/react-dprecated/src/components/FileUpload/FileUpload.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './FileUpload.css';

const FileUpload = ({ multiple, onFilesChange }) => {
  const [files, setFiles] = useState([]);
  const [progress, setProgress] = useState(0);

  const handleFileChange = (event) => {
    const fileList = Array.from(event.target.files);
    setFiles(fileList);
    onFilesChange(fileList);
  };

  const handleDrop = (event) => {
    event.preventDefault();
    const fileList = Array.from(event.dataTransfer.files);
    setFiles(fileList);
    onFilesChange(fileList);
  };

  const handleDragOver = (event) => {
    event.preventDefault();
  };

  return (
    <div className="file-upload">
      <input
        type="file"
        multiple={multiple}
        onChange={handleFileChange}
      />
      <div
        className="drag-drop-area"
        onDrop={handleDrop}
        onDragOver={handleDragOver}
      >
        Drag & drop files here or click to select
      </div>
      {files.length > 0 && (
        <div className="file-list">
          {files.map((file, index) => (
            <div key={index} className="file-item">
              {file.name}
            </div>
          ))}
        </div>
      )}
      <div className="progress-bar" style={{ width: `${progress}%` }}></div>
    </div>
  );
};

FileUpload.propTypes = {
  multiple: PropTypes.bool,
  onFilesChange: PropTypes.func,
};

FileUpload.defaultProps = {
  multiple: false,
  onFilesChange: () => {},
};

export default FileUpload;
