// libs/sveltekit/src/components/SkeletonThreadContainer/SkeletonThreadContainer.svelte
<script lang="ts">
  export type LoadingState = 'loading' | 'hidden';
  export let state: LoadingState = 'loading';
</script>

<div 
  class="skeleton-thread-container" 
  aria-hidden={state === 'hidden'} 
  role="status" 
  aria-label="Loading thread container"
>
  {#if state === 'loading'}
    <div class="skeleton-thread"></div>
    <div class="skeleton-thread"></div>
    <div class="skeleton-thread"></div>
  {/if}
</div>

<style lang="css">
  @import './SkeletonThreadContainer.css';
</style>

// libs/react/src/components/SkeletonThreadContainer/SkeletonThreadContainer.tsx
import React from 'react';

interface SkeletonThreadContainerProps {
  state: 'loading' | 'hidden';
}

const SkeletonThreadContainer: React.FC<SkeletonThreadContainerProps> = ({ state }) => {
  return (
    <div
      className={`skeleton-thread-container ${state}`}
      aria-hidden={state === 'hidden'}
      role="status"
      aria-live={state === 'loading' ? 'polite' : 'off'}
    >
      <div className="skeleton-thread"></div>
      <div className="skeleton-thread"></div>
      <div className="skeleton-thread"></div>
    </div>
  );
};

export default SkeletonThreadContainer;
