// libs/vue/src/components/PublicViewCalendar/PublicViewCalendar.vue
<template>
  <div class="calendar" role="region" aria-label="Public Calendar">
    <div class="filter-options">
      <label for="category-filter">Category:</label>
      <select id="category-filter" v-model="selectedCategory" aria-label="Filter by category">
        <option value="">All</option>
        <option v-for="category in categories" :key="category" :value="category">{{ category }}</option>
      </select>
      
      <label for="location-filter">Location:</label>
      <select id="location-filter" v-model="selectedLocation" aria-label="Filter by location">
        <option value="">All</option>
        <option v-for="location in locations" :key="location" :value="location">{{ location }}</option>
      </select>
    </div>
    
    <div class="events">
      <div v-for="event in filteredEvents" :key="event.id" class="event" @click="showEventDetails(event)">
        <h3>{{ event.title }}</h3>
        <p>{{ event.date }}</p>
      </div>
    </div>
    
    <transition name="fade">
      <div v-if="selectedEvent" class="event-details" role="dialog" aria-labelledby="event-title">
        <h2 id="event-title">{{ selectedEvent.title }}</h2>
        <p>{{ selectedEvent.description }}</p>
        <button class="close-details" @click="closeEventDetails" aria-label="Close event details">Close</button>
      </div>
    </transition>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

interface Event {
  id: number;
  title: string;
  description: string;
  category: string;
  location: string;
  date: string;
}

export default defineComponent({
  name: 'PublicViewCalendar',
  setup() {
    const events = ref<Event[]>([
      { id: 1, title: 'Project Meeting', description: 'Discussing project scope.', category: 'Work', location: 'Room 101', date: '2023-11-01' },
      { id: 2, title: 'Yoga Class', description: 'Morning yoga session.', category: 'Health', location: 'Gym', date: '2023-11-02' }
    ]);

    const categories = ref([...new Set(events.value.map(event => event.category))]);
    const locations = ref([...new Set(events.value.map(event => event.location))]);
    const selectedCategory = ref('');
    const selectedLocation = ref('');
    const selectedEvent = ref<Event | null>(null);

    const filteredEvents = computed(() => {
      return events.value.filter(event => {
        return (!selectedCategory.value || event.category === selectedCategory.value) &&
               (!selectedLocation.value || event.location === selectedLocation.value);
      });
    });

    const showEventDetails = (event: Event) => {
      selectedEvent.value = event;
    };

    const closeEventDetails = () => {
      selectedEvent.value = null;
    };

    return {
      categories,
      locations,
      selectedCategory,
      selectedLocation,
      filteredEvents,
      selectedEvent,
      showEventDetails,
      closeEventDetails
    };
  }
});
</script>

<style scoped>
@import './PublicViewCalendar.css';
</style>

// libs/react/src/components/PublicViewCalendar/PublicViewCalendar.tsx
import React, { useState } from 'react';
import './PublicViewCalendar.css';

interface Event {
  id: string;
  title: string;
  category: string;
  location: string;
  time: string;
  description: string;
}

interface PublicViewCalendarProps {
  events: Event[];
}

const PublicViewCalendar: React.FC<PublicViewCalendarProps> = ({ events }) => {
  const [selectedEvent, setSelectedEvent] = useState<Event | null>(null);
  const [filter, setFilter] = useState<string>('');

  const filteredEvents = events.filter(
    (event) =>
      event.category.includes(filter) || event.location.includes(filter)
  );

  return (
    <div className="calendar-container">
      <div className="filter-section">
        <input
          type="text"
          placeholder="Filter by category or location"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
        />
      </div>
      <div className="events-list">
        {filteredEvents.map((event) => (
          <div
            key={event.id}
            className="event-item"
            onClick={() => setSelectedEvent(event)}
          >
            <h3>{event.title}</h3>
            <p>{event.time}</p>
          </div>
        ))}
      </div>
      {selectedEvent && (
        <div className="event-details">
          <h2>{selectedEvent.title}</h2>
          <p>{selectedEvent.description}</p>
          <p><strong>Category:</strong> {selectedEvent.category}</p>
          <p><strong>Location:</strong> {selectedEvent.location}</p>
          <button onClick={() => setSelectedEvent(null)}>Close</button>
        </div>
      )}
    </div>
  );
};

export default PublicViewCalendar;
