// libs/sveltekit/src/components/GroupChatName/GroupChatName.svelte
<script lang="ts">
  export let name: string = '';
  export let state: 'displayed' | 'hidden' | 'edited' = 'displayed';
</script>

<div class="group-chat-name {state}" role="heading" aria-label="Group chat name">
  {#if state !== 'hidden'}
    <span>{name}</span>
  {/if}
</div>

<style lang="css">
  @import './GroupChatName.css';
</style>

// libs/react/src/components/GroupChatName/GroupChatName.tsx
import React from 'react';

interface GroupChatNameProps {
  name: string;
  isVisible: boolean;
  isEdited: boolean;
}

const GroupChatName: React.FC<GroupChatNameProps> = ({ name, isVisible, isEdited }) => {
  return (
    <div className={`group-chat-name ${isVisible ? 'displayed' : 'hidden'} ${isEdited ? 'edited' : ''}`} aria-label={isVisible ? `Chat name: ${name}` : 'Chat name hidden'}>
      {isVisible && <span>{name}{isEdited && '*'}</span>}
    </div>
  );
};

export default GroupChatName;
