// app/src/components/Actionablelist/Actionablelist.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './ActionableList.css';

const ActionableList = ({ items, onAction, isLoading, isDisabled }) => {
  const handleAction = (item) => {
    if (!isDisabled && !isLoading) {
      onAction(item);
    }
  };

  return (
    <div className={`actionable-list ${isDisabled ? 'disabled' : ''}`}>
      {items.map((item, index) => (
        <div
          key={index}
          className={`actionable-item ${isLoading ? 'loading' : ''}`}
          onClick={() => handleAction(item)}
        >
          <div className="actionable-item-content">{item.label}</div>
        </div>
      ))}
    </div>
  );
};

ActionableList.propTypes = {
  items: PropTypes.arrayOf(
    PropTypes.shape({
      label: PropTypes.string.isRequired,
    })
  ).isRequired,
  onAction: PropTypes.func.isRequired,
  isLoading: PropTypes.bool,
  isDisabled: PropTypes.bool,
};

ActionableList.defaultProps = {
  isLoading: false,
  isDisabled: false,
};

export default ActionableList;

// libs/vue/src/components/ActionableList/ActionableList.vue
<template>
  <div class="actionable-list">
    <div
      v-for="(item, index) in items"
      :key="index"
      class="list-item"
      :class="{ disabled: item.disabled, loading: item.loading }"
      @click="!item.disabled && !item.loading && triggerAction(index)"
    >
      <span>{{ item.label }}</span>
      <button
        class="action-button"
        :disabled="item.disabled || item.loading"
        @click.stop="!item.disabled && !item.loading && triggerAction(index)"
      >
        <span v-if="item.loading">Loading...</span>
        <span v-else>Action</span>
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

interface ListItem {
  label: string;
  disabled: boolean;
  loading: boolean;
}

export default defineComponent({
  name: 'ActionableList',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
  },
  methods: {
    triggerAction(index: number) {
      this.$emit('action-triggered', index);
    },
  },
});
</script>

<style lang="css">
@import './ActionableList.css';
</style>
