// libs/sveltekit/src/components/ActionableList/ActionableList.svelte
<script lang="ts">
  export type ActionableListState = 'hover' | 'action-triggered' | 'disabled' | 'loading';
  export let state: ActionableListState = 'hover';
  export let items: string[] = [];
  export let disabled: boolean = false;

  function handleAction(item: string) {
    if (!disabled) {
      console.log(`Action triggered for: ${item}`);
    }
  }

  function handleKey(event: KeyboardEvent, item: string) {
    if ((event.key === 'Enter' || event.key === ' ') && !disabled) {
      handleAction(item);
    }
  }
</script>

<ul class={`actionable-list actionable-list-${state}`}>
  {#each items as item}
    <li
      class="actionable-list-item"
      role="button"
      tabindex={disabled ? -1 : 0}
      on:click={() => handleAction(item)}
      on:keydown={(event) => handleKey(event, item)}
      aria-disabled={disabled}
    >
      {item}
    </li>
  {/each}
</ul>

<style lang="css">
  @import './ActionableList.css';
</style>

// libs/vue/src/components/ActionableList/ActionableList.vue

<template>
  <ul class="actionable-list" role="list">
    <li
      v-for="(item, index) in items"
      :key="index"
      class="actionable-list-item"
      :class="{ hovered: hoveredIndex === index, disabled: item.disabled, loading: item.loading }"
      @mouseenter="hoveredIndex = index"
      @mouseleave="hoveredIndex = null"
    >
      <span>{{ item.label }}</span>
      <button
        v-if="!item.disabled && !item.loading"
        @click="triggerAction(index)"
        :disabled="item.disabled"
        :aria-disabled="item.disabled ? 'true' : 'false'"
        class="action-button"
      >
        {{ item.actionLabel }}
      </button>
      <span v-if="item.loading" class="loading-spinner">Loading...</span>
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

interface ListItem {
  label: string;
  actionLabel: string;
  disabled?: boolean;
  loading?: boolean;
}

export default defineComponent({
  name: 'ActionableList',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
  },
  setup() {
    const hoveredIndex = ref<number | null>(null);

    const triggerAction = (index: number) => {
      console.log(`Action triggered for item at index: ${index}`);
    };

    return { hoveredIndex, triggerAction };
  },
});
</script>




<style scoped lang="css">
@import './ActionableList.css';
</style>
