// libs/sveltekit/src/components/Badge/Badge.svelte
<script lang="ts">
  export let type: 'default' | 'notification' | 'status' = 'default';
  export let label: string = '';
</script>

<div class="badge" class:type>
  {#if type === 'notification'}
    <span class="notification" aria-label="Notification">{label}</span>
  {:else if type === 'status'}
    <span class="status" aria-label="Status">{label}</span>
  {:else}
    <span class="default" aria-label="Badge">{label}</span>
  {/if}
</div>

<style lang="css">
  .badge {
    display: inline-block;
    padding: 0.5em 1em;
    border-radius: 12px;
    font-size: 0.875rem;
    font-weight: 600;
  }

  .default {
    background-color: #e0e0e0;
    color: #333;
  }

  .notification {
    background-color: #ff9800;
    color: #fff;
  }

  .status {
    background-color: #4caf50;
    color: #fff;
  }
</style>

// app/src/components/Badge/Badge.jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const BadgeContainer = styled.span`
  display: inline-block;
  padding: 0.5em 1em;
  border-radius: 12px;
  font-size: 0.75em;
  color: white;
  background-color: ${(props) => {
    switch (props.variant) {
      case 'notification':
        return '#3498db';
      case 'status':
        return '#4caf50';
      default:
        return '#7f8c8d';
    }
  }};
`;

const Badge = ({ variant, children }) => {
  return <BadgeContainer variant={variant}>{children}</BadgeContainer>;
};

Badge.propTypes = {
  variant: PropTypes.oneOf(['default', 'notification', 'status']).isRequired,
  children: PropTypes.node,
};

Badge.defaultProps = {
  variant: 'default',
  children: null,
};

export default Badge;
