// libs/sveltekit/src/components/ActionSheet/ActionSheet.svelte
<script lang="ts">
  export let isOpen: boolean = false;
  export let actions: Array<{ label: string; action: () => void }> = [];

  const toggleOpen = () => {
    isOpen = !isOpen;
  };

  const handleAction = (action: () => void) => {
    action();
    isOpen = false;
  };

  const handleKeyPress = (event: KeyboardEvent, action: () => void) => {
    if (event.key === 'Enter' || event.key === ' ') {
      handleAction(action);
    }
  };
</script>

<div class="action-sheet" role="dialog">
  <button on:click={toggleOpen} aria-haspopup="true" aria-expanded={isOpen}>
    Toggle Action Sheet
  </button>

  {#if isOpen}
    <div class="action-sheet-content">
      {#each actions as { label, action }}
        <div
          class="action-item"
          role="button"
          tabindex="0"
          on:click={() => handleAction(action)}
          on:keypress={(event) => handleKeyPress(event, action)}
        >
          {label}
        </div>
      {/each}
    </div>
  {/if}
</div>

<style lang="css">
  @import './ActionSheet.css';
</style>

// libs/react/src/components/ActionSheet/ActionSheet.tsx
import React from 'react';

export interface ActionSheetProps {
  isOpen: boolean;
  onClose: () => void;
  actions: { label: string; onClick: () => void }[];
}

const ActionSheet: React.FC<ActionSheetProps> = ({ isOpen, onClose, actions }) => {
  return (
    <div className={`action-sheet ${isOpen ? 'open' : 'closed'}`} role="dialog" aria-modal="true">
      <div className="action-sheet-backdrop" onClick={onClose}></div>
      <div className="action-sheet-content">
        <ul className="action-list">
          {actions.map((action, index) => (
            <li key={index} className="action-item">
              <button onClick={action.onClick} className="action-button">
                {action.label}
              </button>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default ActionSheet;
