// libs/sveltekit/src/components/CountdownTimer/CountdownTimer.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  
  export let duration: number = 60;
  export let autoStart: boolean = false;
  export let ariaLabel: string = 'Countdown Timer';

  let timeLeft: number = duration;
  let interval: NodeJS.Timeout | null = null;

  const start = () => {
    if (!interval) {
      interval = setInterval(() => {
        if (timeLeft > 0) {
          timeLeft -= 1;
        } else {
          clearInterval(interval);
          interval = null;
        }
      }, 1000);
    }
  };

  const pause = () => {
    if (interval) {
      clearInterval(interval);
      interval = null;
    }
  };

  const reset = () => {
    timeLeft = duration;
    pause();
  };

  onMount(() => {
    if (autoStart) {
      start();
    }
  });
</script>

<div class="countdown-timer" role="timer" aria-label={ariaLabel}>
  <div class="time-display">{timeLeft}s</div>
  <button on:click={start} aria-label="Start Timer">Start</button>
  <button on:click={pause} aria-label="Pause Timer">Pause</button>
  <button on:click={reset} aria-label="Reset Timer">Reset</button>
</div>

<style lang="css">
  @import './CountdownTimer.css';
</style>

// libs/react/src/components/CountdownTimer/CountdownTimer.tsx
import React, { useEffect, useState } from 'react';

interface CountdownTimerProps {
  initialTime: number;
  autoStart: boolean;
}

const CountdownTimer: React.FC<CountdownTimerProps> = ({ initialTime, autoStart }) => {
  const [timeLeft, setTimeLeft] = useState(initialTime);
  const [isRunning, setIsRunning] = useState(autoStart);

  useEffect(() => {
    if (!isRunning) return;
    const timer = setInterval(() => {
      setTimeLeft((prev) => (prev > 0 ? prev - 1 : 0));
    }, 1000);

    return () => clearInterval(timer);
  }, [isRunning]);

  const startTimer = () => setIsRunning(true);
  const pauseTimer = () => setIsRunning(false);
  const resetTimer = () => {
    setIsRunning(false);
    setTimeLeft(initialTime);
  };

  const getStatus = () => {
    if (timeLeft === 0) return 'Completed';
    return isRunning ? 'Running' : 'Paused';
  };

  return (
    <div className="countdown-timer" aria-label={`Timer status: ${getStatus()}`}>
      <div className="timer-display">{timeLeft}s</div>
      {!autoStart && (
        <div className="timer-controls">
          <button onClick={startTimer} disabled={isRunning}>Start</button>
          <button onClick={pauseTimer} disabled={!isRunning}>Pause</button>
          <button onClick={resetTimer}>Reset</button>
        </div>
      )}
    </div>
  );
};

export default CountdownTimer;
